#!/usr/bin/env python3
"""Generates LINKS.md from links.config.json: your real links, plus tagged (UTM) versions for each place you post,
and a plain list of the links only YOUR accounts can create (with the exact steps).
   python3 make_links.py
Nothing here invents a URL. A link is only listed as ready if it is filled in links.config.json."""
import json, os, urllib.parse
ROOT = os.path.dirname(os.path.abspath(__file__))
cfg = {k: v for k, v in json.load(open(os.path.join(ROOT, "links.config.json"))).items() if not k.startswith("_")}
CAMPAIGN = "next-right-step"
CHANNELS = [("Instagram bio", "instagram", "bio"), ("Instagram story", "instagram", "story"), ("Instagram post caption", "instagram", "post"),
            ("TikTok bio", "tiktok", "bio"), ("TikTok caption", "tiktok", "post"), ("Facebook post", "facebook", "post"),
            ("Facebook group", "facebook", "group"), ("Pinterest pin", "pinterest", "pin"),
            ("Email 1-7 (welcome series)", "email", "welcome"), ("Inside the PDF guide", "pdf", "guide"), ("Inside the devotional", "pdf", "devotional")]
TARGETS = [("Linktree (use this in every bio)", "LINKTREE_URL"), ("Etsy shop (7HE H0LY R3UP)", "STORE_URL"), ("Gumroad", "GUMROAD_URL")]

def tag(url, source, medium):
    q = urllib.parse.urlencode({"utm_source": source, "utm_medium": medium, "utm_campaign": CAMPAIGN})
    return url + ("&" if "?" in url else "?") + q

out = ["# 7HE H0LY R3UP: Your Links", "",
       "_Generated by `python3 make_links.py` from `links.config.json`. Re-run it any time you add a link._", "",
       "## 1. Live links (already yours)", "", "| Where | Link |", "|---|---|"]
for name, key in TARGETS:
    out.append(f"| {name} | {cfg.get(key) or '(not set)'} |")
out += ["", "## 2. Tagged links: one per place you post", "",
        "Same destination, but with a tag so you can tell which post sent someone. Paste the right one in each place.",
        "Tags are read by tools like Google Analytics. Etsy and Gumroad also show their own referrer stats. Linktree has its own click counts too.", ""]
for tname, key in TARGETS:
    url = cfg.get(key)
    if not url: continue
    out += [f"### {tname}", "", "| Place | Link |", "|---|---|"]
    for label, src, med in CHANNELS:
        out.append(f"| {label} | {tag(url, src, med)} |")
    out.append("")

out += ["## 3. Links only you can create (about 10 minutes total)", "",
        "I can't make these because they live in your accounts. Each one tells you where it goes in `links.config.json`.", "",
        "| Needed | How to get it | Config key |", "|---|---|---|",
        "| **Guide download link** | Gumroad: New product, name it _The Next Right Step_, set the price to **$0**, upload `dist/next-right-step.pdf`, publish, copy the product link | `GUIDE_DOWNLOAD_URL` |",
        "| **Tracker link** | Go to app.netlify.com/drop, drag in the file `dist/tracker.html` (rename it `index.html` first), copy the web address it gives you. The tracker keeps entries only in the visitor's browser | `TRACKER_URL` |",
        "| **Paid product link** | Etsy or Gumroad: list `dist/you-survived-now-we-rebuild.pdf`, copy the listing link | `PAID_PRODUCT_URL` |",
        "| **Email address to publish** | Choose the address you want strangers to write to (I won't use your account address unless you say so) | `GMAIL_ADDRESS` |",
        "| **Template Creator / Plugin Creator** | Paste the web address of each page you want people to land on | `TEMPLATE_CREATOR_URL`, `PLUGIN_CREATOR_URL` |",
        "| **Unsubscribe link + mailing address** | Your email tool (Gumroad emails, MailerLite, Shopify Email) provides the unsubscribe link and asks for the address. Both are required in marketing email | `UNSUBSCRIBE_URL`, `MAILING_ADDRESS` |", "",
        "Then run `python3 build.py`, check the notes at the bottom, and when it says nothing is missing, `python3 build.py --release`.", ""]

missing = [k for k, v in cfg.items() if not v]
out += ["## 4. Status", "", ("Still empty: " + ", ".join(f"`{m}`" for m in missing)) if missing else "All links are filled in."]
open(os.path.join(ROOT, "LINKS.md"), "w").write("\n".join(out) + "\n")
print("wrote LINKS.md; missing:", ", ".join(missing) or "none")
