# Ninety Days of Standing — days 1–30.
# (day, title, lens, scripture reference, ESV quotation or None, teaching, [3 prompts], soft action, prayer, declaration, also-read)
# Quotations are ESV. Where no quotation is printed, the reference is cited and the passage is summarized in the teaching.

DAYS_1 = [
(1, "A War You Didn't Start", "Childhood · Warfare", "Ephesians 6:12",
 "For we do not wrestle against flesh and blood, but against the rulers, against the authorities, against the cosmic powers over this present darkness, against the spiritual forces of evil in the heavenly places.",
 "You were born into a fight before you had words for it. Scripture says the struggle is real and not only flesh and blood, and Jesus names the thief's work plainly: to steal, kill, and destroy (John 10:10). That does not mean every person who hurt you was a puppet, and it does not mean every hard thing is a demon. It means what was done to you was never God's will, and you are allowed to stand against it. Warfare, at its root, is refusing to agree that harm is normal.",
 ["What did I learn as a child about whether the world was safe?", "Where do I see that fight still running in my home, my body, or my mothering?", "What would it change to believe the harm was never God's plan for me?"],
 "Write one sentence that starts, \"What happened to me was not okay because…\" Say it out loud once.",
 "Jesus, I did not choose the war I was born into, but I choose to stand with You in it. Name the harm as harm. Be near me while I look at it. Amen.",
 "What was done to me was wrong, and God was never on its side.",
 "Workbook 1.1 · 2.1  |  Vol. II Ch. 1, 11"),

(2, "Out of the Dark", "Warfare · Addiction · Motherhood", "1 John 1:7",
 "But if we walk in the light, as he is in the light, we have fellowship with one another, and the blood of Jesus his Son cleanses us from all sin.",
 "Secrecy is not strength. It is where shame grows. For a mother, the secret is often what kind of mother am I, with the substance, the past, the temper, the numbness. For a daughter, it is what happened in the house. Light is not exposure for its own sake. It is one safe person who will not panic, gossip, or use it against you. Warfare begins small: telling the truth to one human being, and watching what happens to the fear.",
 ["What am I most afraid people would think of me as a mother, a daughter, or a woman?", "Who is one person who has earned the right to hear the unedited version?", "What would I need from them in that conversation?"],
 "Name your one person and pick a day this week. You do not have to tell it all. Start with one true sentence.",
 "Father, I have kept this in the dark to survive. Give me one safe person and the courage to say one true thing. Meet me in the room. Amen.",
 "I do not have to carry this alone, and I do not have to carry it in secret.",
 "Workbook Part V Step 1  |  Vol. II Step 1"),

(3, "Both Hands", "Motherhood · Addiction · Childhood", "Romans 7:15",
 "For I do not understand my own actions. For I do not do what I want, but I do the very thing I hate.",
 "Some of what happened to you was not your fault. Some of what you did afterward was. Both are true. Paul, who wrote Romans 7, knew the war inside himself. For mothers this is the hardest page: the harm you took in, and the harm that may have landed on your own children. Holding only the first makes you a permanent victim. Holding only the second makes you your own warden. You need both hands to carry this, and you do not have to carry it on your own.",
 ["What was done to me that was never mine to carry?", "What did I do that was mine to own, and who did it touch?", "What do I want to say to the part of me that is stuck in only one column?"],
 "On a sheet of paper make two columns: \"Done to me\" and \"My part.\" Fill in one line each. Stop there.",
 "Lord, give me honest hands, one to set down what was never mine, one to own what was. Hold the rest. Amen.",
 "I can tell the truth about what was done to me and what I did, and still be held.",
 "Workbook 1.6 · 4.4  |  Vol. II Ch. 10"),

(4, "The Accuser's Favorite Sentence", "Warfare · Motherhood", "Revelation 12:10",
 "...for the accuser of our brothers has been thrown down, who accuses them day and night before our God.",
 "Accusation is one of the enemy's oldest tools: a running commentary that uses your own voice. You are a bad mother. You always ruin it. They would be better off. Conviction sounds different. It names one specific thing, it has a way out, and it moves you toward God and toward the people you hurt. Condemnation names your whole self and offers no door. Learn the difference. It will save you years.",
 ["What sentence about myself do I hear most often, especially about mothering?", "Is it specific with a way out, or sweeping with no exit?", "What would Jesus say to that sentence?"],
 "When the sentence shows up today, answer it once with Romans 8:1 and move on. Do not debate it.",
 "Jesus, You stand with me, not against me. Give me ears to tell Your conviction from the accuser's noise. Amen.",
 "Conviction gives me a door. Condemnation does not come from God.",
 "Workbook 2.3  |  Vol. II Ch. 15"),

(5, "A Body on Guard", "Childhood", "Psalm 56:8",
 "You have kept count of my tossings; put my tears in your bottle. Are they not in your book?",
 "Fight, flight, freeze, and fawn were not character flaws. They were what a small body did to stay alive in a house that was not safe. If your body still scans every room, startles at doors, or goes blank when someone raises their voice, it is doing a job it learned young. That is not weak faith. It also is not always discernment. Some of what feels like warfare is a nervous system still on night duty. God keeps count of every tear, and He is not angry at the body that protected you.",
 ["Which survival response do I default to: fight, flight, freeze, or fawn?", "Where does it show up in how I mother, parent, or love?", "What did it save me from?"],
 "Put a hand on the place where you feel it most. Say, \"You kept me alive. You can rest now.\"",
 "God, You saw every night and every tear. Thank You for the body that kept me alive. Teach it that it does not have to stand guard alone. Amen.",
 "My body is not broken. It is remembering, and it can learn a new rhythm.",
 "Workbook 1.2 · 1.4  |  Vol. II Ch. 17"),

(6, "Where the Little Girl Lives", "Childhood · Motherhood", "Isaiah 66:13",
 "As one whom his mother comforts, so I will comfort you; you shall be comforted in Jerusalem.",
 "Trauma has an age. When you are triggered, you may be thirty-five in the room and six in the body. This matters in motherhood, because your child turning the age you were when you were hurt can bring the old fear roaring back. The answer is not to scold the small part of you. It is to comfort her the way you needed to be comforted, and to let God be the Comforter first. He compares His own comfort to a mother's.",
 ["How old does the fear in my body feel?", "What did that age of me need and not get?", "What would I say to her now?"],
 "Write a three-line note to her. Begin: \"I see you. You are not alone. Here is what is true now…\"",
 "Father, You comfort like a mother. Come to the little girl in me, and teach me to be gentle with her. Amen.",
 "I can comfort the child I was without handing her fear to the child I am raising.",
 "Workbook 1.4 (body map)  |  Vol. II Ch. 5"),

(7, "Six Resets in a Fight", "Warfare · Motherhood", "Psalm 46:10",
 "Be still, and know that I am God. I will be exalted among the nations, I will be exalted in the earth!",
 "A body that is flooded cannot discern anything. Before you ask whether something is spiritual, calm the alarm. Breathe in four, hold seven, out eight. Name five things you see. Cold water on the wrists. Look at every corner of the room until your eyes find the exit. Push the wall for ten seconds. Say, \"This is memory, not danger.\" These are not a replacement for prayer. They are what makes it possible to pray when the baby is crying and your chest is on fire.",
 ["Which reset helps me most right now?", "When during my day do I most need it?", "What gets in the way, and what is one small adjustment?"],
 "Pick one reset and practice it three times today before you need it, once at a calm moment.",
 "Lord, I do not have to fight with a racing heart. Slow me down and be near. Amen.",
 "I have tools. I am not at the mercy of my own alarm.",
 "Workbook 1.4  |  Vol. II Ch. 17"),

(8, "Inventory of the Battlefield", "Childhood · Addiction · Motherhood", "Psalm 139:23-24",
 "Search me, O God, and know my heart! Try me and know my thoughts! And see if there is any grievous way in me, and lead me in the way everlasting!",
 "You cannot work with what you will not name. Today you list the three fronts, not the stories, just the titles. Childhood: what happened. Addiction: what you used and what it did. Motherhood: the pain and the hope in it, whether you are raising children, grieving them, hoping for them, or healing from your own mother. Ten lines, no details. Then circle the one you skipped. That is where the work is, and we are coming back to it slowly.",
 ["What are the main titles under childhood?", "What are the main titles under addiction and motherhood?", "Which one did I skip, and what am I afraid will happen if I name it?"],
 "Write your list on the lines. Circle the skipped one. Do not write about it yet.",
 "God, search me, not to punish me but to lead me. Show me where to start, and not more than I can hold. Amen.",
 "Naming it is the beginning of the end of its power over me.",
 "Workbook 1.3 (Work Page 2)  |  Vol. II Step 2"),

(9, "Medical Before Mystical", "Warfare · Addiction · Motherhood", "Jeremiah 8:22",
 "Is there no balm in Gilead? Is there no physician there? Why then has the health of the daughter of my people not been restored?",
 "Before you decide something is demonic, ask a doctor. Postpartum depression, panic, PTSD, thyroid problems, sleep deprivation, and withdrawal can all feel like attack. Binding a spirit that was a vitamin deficiency will exhaust you and then convince you God does not answer. If you are physically dependent on alcohol, benzodiazepines, or barbiturates, withdrawal can be deadly, so do not stop alone. Prayer and medicine are not enemies. God made doctors too.",
 ["What have I been calling spiritual that might also be physical?", "What appointment have I been avoiding, and why?", "Who could go with me or watch my kids while I go?"],
 "Make the call or book the appointment today. If you are in crisis, call or text 988.",
 "Lord, You made bodies and You made healers. Give me the courage to ask for help and the humility to take it. Amen.",
 "Treating my body is not a lack of faith. It is stewardship.",
 "Workbook 2.2 · Part V Step 2  |  Vol. II Ch. 10 (#9, #12)"),

(10, "A Date and a Plan", "Addiction · Motherhood", "Proverbs 4:26",
 "Ponder the path of your feet; then all your ways will be sure.",
 "Someday is a comfortable word. A date is a decision. If you are ready to stop using, pick the date, clear the first seventy-two hours, remove what needs removing, and tell three people. For mothers, add the practical layer: who has the kids, where is the safe place if home is not safe, what are the legal and child-welfare realities, and what help exists (a legal aid office, a social worker, a treatment program that welcomes mothers and children). Fear of losing your kids is real. Hiding usually makes it worse, and support usually helps.",
 ["What date am I willing to write down?", "Who are the three people I will tell?", "What practical pieces (childcare, safe housing, legal help) need to be lined up first?"],
 "Write the date. Write three names. If a medical detox is needed, call SAMHSA at 1-800-662-4357 before the date.",
 "Father, I am tired of someday. Give me a date, a plan, and people. Hold my children while I do this. Amen.",
 "I am not waiting for someday. I am choosing a day.",
 "Workbook Part V Step 3  |  Vol. II Step 21, 23"),

(11, "What Childhood Taught You", "Childhood", "John 8:32",
 "...and you will know the truth, and the truth will set you free.",
 "Trauma does not just hurt. It teaches. It was my fault. I am too much. Love costs. Safe is boring. I only matter when I am useful. Those lessons were installed when you were small, and you may be passing them down without saying a word. A child watches how you treat yourself. The work is not to hate the lessons but to notice them, so you stop living by house rules from a house that burned down.",
 ["What are the three lies I live by most?", "Where did I learn each one?", "Which one might my kids be learning from me?"],
 "Underline the lie that frightens you most. Next to it write, \"I was taught this. I can unlearn it.\"",
 "Jesus, You are the truth. Show me the lies I took on, and replace them with what is real. Amen.",
 "I was taught these under pressure. I am allowed to unlearn them.",
 "Workbook 1.5  |  Vol. II Ch. 12 (Stage 3)"),

(12, "Lie, Evidence, Truth", "Motherhood · Warfare", "2 Corinthians 10:4-5",
 "For the weapons of our warfare are not of the flesh but have divine power to destroy strongholds. We destroy arguments and every lofty opinion raised against the knowledge of God, and take every thought captive to obey Christ,",
 "Paul's weapons here are not shouting or rituals. They are truth, arguments answered, thoughts brought to Christ. Take the loudest lie about your mothering, such as my kids would be better off without me. Ask who taught it. What evidence have you used to keep believing it? Make yourself find one piece of evidence against it. Then write the truth you choose instead. Do not give the Sunday School answer. Give the real one.",
 ["Lie one, in the words I actually say to myself:", "One piece of evidence against it:", "The truth I am standing on instead, and who in Scripture says it:"],
 "Say the truth out loud to the mirror once today. It will feel awkward. Do it anyway.",
 "Lord, I bring this thought to You instead of agreeing with it. Teach me what is true. Amen.",
 "I am not arguing with a lie. I am replacing it.",
 "Workbook 1.5 (Work Page 4)  |  Vol. II Ch. 15"),

(13, "The Names You Answer To", "Childhood · Addiction · Motherhood", "Isaiah 43:1",
 "But now thus says the LORD, he who created you, O Jacob, he who formed you, O Israel: \"Fear not, for I have redeemed you; I have called you by name, you are mine.\"",
 "Somebody named you and you answered. Too much. Not enough. The family's problem. Addict. Bad mother. Runaway. A name given in someone's worst moment can follow you for decades. God gives names too, and He gives them in love. Whatever you answer to will run your life, so it is worth asking who gave it to you and whether they had the right.",
 ["Which name have I answered to longest?", "Who gave it to me, and what were they like when they said it?", "Does God agree with it?"],
 "Write the old name on a slip of paper. Do not tear it up yet. Just see it from the outside.",
 "Father, You called me by name before anyone else did. Help me hear Yours louder than theirs. Amen.",
 "I belong to God. My name is not the worst thing that was said about me.",
 "Workbook 1.5  |  Vol. II Ch. 12 (Stage 3), Ch. 48"),

(14, "Trading Names", "Warfare · Motherhood · Childhood", "Revelation 2:17",
 "...To the one who conquers I will give some of the hidden manna, and I will give him a white stone, with a new name written on the stone that no one knows except the one who receives it.",
 "Scripture is full of people renamed: Abram to Abraham, Jacob to Israel, Simon to Peter. God's names point at who you are becoming, not who you were at your worst. Trading names is not positive thinking. It is putting a new truth in the place the old one occupied. Too much becomes chosen and beloved. Damaged goods becomes new creation. Bad mother becomes a mother who is learning, with help. Say the new one aloud each morning for thirty days.",
 ["The name I am putting down:", "The name I am choosing, and where it is written in Scripture:", "Who will help me remember it?"],
 "Write the new name where you will see it every morning, like the bathroom mirror or the fridge.",
 "Jesus, I give You the old name. Teach me to answer to the one You give. Amen.",
 "I answer to what God calls me, not what they called me.",
 "Vol. II Ch. 48 (Trading the Names)  |  Workbook 3.1"),

(15, "It Was Not Your Fault", "Childhood", "Psalm 103:13",
 "As a father shows compassion to his children, so the LORD shows compassion to those who fear him.",
 "A child cannot consent. A person being coerced is not choosing. A person in survival is not strategizing. Your body responding physically was never agreement. Shame built a city on that lie. Notice that God does not meet you with a lecture. He shows compassion the way a father does for his child. Take your name off a crime you did not commit.",
 ["What am I still blaming myself for that was never a choice?", "How old was I?", "What would I say to a child who told me this story?"],
 "Say it as if you were speaking to a child you love: \"It was not your fault.\" Then say it to yourself.",
 "Father, You are not angry at the child I was. Take the blame I put on her, and give her compassion. Amen.",
 "I am taking my name off a crime I did not commit.",
 "Workbook 1.6  |  Vol. II Ch. 10 (#2)"),

(16, "Why You Went Back", "Addiction · Motherhood", "Luke 22:31-32",
 "Simon, Simon, behold, Satan demanded to have you, that he might sift you like wheat, but I have prayed for you that your faith may not fail. And when you have turned again, strengthen your brothers.",
 "Peter failed and went back. Jesus had already prayed for him and already named what came after: when you have turned again. Why you went back to the substance, to the person, to the house is not stupidity. It was familiar, it worked, you had no options, you loved them, or you thought it was for the kids. Most people try more than once. Going back is not the end of the story. The turning again is.",
 ["What did I go back to, and what did it give me?", "What stopped me from leaving earlier?", "What do I believe Jesus prayed for me?"],
 "Write, \"I went back because…\" with no excuses and no punishments. Then write, \"And I am turning again.\"",
 "Jesus, You prayed for Peter before he fell. Pray for me now. Strengthen me for the turning. Amen.",
 "I was in a trap built to hold. Leaving late is still leaving.",
 "Workbook 4.1  |  Vol. II Ch. 3 (Contract 5), Ch. 10 (#6)"),

(17, "Missing What Hurt You", "Addiction · Childhood", "Psalm 107:9",
 "For he satisfies the longing soul, and the hungry soul he fills with good things.",
 "You can miss the person who hurt you. You can miss the high. You can even miss the version of home that was chaos, because it was yours. Cruelty and tenderness on an unpredictable schedule bond people harder than steady kindness. It is the same pull as a slot machine. Missing is not evidence you should go back. It is evidence that something in you is still hungry, and God fills the hungry.",
 ["What do I actually miss, the person, or the relief between the harm?", "What hunger is under it?", "What is one safe thing that could feed that hunger today?"],
 "When the missing hits, name it: \"This is hunger, not a sign.\" Then eat, drink water, and call a safe person.",
 "God, I am hungry and I am tired of feeding it with what hurts. Fill the place only You can fill. Amen.",
 "What I feel is real. It is not a reason to go back.",
 "Workbook 4.3  |  Vol. II Ch. 3 (Contract 5)"),

(18, "Memory Gaps and Mothering", "Childhood · Motherhood · Addiction", "Psalm 139:12",
 "even the darkness is not dark to you; the night is bright as the day, for darkness is as light with you.",
 "Many survivors have holes: parts of childhood they cannot remember, or years of their own children's lives lost in a fog of use or numbness. The gaps are not proof you are lying, or that you were not there. They are what a mind does to survive. Do not force memory. A trauma-informed counselor can help you go slowly. God sees the parts you cannot, and the grief of missing them is real and welcome.",
 ["What do I wish I remembered, or wish I could get back?", "What does it feel like to grieve it?", "What do I need to stop demanding of my own memory?"],
 "Gather three things you do remember from your child's life, or your own, and write them down as a small gift.",
 "Lord, the dark is not dark to You. Hold what I cannot hold. Give me grace for the gaps. Amen.",
 "I do not need perfect memory to tell the truth or to be loved.",
 "Workbook 1.4  |  Vol. II Ch. 10 (#19)"),

(19, "The Mother's Moral Injury", "Motherhood · Addiction", "1 Timothy 1:15",
 "The saying is trustworthy and deserving of full acceptance, that Christ Jesus came into the world to save sinners, of whom I am the foremost.",
 "Some of you are not haunted only by what was done to you. You are haunted by what you did while surviving: the nights you were not there, the things you said, the people you brought around your children. That is moral injury, and it is real. It is also not unforgivable. Paul called himself the foremost of sinners and God used him anyway. Forgiveness from God is complete. Repair with people is a separate road, and the next day takes it up.",
 ["What did I do that I cannot reconcile with who I wanted to be?", "Who did it hurt?", "What part of this is guilt I can bring to Jesus, and what part is shame that lies?"],
 "Write it in one line. Then write beneath it, \"Jesus came for people like me.\"",
 "Jesus, You came for sinners, and I am one. Take what I cannot carry, and lead me to repair what I can. Amen.",
 "I did that. It was mine. Jesus paid for it. I stop punishing someone He pardoned.",
 "Workbook 4.4 (Work Page 15)  |  Vol. II Ch. 10 (#3)"),

(20, "Living Amends", "Motherhood · Addiction", "Proverbs 28:13",
 "Whoever conceals his transgressions will not prosper, but he who confesses and forsakes them will obtain mercy.",
 "When you cannot undo the harm, you live differently where the harm lives. With children, amends are mostly shown, not demanded: showing up when you said you would, telling the truth at their level, not asking them to take care of your feelings, and not requiring their forgiveness. A short, age-appropriate acknowledgment can help (I am sorry I wasn't there; it was not your fault; I am getting help). Then let your consistency speak. Where a person is gone or contact is unsafe, serve where that damage lives.",
 ["Who needs repair from me, and what would honest repair look like for them?", "What is the risk of asking for forgiveness too soon?", "What is one reliable thing I can show up for this week?"],
 "Choose one promise you can keep this week, however small, and keep it.",
 "Lord, make me someone who shows up. Where I cannot repair, use me where the damage lives. Amen.",
 "I make amends by becoming someone who does not do that anymore.",
 "Workbook 4.4  |  Vol. II Step 31"),

(21, "Two Realms, One Kitchen Table", "Warfare · Motherhood", "2 Corinthians 4:18",
 "...as we look not to the things that are seen but to the things that are unseen. For the things that are seen are transient, but the things that are unseen are eternal.",
 "Spiritual warfare is not only for conferences. The unseen realm meets us at the kitchen table: in what we believe about ourselves, in the tone we use with children, in the cravings at 4 p.m., in how we treat the one who irritates us most. Scripture treats the unseen opposition as real and limited, and treats ordinary faithfulness as how we stand. You are not imagining the fight, and you do not have to make it dramatic. You have to show up, tell the truth, and keep Jesus near.",
 ["Where do I notice the fight in ordinary moments of my day?", "What has been \"just my personality\" that might be something else?", "How could I meet it with something simple?"],
 "Pick one ordinary moment today (making breakfast, driving, folding laundry) and pray one sentence in it.",
 "Lord, You are at my table. Teach me to see what is going on beneath the noise, and to stand there with You. Amen.",
 "I am not imagining what I have been through. And I am not fighting it alone.",
 "Workbook 2.1  |  Vol. II Ch. 1, 11"),

(22, "Four Categories at 2 a.m.", "Warfare · Motherhood · Addiction", "1 Thessalonians 5:21",
 "but test everything; hold fast what is good.",
 "When something is tormenting you, sort it. What part is body and chemistry? What part is wound? What part is flesh, your untrained appetite, which needs discipline, not deliverance? What part might be spiritual? Now you have four assignments instead of one impossible one. If it is a child who is struggling, begin with doctors, teachers, counselors, and love. Do not label a child demonic. Warfare for a mother mostly looks like sleep, safety, honesty, and prayer.",
 ["What is tormenting me most right now?", "How would I sort it: body, wound, flesh, spirit?", "Who could help me with each part?"],
 "Fill in the four categories on a page for one problem. Do one small thing under each.",
 "God, give me discernment instead of panic. Teach me to fight the right thing the right way. Amen.",
 "Discernment is not doubt. It is how I stop fighting the wrong thing.",
 "Workbook 2.3 (Work Page 6)  |  Vol. II Ch. 10 (#12)"),

(23, "What He Cannot Do", "Warfare · Motherhood", "1 John 4:4",
 "Little children, you are from God and have overcome them, for he who is in you is greater than he who is in the world.",
 "Fear sells. The enemy is a created being, not God's opposite. He is not everywhere, he cannot read your mind (only God knows the heart), he cannot make you do anything, and he cannot snatch you from God's hand. Scripture promises that God keeps those who are His (John 10:28-29; 1 John 5:18). It does not promise that nothing bad will ever happen to your children, and I will not pretend it does. It does tell you that you are not facing it unprotected or alone.",
 ["Where has fear for my children or myself been louder than truth?", "What do I believe about what the enemy can do?", "What is God asking me to trust Him with?"],
 "Write one fear for your children. Hand it to God in one sentence: \"This is Yours.\"",
 "Father, You are greater. I give You the fear I have been carrying like a weapon. Keep what I cannot keep. Amen.",
 "He can build a hallway. He cannot move my feet.",
 "Workbook 2.3  |  Vol. II Ch. 11"),

(24, "Standing, Not Cowering", "Warfare", "Ephesians 6:13",
 "Therefore take up the whole armor of God, that you may be able to withstand in the evil day, and having done all, to stand firm.",
 "Notice the verb. Over and over in Ephesians 6 the posture is stand. Colossians 2:15 says Christ disarmed the rulers and authorities and put them to open shame. Authority is not volume, and it is not a formula. It is standing where Jesus has already won. It lets you rest. It also is never a reason to skip a doctor, a counselor, or a safety plan. Cowering and charging are both ways of forgetting He already won.",
 ["Where have I been cowering?", "Where have I been charging in my own strength?", "What would standing look like in one situation this week?"],
 "Stand up, plant your feet, and say aloud, \"I stand in Christ.\" Hold it for ten seconds.",
 "Jesus, You disarmed what scared me. Help me stand where You already won. Amen.",
 "I am not negotiating with fear. I am standing on what Christ has already won.",
 "Workbook 2.5  |  Vol. II Ch. 1"),

(25, "Submit, Then Resist", "Warfare · Addiction", "James 4:7",
 "Submit yourselves therefore to God. Resist the devil, and he will flee from you.",
 "The order matters. Submit first, then resist. Resisting without submitting is how people get hurt, and it is also exhausting. For anyone in addiction, submission begins with an honest admission that you cannot do this on willpower, and it is not defeat. It is where help begins. Authority is not volume. Jesus answered temptation with a sentence of Scripture (Matthew 4). Loud is for our own fear.",
 ["What in my life have I been trying to handle in my own strength?", "What would submitting to God look like there?", "What is one thing I can resist this week once I am under His care?"],
 "Say aloud, \"I cannot do this alone. Jesus, I am Yours.\" Then do one resisting thing.",
 "God, I give You my will, my plan, and my pride. Under Your care, I will stand against what harms me. Amen.",
 "I get under God before I stand against anything.",
 "Workbook 2.5, 2.6 (Step 1)  |  Vol. II Step 8"),

(26, "What Keeps Getting Fed", "Warfare · Childhood · Addiction", "Ephesians 4:26-27",
 "Be angry and do not sin; do not let the sun go down on your anger, and give no opportunity to the devil.",
 "Some struggles keep getting fed by the same things: unforgiveness, a lie about yourself, anger left to rot, old vows, substances, patterns you inherited. Paul says anger is not the problem. Holding it past sundown gives the enemy room. For mothers, this is the rage at a child that is really old rage at someone else. Naming what feeds it is not shame. It is how you stop feeding it.",
 ["What do I keep feeding, knowingly or not?", "Where does my anger really belong?", "What would starving it look like?"],
 "Name the feeding source in one line. Take one small step to stop feeding it today.",
 "Lord, show me what I keep feeding. Teach me to bring anger to You before it spills on people I love. Amen.",
 "Everything I can name, I can bring to God and begin to change.",
 "Workbook 2.4  |  Vol. II Ch. 3 (Contract 9)"),

(27, "Under Cover", "Warfare", "Psalm 91:1-2",
 "He who dwells in the shelter of the Most High will abide in the shadow of the Almighty. I will say to the LORD, \"My refuge and my fortress, my God, in whom I trust.\"",
 "Before anything else, get under cover. That is what prayer is at its simplest. Say who you belong to. Say what you cannot do alone. Ask Him to cover you, and your children, and the day. This is not a spell, and it does not guarantee a trouble-free life. It is the posture of a child who runs to the one who is bigger. Do this before you try anything bigger.",
 ["Where do I run first when I am afraid?", "What would it mean to run to God first?", "What do I want covered today?"],
 "Pray out loud, in your own words, \"I belong to You. Cover me and mine today.\"",
 "Father, I run to You. You are my refuge. Cover me and the ones I love. I do not go in uncovered. Amen.",
 "I do not go in alone and I do not go in uncovered.",
 "Workbook 2.6 (Step 1)  |  Vol. II Step 8"),

(28, "Forgiving the Woman Who Raised You", "Childhood · Motherhood", "Colossians 3:13",
 "bearing with one another and, if one has a complaint against another, forgiving each other; as the Lord has forgiven you, so you also must forgive.",
 "Forgiveness is not saying it was okay, and it is not reconciliation. It is releasing the right to collect. For many of us the debt is owed by a mother or father, and the pain is tangled with how we now parent. Forgive in pieces if you have to. One thing at a time, out loud. Hand it to God and let Him keep the ledger. You can forgive fully and still keep every boundary.",
 ["Who do I need to forgive, and for what specifically?", "What am I afraid forgiveness would mean?", "What would I keep, even after forgiving?"],
 "Choose one specific thing and say, \"I release this to You, God. I am not available for more harm.\"",
 "Lord, I am tired of being their jailer and their prisoner. I release it to You. Keep me safe. Amen.",
 "I refuse to be their jailer and their prisoner at the same time.",
 "Workbook 2.6 (Step 3)  |  Vol. II Step 10"),

(29, "Forgiven Is Not Back In", "Childhood · Motherhood · Warfare", "Proverbs 22:3",
 "The prudent sees danger and hides himself, but the simple go on and suffer for it.",
 "You can forgive someone and still keep them away from your children. Reconciliation needs two people and real repentance. Where someone has harmed you or could harm a child, safety decides access, not guilt or family pressure. Jesus withdrew often, and Paul named people and told others to avoid them. If there is a custody or contact question, a legal aid office, a domestic violence advocate, or a social worker can help you think it through. This is not unforgiveness. It is wisdom.",
 ["Who have I let back in because I thought forgiving required it?", "What does safety actually require right now?", "Who can help me hold the line?"],
 "Write down one boundary around a person and your children. Tell one safe person.",
 "God, give me wisdom, not just kindness. Help me protect what You have given me to guard. Amen.",
 "I forgive completely. I am not available for more harm.",
 "Workbook 7.2  |  Vol. II Step 25"),

(30, "The Armor, for a Mother's Morning", "Warfare · Motherhood", "Ephesians 6:14-15",
 "Stand therefore, having fastened on the belt of truth, and having put on the breastplate of righteousness, and, as shoes for your feet, having put on the readiness given by the gospel of peace.",
 "Thirty seconds, out loud, before the day puts anything on you. Truth: I will not lie to myself today. Righteousness: I am covered by His, not mine. Peace: I bring it into rooms, I do not take chaos from them. Faith, salvation, the Word, prayer (Ephesians 6:16-18). Notice there is no armor for the back. We are built to stand, not to run. It fits at a counter with a coffee as well as in a prayer closet.",
 ["Which piece of armor do I forget most?", "What is coming at me today that I need to prepare for?", "How could this fit into my actual morning?"],
 "Say it out loud for thirty seconds today, standing, even if kids are awake.",
 "Lord, I put on what You gave me. Keep me upright today, and keep my eyes on You. Amen.",
 "I put it on before the day puts anything on me.",
 "Workbook 2.7  |  Vol. II Appendix (daily armor)"),
]
