# Ninety Days of Standing — days 61–90.

DAYS_3 = [
(61, "HALT at Bedtime", "Addiction · Motherhood", "Psalm 127:2",
 "It is in vain that you rise up early and go late to rest, eating the bread of anxious toil; for he gives to his beloved sleep.",
 "Hungry, Angry, Lonely, Tired. Many relapses are several of those stacked, and they are rarely only about the substance. Mothers meet all four by 9 p.m. Some of what feels like a craving is blood sugar. Some of what feels like despair is sleep. Run the check three times a day: what is loudest, and what can I do about it in the next hour? Protecting your sleep and food is not selfish. It is part of how you stand.",
 ["Which of the four is loudest right now?", "What can I do about it in the next hour?", "Who could cover one thing, like dinner or bedtime, so I can rest?"],
 "Eat something real and drink water. If you can, set a bedtime and put the phone out of reach.",
 "Lord, You give Your beloved sleep. Help me rest without guilt. Amen.",
 "I will feed, rest, call, and calm before I decide anything.",
 "Workbook Part V Step 4  |  Vol. II Ch. 17"),

(62, "The Craving Wave", "Addiction", "1 Corinthians 10:13",
 "No temptation has overtaken you that is not common to man. God is faithful, and he will not let you be tempted beyond your ability, but with the temptation he will also provide the way of escape, that you may be able to endure it.",
 "A craving often peaks and fades within fifteen to thirty minutes, even when it does not feel that way. Say it aloud: I am having a craving. It will peak and pass. Set a timer. Change your body: cold water, twenty pushups, walk outside. Change your location. Call, do not text. Eat and drink. Pray short. Play the tape forward. You only have to outlast a wave. If kids are present, tell them in a simple way that you need a minute, and go to a safe adult or call someone.",
 ["Who are the three numbers I will call, memorized?", "What changes my body fastest?", "What do I do if the kids are awake?"],
 "Write your three numbers on a card and tape one copy where you will see it.",
 "Jesus, I do not have to win this hour, only this wave. Give me a way out and the sense to take it. Amen.",
 "I only have to outlast a wave. It always breaks.",
 "Workbook Part V Step 7  |  Vol. II Step 28"),

(63, "Play the Tape Forward, With Her Face", "Addiction · Motherhood", "Proverbs 14:12",
 "There is a way that seems right to a man, but its end is the way to death.",
 "Not the first hour. The forty-eighth. The phone call you would have to make. The face you would have to look at. For a mother, the face is often a child's. Write it now, while you are clear, because you will not be able to write it in the moment. This is not a scare tactic. It is a way of giving your future self the evidence she will need. Include who is with the kids if you use, and where the naloxone is if opioids are in your history.",
 ["If I use or go back today, what happens within forty-eight hours?", "Whose face do I see?", "What do I most want to protect?"],
 "Write your tape on a card. Keep it where you keep your keys.",
 "God, I want to keep what You have given me. Let me remember it when I cannot think. Amen.",
 "I decide this now, while I can still think.",
 "Workbook Part V Step 7  |  Vol. II Step 29"),

(64, "Replace the Function", "Addiction · Motherhood", "Isaiah 55:2",
 "Why do you spend your money for that which is not bread, and your labor for that which does not satisfy? Listen diligently to me, and eat what is good, and delight yourselves in rich food.",
 "You cannot leave a vacancy. For every job the substance did, find a legitimate replacement. It numbed pain, so find a place to put pain: therapy, a journal, a friend. It gave energy, so find food, movement, sleep. It gave belonging, so find a meeting or a group. It quieted your head, so find music, a walk, or silence. For mothers, add: it gave me a break, so find a real break, a trade-off with a friend, or a respite program. God invites us to what satisfies.",
 ["What jobs did it do for me?", "What legitimate replacement could do each job?", "When will I do it?"],
 "Complete the job and replacement list from Day 39. Choose one to start today.",
 "Lord, I do not want to leave an empty room. Fill it with what is good. Amen.",
 "I am not removing something. I am replacing it.",
 "Workbook Part V Step 5  |  Vol. II Step 26"),

(65, "Fill the House", "Warfare · Motherhood", "Romans 12:21",
 "Do not be overcome by evil, but overcome evil with good.",
 "Jesus tells a story of a swept house left empty (Luke 11:24-26), and the last state was worse than the first. Whatever your view of the spiritual side, the practical truth stands: when something leaves your life, something must take its place. Where fear lived, put love. Where shame lived, put belonging. Where craving lived, put satisfaction. For a household, this can mean worship music in the kitchen, a bedtime routine, a regular meal, a table prayer. Overcome with good, in small and visible ways.",
 ["What am I emptying that needs filling?", "What small good thing could fill it?", "What would my household's \"filled\" feel like?"],
 "Choose one new, simple good habit for your home this week (a song, a prayer, a meal). Start tonight.",
 "Holy Spirit, fill every room that has been emptied. Leave nothing vacant. Amen.",
 "Holy Spirit, occupy every room. Leave nothing empty.",
 "Workbook 2.6 (Step 8)  |  Vol. II Step 18"),

(66, "Architecture for a Chaotic House", "Motherhood · Addiction", "1 Corinthians 14:40",
 "But all things should be done decently and in order.",
 "Freedom is architecture. Same wake hour. Sunlight in the first hour. Prayer out loud. Protein and water before caffeine. Movement. A HALT check. A meeting or a call. Same bedtime, phone out of the room. If you are a mother of little ones, you are building this around naps, school drop-off, and chaos, and that is fine. Pick the three that matter most and let the others wait. Sleep affects almost everything else.",
 ["Which piece of daily structure am I missing most?", "What is the smallest version I could try?", "What would I need to ask someone for?"],
 "Choose three anchors for your day and write them where you can see them.",
 "God, You are a God of order. Help me build a day I can stand on. Amen.",
 "Freedom is architecture. I am building the walls.",
 "Workbook Part V Step 6  |  Vol. II Step 23"),

(67, "Boundaries at the Front Door", "Motherhood · Warfare", "Proverbs 4:23",
 "Keep your heart with all vigilance, for from it flow the springs of life.",
 "Boundaries that exist only in your heart are wishes. Block the number. Change the lock. Tell the relative who relays messages to stop. Decide in advance what you will do when they reach out, because they usually do right when you get peaceful. For mothers, this includes who can be near your children, who can pick them up, and what phones and screens are in the house. A boundary is a property line, not a punishment, and you do not have to explain it forty times.",
 ["What boundary do I need to set?", "How will I enforce it this week?", "What will I do when they push back?"],
 "Set one real-world boundary today. Write the exact sentence you will use.",
 "Lord, give me a firm yes and a firm no, and keep my heart open to those who are safe. Amen.",
 "I am not explaining it forty times. It is a property line.",
 "Workbook 7.5 (Step 6)  |  Vol. II Step 25"),

(68, "When You Fall in Front of Your Kids", "Addiction · Motherhood", "Micah 7:8",
 "Rejoice not over me, O my enemy; when I fall, I shall rise; when I sit in darkness, the LORD will be a light to me.",
 "Having a plan is not permission. Not having one gives the fall a runway. Stop at the first one. The fall is the first act, the ruin is the decision afterward. Tell someone within the hour. Make sure your children are safe and supervised. Have naloxone in the house if opioids are in your history, and tell a person who can help. Do not throw away ninety days over one day. Then find the link you missed and write it down. Kids can handle an honest, age-appropriate truth better than a cover story.",
 ["What is my written plan for the day I fall?", "Who will care for my children if I cannot?", "What will I say to them, and when?"],
 "Write the plan and share it with one person. Keep a copy on the fridge or in your phone.",
 "Lord, when I fall, You are my light. Give me someone to call, and keep my children safe. Amen.",
 "The identity is in the rising, not in never falling.",
 "Workbook Part V Step 8  |  Vol. II Step 29"),

(69, "Where Was He When She Was Small", "Childhood", "Genesis 16:13",
 "So she called the name of the LORD who spoke to her, \"You are a God of seeing,\" for she said, \"Truly here I have seen him who looks after me.\"",
 "Hagar, a mistreated servant who had run away, is the first person in Scripture to give God a name, and it is the God who sees. He was near the brokenhearted in the room, not outside it, not arriving later. That is harder than absence, because it means He saw. It is also better than absence, because it means you were never alone, even when you felt completely alone. I do not know why He did not stop it. I know He saw, and I know He kept the record of every tear.",
 ["Where do I most need to know He was?", "What do I feel when I imagine Him in that room?", "What do I want to say to Him?"],
 "Say aloud, \"You saw me.\" Sit with whatever comes.",
 "God of seeing, I did not know You were there. Show me, gently, how You were. Amen.",
 "He was in the room. I was never in there by myself.",
 "Vol. II Ch. 22  |  Workbook 1.5"),

(70, "Why Didn't He Stop It, Asked by a Mother", "Motherhood · Childhood", "Isaiah 49:15",
 "Can a woman forget her nursing child, that she should have no compassion on the son of her womb? Even these may forget, yet I will not forget you.",
 "Whoever you are asking for, yourself or your child, the question is the same. God made a world with real agency, because love that cannot be refused is not love. That means people can choose evil, and He does not routinely override the will He gave. He did not cause it, want it, or approve it. He hated it. That is an explanation, not a comfort, and I will not pretend it is the same. But notice how He answers in this verse: with a mother's love as His comparison, and a promise that He does not forget.",
 ["What do I most need to ask Him?", "What do I do with the part that has no answer?", "How does it feel to hear Him compare Himself to a mother?"],
 "Write the question you have never asked, and leave it open.",
 "Father, I do not understand. I trust Your character where I cannot trace Your hand. Stay with me. Amen.",
 "I trust His character where I cannot trace His hand.",
 "Vol. II Ch. 23  |  Workbook 3.1"),

(71, "Not Punishment", "Motherhood · Childhood", "John 9:3",
 "Jesus answered, \"It was not that this man sinned, or his parents, but that the works of God might be displayed in him.\"",
 "The disciples asked whose sin caused a man's blindness, and Jesus rejected the whole premise. If your child struggles with health, learning, mental health, or addiction, it is not the sentence for your past. If your own suffering feels like punishment, it is not. Jesus paid the bill and God does not double-bill. Grief is not proof of a curse, and hardship is not a verdict.",
 ["What have I secretly believed I was being punished for?", "Where have I connected my child's pain to my past?", "What would it mean to let that go?"],
 "Write the sentence you believe, then cross it out and write, \"This is not punishment.\"",
 "Jesus, You refused the lie that suffering is always a sentence. Take mine and my children's out of that frame. Amen.",
 "He is not punishing me. There is no condemnation.",
 "Vol. II Ch. 20  |  Workbook 3.3"),

(72, "Angry at God", "Warfare · Childhood · Motherhood", "Psalm 13:1-2",
 "How long, O LORD? Will you forget me forever? How long will you hide your face from me? How long must I take counsel in my soul and have sorrow in my heart all the day? How long shall my enemy be exalted over me?",
 "Scripture preserves complaints. Jesus quoted a psalm of abandonment from the cross. Job accused God and God said Job had spoken rightly of Him. Lamentations is grief laid out before God, and God kept it in the canon. He can handle your rage. What He cannot work with is your distance. Say it to Him directly. Mothers who have buried a child, lost custody, or watched a child suffer have every right to this psalm.",
 ["What have I never said to God directly?", "What am I afraid will happen if I do?", "What would it look like to say it today?"],
 "Write or say it to God, unedited, for two minutes.",
 "God, here it is, all of it. I am bringing it to You instead of holding it against You. Amen.",
 "I bring it to Him instead of holding it against Him.",
 "Vol. II Ch. 27  |  Workbook 7.6"),

(73, "Taking Your Case Out of Court", "Warfare · Childhood", "Romans 12:19",
 "Beloved, never avenge yourselves, but leave it to the wrath of God, for it is written, \"Vengeance is mine, I will repay, says the Lord.\"",
 "As long as you hold a verdict against God, you cannot receive from Him. You do not have to stop having questions. You have to stop having a verdict. And handing over your case against the people who hurt you is not letting them off. It is God taking a weight that was killing you. He is the judge, and He sees everything, including what never reached a human court. Some people never face anything on earth. That is not the end of the story.",
 ["What verdict am I carrying against God?", "What case am I carrying against someone else?", "What would it feel like to hand each to Him?"],
 "Write \"I withdraw the verdict\" beside the one you are ready to put down.",
 "God, I keep my questions open and I withdraw my verdict. The case is Yours. Amen.",
 "I keep the questions open. I withdraw the verdict.",
 "Vol. II Ch. 26  |  Workbook 2.6 (Step 3)"),

(74, "The Quiet Stretch of Faith", "Warfare · Motherhood", "Lamentations 3:26",
 "It is good that one should wait quietly for the salvation of the LORD.",
 "Elijah was suicidal and looked for God in wind, earthquake, and fire, and God came in a thin silence, after He fed him and let him sleep twice. Food, sleep, then the whisper. Sometimes the silence is not rejection. Sometimes you are exhausted and He is feeding you first. A mother in a dry season may have no energy for a long quiet time, and that is okay. A few honest sentences are prayer.",
 ["Have I been asking for a whisper when I need food and sleep?", "What would feed me today?", "What is one small way to wait?"],
 "Eat something and rest for ten minutes, even if just sitting. Then pray one sentence.",
 "Lord, I am tired. Feed me, and then speak. Amen.",
 "Silence is documented. It is not rejection.",
 "Vol. II Ch. 27  |  Workbook 7.6"),

(75, "Silence With the Baby Monitor On", "Motherhood · Warfare", "Psalm 131:2",
 "But I have calmed and quieted my soul, like a weaned child with its mother; like a weaned child is my soul within me.",
 "Noise was safety. If it was quiet, you could hear them coming, and you had to feel it. So silence may feel like danger before it feels like peace. Start with two minutes. Eyes open if closed feels unsafe. When your mind runs, say later and come back. The coming back is the prayer. In a house with children, quiet may be five minutes in a bathroom, in the car, or while the baby sleeps. Take it. It counts.",
 ["How long did I sit, and what came up?", "What does silence feel like in my body?", "Where is a safe place I can practice?"],
 "Sit two minutes today. Feet on the floor. Say once, \"Jesus, I am here.\" Then nothing.",
 "Father, I do not have to say anything. I am not leaving. Quiet my soul like a child with her mother. Amen.",
 "I am here. He does not have to say anything. I am not leaving.",
 "Workbook 7.6  |  Vol. II Ch. 27"),

(76, "All Things, Honestly", "Motherhood · Warfare", "Romans 8:28",
 "And we know that for those who love God all things work together for good, for those who are called according to his purpose.",
 "It does not say all things are good. It says God works in all things toward good, and the next verse defines that good as being made like Christ. It is not a promise that your story will have a satisfying plot, and it is not meant to be said to someone in fresh grief. It is a promise that nothing in your story, including what happened in your childhood, your addiction, or your mothering, is unusable in His hands. It was not good. It will not be wasted. Those are different things.",
 ["What do I need Him to use rather than explain?", "What have I been tempted to call good that was not?", "What do I hope He will redeem?"],
 "Write one thing that was not good, and one thing you are asking Him not to waste.",
 "God, I will not call it good, but I ask You not to waste it. Use it. Amen.",
 "It was not good. It will not be wasted. Those are different.",
 "Vol. II Ch. 25  |  Workbook 3.5"),

(77, "You Were Not Their Savior", "Motherhood · Addiction", "Psalm 147:3",
 "He heals the brokenhearted and binds up their wounds.",
 "If you lost someone to addiction, a sister, a child, a friend, you may have been carrying the idea that you should have saved them. You were not their savior. You were their sister, their mother, their friend. You lost them because addiction is lethal, because they were sick, and because the world they were in was built to fail people like them. None of those were yours to control. This page is for Brandi, or whoever you are carrying. Grief is allowed here.",
 ["What did I do for them?", "What do I keep telling myself I should have done?", "Was it truly in my power at that time?"],
 "Write one thing you did that was love. Let that be enough for today.",
 "God, I loved them and I was never their God. Hold them, and hold me. Amen.",
 "I loved them. I was never their God. That was never my job.",
 "Workbook 7.4 (Work Page 17)  |  Vol. II Ch. 38, 39"),

(78, "Who Was Responsible", "Motherhood · Addiction", "Psalm 9:9",
 "The LORD is a stronghold for the oppressed, a stronghold in times of trouble.",
 "List what actually contributed: their choices, the people who hurt them, the ones who sold to them, the systems that turned them away, the disease itself, the patterns they were born into, and your choices. Then count how many lines have your name on them, and how many do not. The point is not to avoid responsibility. It is to put it where it belongs, so grief can be grief and not an endless trial.",
 ["Who or what was responsible for each part?", "Which lines have my name, truthfully?", "What age and condition was I in then?"],
 "Fill in a list of responsible parties. Stop when it is done.",
 "Lord, You are a stronghold for the oppressed. Help me put the weight where it belongs. Amen.",
 "I judge my past self with resources she did not have. I stop.",
 "Vol. II Ch. 39  |  Workbook 7.4"),

(79, "Hope Without Certainty", "Warfare · Motherhood", "Psalm 139:8",
 "If I ascend to heaven, you are there! If I make my bed in Sheol, you are there!",
 "I am not God, and I will not pretend to know where she is. But addiction is not the unforgivable sin, God judges the heart and not the manner of death (1 Samuel 16:7), and Romans 8:38-39 lists death first among the things that cannot separate us from His love. A cry does not have to be eloquent: the thief on the cross got one sentence (Luke 23:42-43). You can hope, legitimately, without lying to yourself. Hope is not certainty, and you do not need certainty to stop tormenting yourself.",
 ["Can I hope without needing to know?", "What does it feel like to place them in God's hands?", "What would help me leave them there?"],
 "Say aloud, \"I do not know, and I hope.\" Sit with it.",
 "God, You are there, even in Sheol. I put them in Your hands. I do not know everything, and I hope. Amen.",
 "I am putting them in the hands of someone kinder than the people who scared me.",
 "Vol. II Ch. 40  |  Workbook 7.4"),

(80, "Not a Debt", "Motherhood · Addiction", "Romans 8:15",
 "For you did not receive the spirit of slavery to fall back into fear, but you have received the Spirit of adoption as sons, by whom we cry, \"Abba! Father!\"",
 "Their death did not buy your life, and there was no exchange. If you build your whole recovery or your whole work as restitution for being the one who lived, you will never be able to stop, and it will never be enough, because guilt does not close accounts. Build it because it is right, and because you love them. Their name goes on it as a dedication, not a debt. A mother who survived does not owe her life as payment, and neither does a sister.",
 ["Am I building out of love or out of guilt?", "How can I tell the difference?", "What would change if it were a dedication, not a debt?"],
 "Write the sentence, \"My life is not a payment.\" Say it aloud once.",
 "Father, I did not receive a spirit of slavery. Free me from owing. Let me carry their name in love. Amen.",
 "Their name goes on the work as a dedication, not a debt.",
 "Vol. II Ch. 40, 41  |  Workbook 7.4"),

(81, "The Letter", "Childhood · Motherhood · Addiction", "John 11:35",
 "Jesus wept.",
 "Jesus wept at a grave He was about to open. Grief is not weak faith. Write the one you lost everything: the love, the rage, the why did you not call me, the I am sorry, the last conversation you wish you had, and what you have never told anyone. If you are writing to Brandi, write to Brandi. Then write the indictment you have been running against yourself, and, if you can do it safely, burn it outside and watch it go.",
 ["What I have never said to them:", "What case have I been prosecuting against myself?", "What is my verdict on each count?"],
 "Write the letter. Then, if you wish and it is safe, burn the second page.",
 "Jesus, You wept. Weep with me. Let me say it all, and let it go. Amen.",
 "I am not letting them go. I am putting them down in better hands.",
 "Vol. II Ch. 42  |  Workbook 7.4"),

(82, "Grief Is Not a Relapse", "Addiction · Motherhood", "Matthew 5:4",
 "Blessed are those who mourn, for they shall be comforted.",
 "Grief that is not given a place will take one, usually as rage or shutdown, or a craving. Know your dates: birthdays, anniversaries, the day you got the call. Plan for them instead of being ambushed. Have one person to call on those days. And stop calling it a setback when it is love with nowhere to put itself. For a mother, this includes the grief of missed milestones, a child who is gone or estranged, or the childhood you never had.",
 ["What are my hard dates?", "Who will I call?", "What gentle ritual could I make for them?"],
 "Put the next hard date on your calendar with a name and a plan.",
 "Lord, comfort me as You promised. Let me grieve without breaking. Amen.",
 "I am allowed to grieve, and I am allowed to have a good day.",
 "Vol. II Step 30  |  Workbook 7.4"),

(83, "When the Living Child Is Out of Reach", "Motherhood", "Jeremiah 31:16-17",
 "Thus says the LORD: \"Keep your voice from weeping, and your eyes from tears, for there is a reward for your work, declares the LORD, and they shall come back from the land of the enemy. There is hope for your future, declares the LORD, and your children shall come back to their own country.\"",
 "Some of you are mothers whose children are removed, estranged, grown and angry, or lost to addiction. You cannot make them come back, and you cannot force forgiveness. What you can do is stay safe, stay consistent, keep an open door and a clear boundary, send simple messages that ask nothing, and trust God with what you cannot reach. This verse is an ancient promise to a nation, and many mothers have held it. It is hope, not a guarantee about any one person's choices. Luke 15:20 shows a father who ran when the son was still far off.",
 ["Who am I waiting for?", "What can I do that is consistent and safe?", "What do I need to hand to God?"],
 "Write a short, non-demanding note you may or may not send: \"I love you. I am here. No pressure.\"",
 "Father, You see my child. Go where I cannot go. Keep the door open in me. Amen.",
 "I keep the door open without losing myself.",
 "Workbook 7.2  |  Vol. II Ch. 37"),

(84, "The Release", "Warfare · Motherhood", "Psalm 55:22",
 "Cast your burden on the LORD, and he will sustain you; he will never permit the righteous to be moved.",
 "Say it: I release ___ into the hands of God. I am not their savior, judge, jailer, or payment. What was good, I keep. What was mine, I take back. What was theirs, I return. I forgive them, and I am not available for more harm. Then replace the space on purpose, because holes get filled by whatever is nearest. Put something good in it: a person, a practice, a purpose.",
 ["Who am I releasing?", "What am I keeping, and what am I returning?", "What will I put in the space?"],
 "Write the release by name, and read it aloud. Then do one small good thing in the space.",
 "God, I release them into Your hands. Sustain me. Amen.",
 "Out of my hands, into His. His are better than mine ever were.",
 "Workbook 7.5 (Work Page 18)  |  Vol. II Step 30"),

(85, "Known Before You Were Formed", "Childhood · Motherhood", "Psalm 139:13-14",
 "For you formed my inward parts; you knitted me together in my mother's womb. I praise you, for I am fearfully and wonderfully made. Wonderful are your works; my soul knows it very well.",
 "God knew you before you were formed, and what was done to you never canceled what He had in mind for you. The same is true of every child. A mother does not manufacture her child's worth, and neither does a mother's failure erase it. I cannot tell you the harm was aimed at your calling. I do not know that. But I can tell you the place that hurt most is often the place you understand best, and that can become a place you help from.",
 ["What was hurt earliest, and what did it try to take?", "What do I see when I look at my child, or the child I was, as known and wanted by God?", "What does it change?"],
 "Look at a photo of yourself as a child. Say, \"Known and wanted by God.\"",
 "Father, You knitted me and every child together. Let that be the final word over us. Amen.",
 "God's knowing came first. The harm does not get the final word.",
 "Workbook 3.1  |  Vol. II Ch. 28"),

(86, "The Wound as a Door", "Warfare · Motherhood", "2 Corinthians 1:3-4",
 "Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort, who comforts us in all our affliction, so that we may be able to comfort those who are in any affliction, with the comfort with which we ourselves are comforted by God.",
 "Joseph was starved of family and put in charge of feeding families. Moses was drawn out of the water and sent to draw a nation out. Often, the fruit comes in the shape of the wound. Not always, not automatically, and never as a reason to call the wound good. Look at yours as a map, not a verdict. The so that is the whole point: you were not comforted to feel better only. You were comforted so you would know the road.",
 ["Where do my wound and my compassion overlap?", "Who might need exactly what I know?", "What is one small way I could offer it?"],
 "Complete the sentence: \"I am the one who ___ for the people who ___.\"",
 "God of all comfort, comfort me, and let me comfort someone else with what You gave me. Amen.",
 "My wound does not have to stay a wound. It can become a door.",
 "Workbook 3.5  |  Vol. II Ch. 33"),

(87, "Sent, Not Special", "Warfare · Motherhood", "John 15:16",
 "You did not choose me, but I chose you and appointed you that you should go and bear fruit and that your fruit should abide, so that whatever you ask the Father in my name, he may give it to you.",
 "Chosen is not a rank. It is an assignment with a destination. Scripture uses the language of being chosen of every believer, not only the dramatic ones. Many people in Scripture were marked early, isolated, delayed, misunderstood, and broken in a specific place before they were used. The cost is real: lost people, delay that looks like denial, being misunderstood by good people. It does not mean God likes you more. For a mother, your assignment starts at the table you are sitting at.",
 ["What has this already cost me?", "What am I still unwilling to pay?", "What is the assignment right in front of me?"],
 "Name the assignment closest to you today: a child, a friend, a task. Do one small thing for it.",
 "Jesus, You chose me and sent me. Keep me humble and faithful. Amen.",
 "Chosen does not mean liked more. It means sent.",
 "Workbook 3.1–3.4  |  Vol. II Ch. 28, 29"),

(88, "Two Roads, One Small Step", "Motherhood · Addiction", "Deuteronomy 30:19",
 "I call heaven and earth to witness against you today, that I have set before you life and death, blessing and curse. Therefore choose life, that you and your offspring may live,",
 "One possible future is the woman who knew what she was for, told people about it, and never started, while the pattern passed on. Another is the same woman, with the agreements she made in pain released, the pattern interrupted, five people who truly know her, and someone helped because of what she built. Neither is guaranteed. Choices are what you have, and you get to make a small one today. If this page pulls you down, close it and call someone.",
 ["If this week repeats 260 times, where am I in five years?", "Who else is affected by my choices?", "What is the one small step I can take today?"],
 "Take the small step you wrote. Then tell one person.",
 "God, I choose life, for me and for those who come after me. Start small with me today. Amen.",
 "I am going to do it, scared and imperfect and on a date.",
 "Vol. II Ch. 43–45  |  Workbook 3.5"),

(89, "Steward, Not Survivor", "Motherhood · Warfare", "2 Timothy 1:5",
 "I am reminded of your sincere faith, a faith that dwelt first in your grandmother Lois and your mother Eunice and now, I am sure, dwells in you as well.",
 "Victim: this happened to me. Survivor: and I am still here. Steward: and now it belongs to God and it is for somebody else. Paul remembered a line of faith that passed through women. Whatever your line passed on, you can begin a line of faith and honesty now. Teach your children the way you walk: simply, talking of it when you sit, walk, lie down, and rise (Deuteronomy 6:6-7). You do not need to be finished to steward what you have learned.",
 ["What have I learned that is worth passing on?", "Who could receive it this week?", "What does passing it on look like at my table?"],
 "Share one honest, age-appropriate truth with a child or friend this week.",
 "Lord, make me a steward of what You have taught me. Let what I pass on be good. Amen.",
 "I know the road because I was on it. That is the qualification.",
 "Workbook 3.5  |  Vol. II Step 32"),

(90, "The Commission", "Warfare · Motherhood · Addiction · Childhood", "Nehemiah 4:14",
 "...Do not be afraid of them. Remember the Lord, who is great and awesome, and fight for your brothers, your sons, your daughters, your wives, and your homes.",
 "Nehemiah rebuilt a wall with one hand on the work and the other on the weapon. That is the picture: build and stand at the same time. Revelation 12:11 says they conquered by the blood of the Lamb and the word of their testimony, and your testimony is whatever is true, told at your own pace to safe people. Read the whole page aloud, standing. Then set the next date and run it again, because you can only see the next layer from ground you already took. You are not finished. You are on your way.",
 ["What is different about me than on Day 1?", "What is the next layer I can see now?", "Who will walk with me into it?"],
 "Sign it, date it, and tell one person. Then pick your next date.",
 "Father, thank You for ninety days of honesty. Keep me standing, keep me building, and keep me Yours. In Jesus' name. Amen.",
 "I am the woman God chose to stand and to build. Not someday. Today. The line stops here.",
 "Workbook Closing  |  Vol. II Ch. 51"),
]
