# Ninety Days of Standing — days 31–60.

DAYS_2 = [
(31, "Agreements Made in Pain", "Warfare · Childhood", "Colossians 2:14",
 "by canceling the record of debt that stood against us with its legal demands. This he set aside, nailing it to the cross.",
 "Scripture uses the language of debts and records, and says Christ canceled the record that stood against us. This book uses a courtroom picture for the vows, beliefs, and agreements people make in pain: not as a formula, but as a way to see that what you agreed to as a frightened child does not have to keep running your adult life. Christians hold different views on how literally to take the picture. What is clear is that Jesus came to set captives free, and you are allowed to look honestly at what you have been living by.",
 ["What do I suspect I agreed to when I was small or hurting?", "How has it been running my life, my choices, my parenting?", "What is it like to think it does not get the final word?"],
 "Write one agreement you suspect you made, in the words you think you would have used.",
 "Jesus, You carried the record that stood against me. Show me what I agreed to in pain, and show me what You say instead. Amen.",
 "What I agreed to in pain does not get the final word. Christ does.",
 "Workbook 2.4  |  Vol. II Ch. 1, 2"),

(32, "The Vow Behind the Door", "Childhood", "Matthew 5:37",
 "Let what you say be simply 'Yes' or 'No'; anything more than this comes from evil.",
 "Somewhere around eight or nine, a lot of us made a rule to survive. I will never need anyone. I will never cry again. I will never be like my mother. It worked then. It may be running your adult life now, and it can be the reason you cannot let anyone hold you. Even a vow made to be the opposite of someone can bind you to them, because you are still living in reaction. Jesus told us to stop swearing oaths. Not because He is harsh, but because He knows vows made in fear are heavy.",
 ["What rule did I make to stay alive?", "How old was I, and what was happening?", "What is it costing me now, especially with the people I love?"],
 "Write the vow in the exact words you remember. Under it, write what it protected you from.",
 "God, a child made that promise because she had to. Thank You that she survived. Show me what it is costing now. Amen.",
 "It kept me alive. It does not get to run me.",
 "Workbook 2.4  |  Vol. II Ch. 3 (Contract 1), Ch. 4"),

(33, "Releasing a Child's Promise", "Childhood · Motherhood", "Mark 10:14",
 "...Let the children come to me; do not hinder them, for to such belongs the kingdom of God.",
 "Jesus welcomed children and did not make them earn it. When you find the vow, speak to the child who made it, not to scold her but to release her. You can say: I see you. You made that promise because you had to, and it worked. I am the adult now. You do not have to hold the door anymore. Then, in Jesus' name, release the vow and replace it with something true: I can let safe people in. I can feel and still be okay. I can want things. A mother who learns this teaches her children it, too.",
 ["What would I say to the child who made the vow?", "What new, true sentence do I want to live by?", "Who could witness me saying it out loud?"],
 "Say the release aloud, in your own words, and then say your new sentence three times.",
 "Jesus, You welcomed children. Welcome her. Come and bring her home. I take over from here, with You. Amen.",
 "I break the old rule and I write a new one with God.",
 "Vol. II Ch. 4 (inner-vow work)  |  Workbook 2.6 (Step 5)"),

(34, "Words You Said Over Yourself and Over Them", "Motherhood · Childhood", "Ephesians 4:29",
 "Let no corrupting talk come out of your mouths, but only such as is good for building up, as fits the occasion, that it may give grace to those who hear.",
 "Words matter. Proverbs 18:21 says life and death are in the power of the tongue. Many of us can still hear what was said over us: you will never amount to anything, you are just like your father. And many of us have said things to our own children in the worst hour that we would give anything to take back. You cannot unsay them, but you can repair them. Apologize plainly. Say something truer. Then keep saying it. Words can wound, and words can bless.",
 ["What was said over me that I still hear?", "What have I said to my kids, or someone I love, that I wish I could unsay?", "What truer thing can I say, and to whom?"],
 "Speak one blessing today to a child, or to the child you were. Make it specific.",
 "Lord, heal what was said over me. Forgive what I said. Teach me to speak life where there was death. Amen.",
 "I take back every word I spoke in pain. It does not get to run my life.",
 "Vol. II Ch. 6  |  Workbook 2.6 (Step 5)"),

(35, "The Shame Covenant", "Warfare · Motherhood", "Psalm 34:5",
 "Those who look to him are radiant, and their faces shall never be ashamed.",
 "Shame is not the same as guilt. Guilt says I did something wrong. Shame says I am something wrong. Shame hides, and the hiding feeds it. A mother's shame is especially loud, because the culture around us has a thousand rules for a good mother and she has broken them all in her own mind. Safe light is what shame cannot stand. That means looking toward Him, not at your reflection in other people's faces.",
 ["What do I feel most ashamed of as a woman or mother?", "Who taught me this shame?", "What does it look like to look toward Jesus instead of toward their opinion?"],
 "Tell one true, shame-heavy thing to your safe person. Watch what they do. Notice that you are still here.",
 "Jesus, I look to You. Lift the shame I have worn like a coat. Let my face be uncovered. Amen.",
 "I am not the worst thing that happened to me, and I am not the worst thing I did.",
 "Vol. II Ch. 3 (Contract 14)  |  Workbook 1.6"),

(36, "The Silence Contract", "Childhood · Motherhood · Warfare", "Psalm 32:3",
 "For when I kept silent, my bones wasted away through my groaning all day long.",
 "Somebody told you not to tell, and you kept it, sometimes for decades, sometimes to protect people who never protected you. Families can protect secrets over children. Telling should be done with support and never in a way that puts you in danger. If a child is at risk right now, protecting that child comes before the family secret: call the Childhelp National Child Abuse Hotline at 1-800-422-4453, or 911 in an emergency. Your story matters. You are not the keeper of what was done to you.",
 ["What does my family never say out loud?", "What has the silence cost me, and who else?", "What would telling safely look like?"],
 "Write down the secret for yourself only, then decide who, if anyone, should hear it, and when.",
 "Father, You see what was hidden. Give me courage and wisdom to speak when it is time and safe. Protect every child involved. Amen.",
 "I am not the keeper of what was done to me.",
 "Vol. II Ch. 3 (Contract 19)  |  Workbook 6.3"),

(37, "Soul Ties, Plainly", "Warfare · Addiction · Motherhood", "1 Corinthians 6:17",
 "But he who is joined to the Lord becomes one spirit with him.",
 "\"Soul tie\" is not a phrase found in Scripture. It is a name many believers use for a real experience: someone you barely knew, or someone who harmed you, still has a hold on your thoughts. Scripture does say sexual union joins two people in a real way (1 Corinthians 6:16). What was taken from you was a wrong done to you, not a sin you committed. And for mothers there is a layer: the father of your child, or the person you use with, may still be in your life. Being joined to the Lord is the tie that holds.",
 ["Who still has a hold on my mind or body?", "Is this person tied to my children, my housing, my money, or my recovery?", "What would a healthier connection to them look like, if any?"],
 "List names, or write \"the one whose name I do not know.\" Do not write the stories.",
 "Lord, You are the one I want to be joined to. Loosen what is not of You, and show me what safe connection looks like. Amen.",
 "What God did not join, I do not keep.",
 "Vol. II Ch. 5  |  Workbook 2.4"),

(38, "Releasing the Hold", "Warfare · Motherhood", "Philippians 3:13-14",
 "Brothers, I do not consider that I have made it my own. But one thing I do: forgetting what lies behind and straining forward to what lies ahead, I press on toward the goal for the prize of the upward call of God in Christ Jesus.",
 "You can release your hold on a person and ask God to loosen their hold on you. Hand back what is theirs: the shame, the blame, the voice in your head, their version of you. Take back what is yours: your body, your mind, your peace, your future. If you share children with this person, the release is internal and the practical is separate: a clear parenting plan, communication in writing, and an advocate or attorney if safety is a concern. Pressing forward is not pretending. It is a direction.",
 ["What am I handing back today?", "What am I taking back?", "If there is a shared child, what practical structure would protect them and me?"],
 "Pray the release in your own words, by name. Then take one practical step (a message, a document, a call).",
 "Jesus, I release my hold, and I ask You to loosen theirs. I hand back what was never mine. Amen.",
 "I take back what was mine and hand back what was never mine.",
 "Vol. II Ch. 5, Step 15  |  Workbook 2.6 (Step 6)"),

(39, "The Cistern and the Bottle", "Addiction · Childhood", "Jeremiah 2:13",
 "for my people have committed two evils: they have forsaken me, the fountain of living waters, and hewed out cisterns for themselves, broken cisterns that can hold no water.",
 "Every addiction promised something real: peace, escape, belonging, courage, rest. Those are good things, and only God gives them without charging interest. The cistern is not the sin. Digging your own is. This is not an insult. It is the most honest question there is: what was it giving me that I could not get anywhere else? If you can answer that, you can find a legitimate source for the need. You cannot rebuke a habit you keep feeding. Some things are crucified, not cast out.",
 ["What did it give me that I could not get anywhere else?", "What did it let me stop feeling?", "What good thing was I really thirsty for?"],
 "Write the job it did. We will replace each one by Day 64.",
 "God, I dug my own cistern because I was thirsty and no one handed me water. Teach me to drink from You. Amen.",
 "I put it down as my savior, my comfort, and my god.",
 "Workbook 4.2  |  Vol. II Ch. 3 (Contract 8)"),

(40, "The Bond You Mistook for Love", "Childhood · Addiction", "1 John 4:18",
 "There is no fear in love, but perfect love casts out fear. For fear has to do with punishment, and whoever fears has not been perfected in love.",
 "When harm and love arrive in the same package, your instrument for detecting safety gets miscalibrated. You can smell danger from a mile away and still walk straight into it. Your alarm works. Your identifier is off. It is rebuilt by new evidence, slowly, with safe people. If love has always had fear in it, real love can feel boring or suspicious at first. Do not trust the feeling of intensity. Trust the pattern over time.",
 ["Where has fear been tangled in love for me?", "Who in my life has been consistently safe?", "What evidence would I want to gather before trusting someone?"],
 "Make a list: three signs of a safe person. Check it against someone in your life.",
 "Lord, teach me what safe love looks like. Be the standard I measure by. Amen.",
 "I am building new evidence. Familiar is not the same as safe.",
 "Workbook 4.3  |  Vol. II Ch. 3 (Contract 5)"),

(41, "Control, Mother's Edition", "Motherhood · Childhood", "Matthew 6:27",
 "And which of you by being anxious can add a single hour to his span of life?",
 "If you can manage every variable, nobody can ambush you again. That made sense. It also means you cannot rest, cannot receive, and may be squeezing your children with a grip meant for a different danger. Hypervigilance feels like love. Sometimes it is. Sometimes it is a wound wearing competence as a uniform. Protecting children is part of mothering, and so is letting them be children.",
 ["Where am I controlling because I am afraid of being ambushed again?", "What would my kids say about my fear?", "What is one thing I could let be a little messy?"],
 "Choose one thing to loosen your grip on this week, and tell someone you are trying.",
 "Father, You see what I am afraid of. Hold what I cannot control. Let me rest in You. Amen.",
 "I open my hands. Control was never protection.",
 "Vol. II Ch. 3 (Contract 15)  |  Workbook 1.2"),

(42, "Worth That Isn't Work", "Motherhood · Childhood", "Luke 10:41-42",
 "But the Lord answered her, \"Martha, Martha, you are anxious and troubled about many things, but one thing is necessary. Mary has chosen the good portion, which will not be taken away from her.\"",
 "I only matter when I am useful. So you produce, you carry, you fix, you serve, and you cannot stop. Jesus did not shame Martha. He named what she was carrying and invited her to sit. For a mother who learned love was payment for labor, rest feels like disappearing. Test it honestly: who are you when you produce nothing?",
 ["Who am I when I am not useful to anyone?", "Where do I feel guilty when I rest?", "What would it mean to be loved at rest?"],
 "Do ten minutes of nothing useful today. Notice what comes up. Do not fix it.",
 "Lord, I am anxious about many things. Let me sit at Your feet for a minute without earning it. Amen.",
 "I am loved at rest. My worth was never output.",
 "Vol. II Ch. 3 (Contract 16)  |  Workbook 1.5"),

(43, "Self-Punishment", "Addiction · Motherhood", "Romans 8:1",
 "There is therefore now no condemnation for those who are in Christ Jesus.",
 "Part of you decided that as long as you keep paying, it is not unpunished. So you sabotage, you deny yourself, you stay in what hurts, or you relapse after good news. The bill was settled. Continuing to pay may feel like humility while it refuses a payment Jesus already made. Repair with people, where it is safe, is good. Punishing yourself is not repair.",
 ["How do I still punish myself?", "What am I paying for?", "What would accepting grace cost me, and what would it give?"],
 "Do one kind thing for yourself today that you would do for a friend.",
 "Jesus, You already paid. Teach me to receive it and to stop collecting. Amen.",
 "I am not going to keep paying for what He already bought.",
 "Vol. II Ch. 3 (Contract 17)  |  Workbook 4.4"),

(44, "Wanting Out", "Warfare · Motherhood · Addiction", "1 Kings 19:4-5",
 "But he himself went a day's journey into the wilderness and came and sat down under a broom tree. And he asked that he might die, saying, \"It is enough; now, O LORD, take away my life, for I am no better than my fathers.\" And he lay down and slept under a broom tree. And behold, an angel touched him and said to him, \"Arise and eat.\"",
 "A death wish is a symptom, not a sin, and not a truth. Elijah, Jonah, Job, and Moses all asked to die, and God's answer to Elijah was food, sleep, a whisper, and a new job, not a rebuke. Mothers in particular can slide into the lie that the kids would be better off. They would not. If that thought has teeth today, call or text 988, or 911, before you read another word. Postpartum Support International (1-800-944-4773) and the National Maternal Mental Health Hotline (1-833-852-6262) are there for mothers.",
 ["When did I first start wanting out?", "What is the pain underneath the wish?", "Who can I tell today?"],
 "If the thought is loud, stop here and call or text 988. If it is quieter, tell one person you trust today.",
 "God, I am tired. Feed me, let me sleep, and send me someone. Keep me here. Amen.",
 "I choose life. I will tell someone.",
 "Vol. II Ch. 3 (Contract 18)  |  Workbook Resources"),

(45, "The Accuser's Pen", "Warfare", "Zechariah 3:1-4 (v. 2 quoted)",
 "And the LORD said to Satan, \"The LORD rebuke you, O Satan! The LORD who has chosen Jerusalem rebuke you! Is not this a brand plucked from the fire?\"",
 "In Zechariah's vision, Joshua stands in filthy clothes with the accuser at his right hand. God does not argue Joshua's case. He rebukes the accuser and says, Remove the filthy garments. I have taken your iniquity away. The accuser says it once and you say it to yourself for thirty years. I am worthless. I always ruin things. Today you take the pen back. A defeated prosecutor does not get to write your story.",
 ["What sentence have I been finishing for the accuser?", "What are the filthy garments I am still wearing?", "What clothing does God offer instead?"],
 "Cross out the sentence in your writing, and write God's sentence over it: \"Remove the filthy garments.\"",
 "Lord, You rebuke the accuser. Take the filthy clothes I have been wearing and clothe me. Amen.",
 "I do not receive that. That is not mine. I take back the pen.",
 "Workbook 2.3  |  Vol. II Ch. 1, 3 (Contract 22)"),

(46, "Terrain, Not Guilt", "Motherhood · Childhood", "Ezekiel 18:20",
 "The soul who sins shall die. The son shall not suffer for the iniquity of the father, nor the father suffer for the iniquity of the son. The righteousness of the righteous shall be upon him, and the wickedness of the wicked shall be upon himself.",
 "Guilt does not transfer. Your children are not guilty of your past, and you are not guilty of your parents'. But terrain does: patterns, wounds, habits, biology, poverty, silence. You did not inherit their sin. You inherited the ground it was committed on. Exodus 20:5 says consequences reach down generations, and Ezekiel 18 says each person answers for their own. The same Bible says God's steadfast love reaches thousands. Do not let anyone tell you your child is cursed because of what you did. Do tell the truth about the terrain.",
 ["What has run in my family for three generations or more?", "Where do I see it in how I parent or want to parent?", "What would it mean to see my children as not guilty of any of it?"],
 "Write one pattern that has run in your family, and one way you are interrupting it.",
 "Father, I cannot change what I inherited, but I can walk differently. Meet my children where I could not. Amen.",
 "I did not inherit guilt. I inherited a terrain, and I can change what grows on it.",
 "Workbook 6.1  |  Vol. II Ch. 8"),

(47, "Drawing the Family Line", "Childhood · Motherhood", "Psalm 78:4",
 "we will not hide them from their children, but tell to the coming generation the glorious deeds of the LORD, and his might, and the wonders that he has done.",
 "Draw it. Three or four generations, both sides. Mark the patterns: addiction, abuse, suicide, early death, mental illness, poverty, abandonment, incarceration, silence. Then notice which columns have marks in three or more generations. This is not to blame your family. It is to see clearly, and to also see the good: faith, resilience, a grandmother who prayed. The same line that carried the pain carries gifts, and you get to choose what to pass on.",
 ["What patterns do I see?", "What good has also come down my line?", "What do I want my children's story to include?"],
 "Start the family map on the page, even partially. Add one good thing next to each side.",
 "Lord, show me my family as You see it. Thank You for the good, and help me carry it forward. Amen.",
 "I am looking straight at it. And I am looking at what is good, too.",
 "Workbook 6.2  |  Vol. II Ch. 8 (bloodline map)"),

(48, "Four Layers in the Nursery", "Motherhood · Warfare", "Romans 12:2",
 "Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect.",
 "A pattern can travel four ways. Behavioral: kids learn what they see. Biological: severe stress can shape how bodies respond, and scientists are still learning how. Systemic: poverty, incarceration, and lack of support are real walls. Spiritual: Scripture speaks of the enemy and of unhealed wounds, and Christians differ on how to understand this layer. Most people fight one layer and wonder why it did not hold. Work all four: practice new behavior, protect sleep and health, build support and use resources, and bring it to God.",
 ["Which layer have I been ignoring?", "What is one small action for each layer?", "Who could help with the one I cannot reach alone?"],
 "Write the four layers and one action for each, small enough to do this week.",
 "God, renew my mind and teach me to work all of it. Give me patience with the pace of change. Amen.",
 "I am working all four layers, not just the one I can see.",
 "Workbook 6.1  |  Vol. II Ch. 8"),

(49, "Where It May Have Started", "Childhood · Warfare", "Lamentations 5:7",
 "Our fathers sinned, and are no more; and we bear their iniquities.",
 "For each pattern, ask where it may have started. What did somebody in your line do? What was said over a child? What was done to your family: displacement, loss, a family destroyed? What secret does the family keep? You will not always find an answer, and you are not required to. Some of this is inference. Hold it with humility, and do not make it a diagnosis of any person. Naming a beginning often takes some of the weight off. Secrets grow in the dark.",
 ["What pattern do I most want to understand?", "What do I know about where it began?", "What do I not know, and can I let that be?"],
 "Write one possible starting place for one pattern. Label it \"maybe.\"",
 "Lord, You know what I cannot find. Bring light where it helps and mercy where it does not. Amen.",
 "I am finding the hinge, and hinges can be moved.",
 "Workbook 6.3  |  Vol. II Ch. 8"),

(50, "Standing in the Gap", "Motherhood · Warfare", "Nehemiah 1:6",
 "let your ear be attentive and your eyes open, to hear the prayer of your servant that I now pray before you day and night for the people of Israel your servants, confessing the sins of the people of Israel, which we have sinned against you. Even I and my father's house have sinned.",
 "Nehemiah prayed for his people with the words we have sinned, including himself. Daniel did too (Daniel 9). Many believers find this meaningful for family patterns: you do not take on their guilt, you agree with God about what is true, and you ask for mercy on your line. It is a practice to consider, not a requirement for freedom or a magic formula. If it does not sit right, skip it and talk to a pastor you trust. Mothers often do this naturally: praying for their children, their parents, and themselves in one breath.",
 ["Which pattern would I bring to God by name?", "What would it be like to pray it without defending anyone?", "What do I want to ask God for my children?"],
 "Pray for one pattern in your family in your own words, with no one else listening.",
 "God, I stand in the gap with You for the people I love. I tell the truth and ask for mercy. Amen.",
 "I stand in the gap as a daughter and mother of this family. I do not defend it.",
 "Workbook 6.4  |  Vol. II Ch. 8 (identificational repentance)"),

(51, "A Prayer for the Line", "Motherhood · Warfare", "Exodus 34:6",
 "The LORD passed before him and proclaimed, \"The LORD, the LORD, a God merciful and gracious, slow to anger, and abounding in steadfast love and faithfulness,\"",
 "Before any prayer about a family line, remember who is being prayed to: merciful, gracious, slow to anger, abounding in steadfast love. Pray it specifically, one pattern at a time: Father, I confess that ___ has run in my family. I do not defend it or hide it. I bring every vow, oath, and harsh word made in my family line to the cross of Christ, and I ask You to cancel its hold. Place my children and my family under Your protection. Do not let this pass on to them. Nothing here guarantees an outcome. It hands the outcome to the One who is merciful.",
 ["Which pattern am I praying over today?", "What do I want God to do for my children?", "What am I willing to do differently in response?"],
 "Pray the prayer once for one pattern. Write the date.",
 "Merciful Father, I bring this pattern, my family, and my children to You. Protect them. Begin with me. Amen.",
 "I trust Jesus to carry what I cannot, and I will do the work of changing what I can.",
 "Workbook 6.4  |  Vol. II Ch. 8"),

(52, "Agreements We Repeat", "Childhood · Motherhood", "Proverbs 26:2",
 "Like a sparrow in its flitting, like a swallow in its flying, a curse that is causeless does not alight.",
 "It is just how we are. Everybody in my family is like this. We die young. We do not do money. Nobody stays married. We say these like fate, and children hear them as fate. That is not prophecy. It is a pattern, and patterns can end. Proverbs 26:2 says a causeless curse does not land. Even more, Christ has redeemed us (Galatians 3:13, which speaks of the curse of the law; applying it to family patterns is a practical application, not the verse's direct subject). Watch the sentences you say over yourself and over your kids.",
 ["Which of these sentences do I say?", "Which have my children heard from me?", "What truer sentence could replace each?"],
 "Cross out one family \"we always\" sentence and write a truer one beside it.",
 "Lord, I do not want to speak fate over the ones I love. Put new words in my mouth. Amen.",
 "That was never prophecy. It was a pattern, and it ends.",
 "Workbook 6.5  |  Vol. II Ch. 6"),

(53, "New Behavior, Practiced Badly", "Motherhood · Addiction", "Ephesians 4:23-24",
 "and to be renewed in the spirit of your minds, and to put on the new self, created after the likeness of God in true righteousness and holiness.",
 "You can renounce a pattern perfectly and still repeat it, because nobody ever taught you something different. Prayer closes a door. Practice builds a house. If you grew up with yelling, you may have to learn calm like a second language. Name the inherited behavior and the concrete replacement. Find someone who does the thing you never saw, such as a parenting class, a therapist, a mentor, or a friend with a steady house, and get close enough to watch. Practice badly on purpose, because practicing badly is how it is learned.",
 ["What behavior did I inherit?", "What is the one I am building instead?", "Who can I watch or learn from?"],
 "Choose one replacement behavior and tell your child, a friend, or your counselor what it is.",
 "Father, teach me what I was never shown. Give me patience with myself and with the slow pace of learning. Amen.",
 "I am not just closing a door. I am building a different house.",
 "Workbook 6.6  |  Vol. II Step 26"),

(54, "Honor Without Repeating", "Childhood · Motherhood", "Exodus 20:12",
 "Honor your father and your mother, that your days may be long in the land that the LORD your God is giving you.",
 "You can honor your parents and refuse their pattern. Honor is not obedience, agreement, access, or silence. It means you do not degrade them, you do not build your identity on hating them, and you do not hand them your life as payment. If your mother harmed you, honoring may look like praying for her from a distance, speaking of her truthfully, and keeping safe boundaries. It is not betrayal to be the one who stopped it.",
 ["What can I genuinely honor about where I come from?", "What am I refusing to carry forward?", "What boundary protects both me and my children?"],
 "Write one honest, good thing about each parent or caregiver, if there is one. Then one thing you will not repeat.",
 "Lord, You asked me to honor, and You never asked me to be hurt. Show me what honor looks like safely. Amen.",
 "I honor where I came from. I am not repeating it.",
 "Workbook 6.7  |  Vol. II Ch. 8"),

(55, "The Line Stops Here", "Motherhood · Warfare", "Joshua 24:15",
 "And if it is evil in your eyes to serve the LORD, choose this day whom you will serve... But as for me and my house, we will serve the LORD.",
 "Write it, sign it, put it where your children can read it. Three things that end with me. Three things that begin with me. Then bless your children out loud, by name, regularly. Words can wound and words can bless. Speak over them what nobody spoke over you. A promise is not a guarantee about how they will choose, because each of them gets to choose. It is your choice, made in public, and that matters.",
 ["Three things that end with me:", "Three things that begin with me:", "How will I bless my children (or the people I love) this week?"],
 "Write your declaration and sign it. Bless one child or loved one aloud, by name.",
 "God, let it stop here, with You and with me. I place my house in Your hands. Amen.",
 "I can be the pivot. I am choosing to help what was meant to bury my family become something that frees it.",
 "Workbook 6.8  |  Vol. II Step 16"),

(56, "Twelve Patterns", "Warfare · Childhood", "2 Corinthians 2:11",
 "so that we would not be outwitted by Satan; for we are not ignorant of his designs.",
 "Volume II lays out twelve patterns that show up in the lives of people who have been hurt and stuck: being unwanted, early wounds, a false name, isolation, a coping tool, a shame loop, agreements, normalizing, passing it on, derailing the calling, waiting too long, silencing the story. This is a pattern-recognition tool, not a revealed schedule. Scripture also says much of our trouble comes from our own hearts, other people, and a broken world. Use it to notice, not to decide every hard thing was a scripted attack, and never to blame yourself for what was done to you.",
 ["Which of the twelve patterns do I recognize?", "Which is loudest right now?", "What would I need to interrupt it?"],
 "Mark the two patterns that fit you best. Do not analyze. Just notice.",
 "Lord, I do not want to be outwitted, and I do not want to see attacks everywhere. Give me clear eyes. Amen.",
 "I can read the pattern now. Predictable is beatable.",
 "Vol. II Ch. 12  |  Workbook 2.2"),

(57, "Isolation Is How It Gets In", "Motherhood · Addiction · Warfare", "Ecclesiastes 4:9-10",
 "Two are better than one, because they have a good reward for their toil. For if they fall, one will lift up his fellow. But woe to him who is alone when he falls and has no one to lift him up!",
 "Isolation makes almost every harm worse. Abusers isolate. Addiction isolates. Early motherhood isolates, and shame isolates most of all. This is why you need five kinds of people, not one: the one who knows everything, the one further ahead, the one behind you, the one who is just a friend, and the one allowed to correct you. For a mother in recovery, a meeting, a church small group, a moms' group, or a counselor can be the first of these.",
 ["Which of the five roles is empty for me?", "Where could I find one this month?", "What keeps me from reaching out?"],
 "Write the five roles with one name beside each, or a blank. Choose one blank to work on.",
 "God, You settle the solitary in a home. Put people around me, and give me courage to let them in. Amen.",
 "I will not do this alone. Alone was the plan, not the answer.",
 "Vol. II Ch. 12 (Stage 4), Step 24  |  Workbook Part V Step 6"),

(58, "Who Can Tell You You're Wrong", "Motherhood · Warfare", "Proverbs 27:17",
 "Iron sharpens iron, and one man sharpens another.",
 "A person who cannot be corrected is dangerous, and that includes a mother who is sure she is right. If nobody is allowed to tell you you are wrong, that is this month's assignment. Correction from someone who loves you is a gift, and it is also uncomfortable. Learn to hear it without collapsing into shame or attacking in defense. A teachable mother raises teachable children.",
 ["Who is allowed to tell me I am wrong?", "How did I take it the last time?", "What would help me receive correction without falling apart?"],
 "Ask one trusted person, \"What is one thing I could hear that would help me?\" Listen without answering.",
 "Lord, make me teachable. Give me friends who will tell me the truth with love. Amen.",
 "I would rather be corrected than be impressive.",
 "Workbook 3.4 (Work Page 11)  |  Vol. II Ch. 34"),

(59, "Running Out the Clock", "Motherhood · Warfare", "Ephesians 5:15-16",
 "Look carefully then how you walk, not as unwise but as wise, making the best use of the time, because the days are evil.",
 "One of the most common traps is not destruction. It is delay. Someday I will get help. Someday I will tell the truth. When the kids are older. When I am ready. A woman who is going to change soon for thirty years has changed nothing. This is not a call to panic or perfection. It is an invitation to pick one small, real step with a date on it, because your children are growing up on today's calendar.",
 ["What have I been about to do for years?", "What is the smallest version I could do this week?", "Who will hold me to it?"],
 "Put one date on the calendar for one small step. Tell one person.",
 "Father, redeem the time I have lost, and help me not to waste today. Amen.",
 "Not someday. Today has a date on it.",
 "Vol. II Ch. 12 (Stage 11)  |  Workbook 3.3"),

(60, "The Trigger Chain, Mid-Parenting", "Addiction · Motherhood", "1 Peter 5:8-9",
 "Be sober-minded; be watchful. Your adversary the devil prowls around like a roaring lion, seeking someone to devour. Resist him, firm in your faith, knowing that the same kinds of suffering are being experienced by your brotherhood throughout the world.",
 "Relapse is never one moment. It is a chain with six to ten links: the setting, the emotional state, the body, the thought, the justification, the first action, the point of no return, the use, the aftermath. For a mother, the links often include exhaustion, a child's meltdown, no support, and the thought, I just need a minute. Circle link three or four. That is where you intervene, because by link seven you had already decided. Note that Peter says you are not the only one.",
 ["What does my chain look like, step by step?", "Which link is earliest and detectable?", "What will I do the moment I see it, especially when the kids are in the room?"],
 "Write your chain and circle the earliest link. Write one action for it, such as a phone call or a walk.",
 "God, help me see the early links, and give me a plan for when the house is loud. Amen.",
 "I fight at link three. Link seven is not a fight, it is a formality.",
 "Workbook Part V Step 4  |  Vol. II Step 27, 28"),
]
