# Editorial corrections for The Whole Story, Volume II.
# (exact old text, new text). Build fails if any "old" is not found exactly once.

EDITS = [
# ---- Epigraph ----
("Then it shows you how to tear the whole thing down, line by line, with authority you already have.",
 "Then it shows you how to work through it, step by step, with Scripture, with safe people, and with the authority Christ gives His own."),

# ---- Book One ----
("Here is the thing almost nobody explains, and once you see it you cannot unsee it: **the spiritual realm runs on law, not on power.**",
 "*A note before this chapter: what follows uses a courtroom picture — legal ground, contracts, revoking — drawn from the legal language Scripture itself uses. It is a teaching frame, not a formula, and Christians hold different views on how literally to take it. Use what helps you, test all of it against Scripture, and never let it stand in for medical care, therapy, or safety.*\n\nHere is a picture that Scripture's own language makes possible: **the spiritual realm is not a contest of raw power. It is a matter of truth, law, and authority.**"),
("The Greek is *topos* — literally **place, ground, a legal foothold.**",
 "The Greek is *topos* — literally **a place, an opportunity, a foothold.**"),
("Sometimes a yes somebody else made on your behalf. It still functions.",
 "Sometimes a yes somebody else made on your behalf. It can still shape you."),
("The spirit realm recognizes **declared** agreement. That's why we renounce out loud — you are entering the same court the contract was filed in.",
 "Scripture takes spoken words seriously (Proverbs 18:21; Matthew 12:36–37; Romans 10:9–10). That's part of why we say these things out loud: speaking makes a decision real to *you*."),
("This isn't name-it-claim-it nonsense. It's that **you are a being with spiritual authority, and you used it against yourself.** That registers.",
 "This isn't name-it-claim-it nonsense, and your words did not seal your fate. But words shape how we see ourselves, and the ones you spoke in your worst hour have probably been echoing ever since. **You can bring them to God and speak something truer.**"),
("Sex is a **covenant instrument**, not a recreational act. It binds regardless of intent, context, or consent.",
 "Scripture treats sex as more than a casual act — it joins two people in a real way, which is part of why what happens there can leave a mark."),
("**Say the hard part out loud:** this includes what was done *to* you. A tie formed in assault is **not your sin** and it is **still a tie that needs cutting**. That's why a person you barely knew, or someone you never chose, can still have a hook in your body and your dreams twenty years later. You did not sign it. It still got filed. And it can still be cut.",
 "**Say the hard part out loud:** this includes what was done *to* you. What was done in assault is **not your sin** — it was a crime against you — and it can still leave a hold on your body, your dreams, and your trust twenty years later. You did not choose it, and you are not stuck with it. That kind of hold deserves real care: safe people, a trauma-informed counselor, and prayer."),
("**The thing nobody says:** a lot of survivors got into this **because nobody else was protecting them.**",
 "*Christians weigh some items on that list differently. Weigh them with Scripture and a trusted pastor. The point is not to frighten you about childhood games — it is to be honest about what you turned to for protection or answers.*\n\n**The thing nobody says:** a lot of survivors got into this **because nobody else was protecting them.**"),
("The word *pharmakeia* in Galatians 5:20 sits directly beside idolatry in Paul's list. Sit with that.",
 "Paul lists idolatry and sorcery (*pharmakeia*) side by side in Galatians 5:20. Scripture's concern is what rules you — not medicine taken under a doctor's care. If a prescription is part of your recovery, it stays."),
("unaddressed murder or abortion in the line", "unaddressed violence in the line"),
("Silence is the single most effective weapon against you, and it's the one your own family will help him enforce.",
 "Silence is one of the most effective weapons against you, and it's the one your own family may help enforce."),
("**This is why THKS exists. Saying it out loud is the warfare.**",
 "**This is why 7HE H0LY REUP exists. Saying it out loud is part of the fight.**"),
("**Every one of these was a child's attempt to build a father.** That's not wicked. It's grief.",
 "**Every one of these was an attempt to feel safe when nobody was keeping you safe.** That's not wicked. It's grief."),
("It functions like an open invitation, and it has to be revoked explicitly.",
 "It is not a spiritual contract you are trapped in. It is pain speaking, and it deserves a real answer: tell someone safe and get professional support."),
("**That one is the keystone. Pull it and things collapse.**",
 "**That one is often the keystone — the one that, once named, changes the most.**"),

# ---- Chapter 4: soul contracts ----
("What's real is this: **your soul makes agreements after birth, inside trauma, and those agreements bind.**",
 "What's real is this: **after birth, inside trauma, a child makes promises and decisions in order to survive — and those can keep running a life long after the danger is gone.**"),
("**A real soul contract is a vow made by your inner self, usually as a child, usually in a single unbearable moment, in order to survive — and never revisited.**",
 "**What people call a \"soul contract\" is, in reality, an inner vow: made by your inner self, usually as a child, usually in a single unbearable moment, in order to survive — and never revisited.**"),
("| Binding karmically | Binding by agreement, revocable by authority |",
 "| Binding karmically | Shaping you, and changeable with truth, support, and God's help |"),
("| Can't be broken, only \"completed\" | **Can be broken today, out loud, in Jesus' name** |",
 "| Can't be broken, only \"completed\" | **Can be released today — out loud, in Jesus' name, with support** |"),

# ---- Chapter 5: soul ties ----
("A soul tie is a **binding of soul to soul** — mind, will, emotion, identity — created by covenant, sex, trauma, deep loyalty, or vow.",
 "*\"Soul tie\" is not a phrase found in Scripture. It is a name many believers use for a real experience: a deep bond, or a painful hold, between you and another person. Scripture does describe real bonds between people (1 Samuel 18:1; Genesis 2:24; 1 Corinthians 6:16). We use the phrase here as a practical label, not a settled doctrine.*\n\nA soul tie, in this sense, is a **bond between two people** — mind, will, emotion, identity — formed by covenant, sex, trauma, deep loyalty, or vow."),
("### How to know you have one", "### How it can show up"),
("- You feel loyal to someone who harmed you\n",
 "- You feel loyal to someone who harmed you\n\n*These are also common after trauma and attachment wounds, and a counselor can help you sort out what is what. They are not proof that something spiritual is going on.*\n"),
("| Unresolved grief | A tie to the dead that keeps you from living — real and gentle to cut |",
 "| Unresolved grief | A bond to the dead that keeps you from living — real, and gentle to loosen |"),
("| Sexual violation | **Not your sin. Still a tie.** |", "| Sexual violation | **Not your sin.** It can still leave a hold. |"),
("### THE CUTTING — do this thoroughly", "### THE CUTTING (releasing the hold) — do this thoroughly"),
("> In the name of Jesus Christ and by the power of His blood, I sever every ungodly soul tie between me and [name]. I cut it — spirit, soul, and body. I cut it in the natural and in the spiritual realm.",
 "> In the name of Jesus Christ and by the power of His blood, I release my hold on [name] and ask You to loosen every unhealthy bond between us — spirit, soul, and body."),
("their shame, their sin, their words, their judgments, their spirit, their hold. **It goes back. I do not keep it.**",
 "their shame, their sin, their words, their judgments, their hold. **It goes back. I do not keep it.**"),
(">\n> Every spirit that traveled that tie — your road is closed. Leave. Go where Jesus sends you.\n", ""),

# ---- Chapter 6: words ----
("## 6. WORDS AS LEGAL INSTRUMENTS", "## 6. WORDS THAT BIND"),
("The spirit realm is a spoken realm. God created by speaking. Jesus healed and cast out by speaking. Curses are spoken. Blessings are spoken. Vows are spoken. **Your mouth is a legal instrument.**",
 "Scripture takes words seriously. God created by speaking. Jesus healed by speaking. Blessings are spoken. Vows are spoken. **Your words carry weight.**"),
("Proverbs 26:2 says an undeserved curse \"does not land\" — which also means **a curse with legal ground does.** That's the whole issue: ground.",
 "Proverbs 26:2 says a causeless curse \"does not alight.\" Words spoken against you by people with authority can wound deeply, but Scripture gives no reason to think a causeless curse has power over someone who belongs to Christ."),
("Every time you nod at a lie about yourself, you sign.", "Every time you nod along to a lie about yourself, you strengthen it."),
("This is not positive thinking. It's putting your legal instrument to work on the right side.",
 "This is not positive thinking. It's putting your words to work on the right side."),
("4. No weapon formed against me prospers. (Isa 54:17)", "4. No weapon formed against me shall succeed. (Isa 54:17)"),
("5. God did not give me a spirit of fear but of power, love, and a sound mind. (2 Tim 1:7)",
 "5. God gave me a spirit not of fear but of power and love and self-control. (2 Tim 1:7)"),
("6. Greater is He in me than he that is in the world. (1 John 4:4)",
 "6. He who is in me is greater than he who is in the world. (1 John 4:4)"),

# ---- Chapter 7: body ----
("a pact, a cutting, a miscarriage, an abortion, a violent assault — **it registered.** That's not something to be terrified of. It's something to know, so you can apply the answer.",
 "a pact, a cutting, a painful loss, a violent assault — **it mattered, and it was seen.** That's not something to be terrified of. It's something to bring to the One whose sprinkled blood speaks a better word (Hebrews 12:24)."),

# ---- Chapter 8: generational ----
("And Exodus 20:6 — the very next verse — says His steadfast love runs to **a thousand generations.** The mercy outruns the curse by a factor of 250. That's the actual math of the covenant.",
 "And Exodus 20:6 — the very next verse — says His steadfast love reaches **thousands** of those who love Him (Deuteronomy 7:9 says a thousand generations). The mercy outruns the consequence by a wide margin."),
("This is measurable science, not a metaphor. Severe stress alters gene expression, and those alterations pass to offspring. Studies of Holocaust survivors' descendants, famine survivors' grandchildren, and descendants of enslaved people show inherited alterations in stress-hormone regulation. **Your baseline cortisol may have been set by something that happened to your grandmother.** You inherited a nervous system already on alert.",
 "This is an active area of research. Studies of Holocaust survivors' descendants and other groups suggest severe stress can leave marks on stress-hormone regulation that show up in the next generation. Scientists are still working out how much, and how, and it is not destiny. **Your baseline may have been shaped by more than your own story.** You may have inherited a nervous system already on alert."),
("This is the layer that explains why the same thing happens in a bloodline **even when circumstances change completely** — the cousin raised in a good home who ends up the same way. Behavior doesn't explain that. Biology partly does. **Access explains the rest.**",
 "Some believers point to this layer to explain why the same thing shows up in a family **even when circumstances change completely** — the cousin raised in a good home who ends up the same way. Behavior and biology explain a lot of that. Whether there is also a spiritual layer, and how it works, is something Christians discuss, and Scripture gives us less detail than we may want. Hold it with humility."),
("- [ ] Barrenness / pregnancy loss / infant death\n", ""),
("- [ ] Specific disease clustering\n", ""),
("- [ ] Accidents, disasters, freakish misfortune\n", ""),
("- [ ] Children removed by the state, generation after generation\n",
 "- [ ] Children removed by the state, generation after generation\n\n*Illness, infertility, pregnancy loss, and accidents are griefs to be carried with comfort — not proof of a curse, and not anyone's failure.*\n"),
("**That's the urgency. That's why this is not a someday project.**",
 "**That's why this is worth doing — for you, and for whoever comes after you.**"),
("This is the piece that makes generational work *work*, and most people have never heard of it.",
 "This is a practice many believers have never heard of."),
("**You are not taking on their guilt. You are agreeing with God about what is true, as a legitimate representative of that bloodline, so that the standing agreement is answered by a superior one.** The contract was made by agreement; it is broken by a stronger agreement made by someone with standing. **You have standing. You're in the line.**",
 "**You are not taking on their guilt. You are agreeing with God about what is true, as someone who belongs to that family, and asking Him to do what only He can do.** Many believers find this meaningful. It is not a requirement for your freedom, and it is not a magic formula. If it does not sit right with you, skip it and talk with a pastor you trust."),
("> — I renounce every covenant, vow, oath, pact, dedication, and agreement made by anyone in my bloodline that gave the enemy access to us. Known and unknown. I revoke them all.",
 "> — I bring to the cross every covenant, vow, oath, pact, dedication, and agreement made by anyone in my bloodline that has shaped us for harm. Known and unknown. I ask You to cancel their hold."),
("> **Every spirit that has operated in this bloodline through [pattern]:** your legal ground is gone. Your assignment is terminated. I am not your inheritance. My children are not your inheritance. You may not transfer, relocate, or reassign. In the name of Jesus Christ — **leave, and go where He sends you.**",
 "> Jesus, I place myself, my children, and my family line under Your protection. Anything that is not from You — any lie, pattern, or influence that has run through **[pattern]** — I resist in Your name. Do not let it pass on to my children."),

# ---- Chapter 10: things nobody talks about ----
("Paul murdered believers and wrote half the New Testament.",
 "Paul persecuted believers and approved of their deaths, and went on to write much of the New Testament."),
("Right about the middle. That's the pushback, it's predictable, and it's a sign you're at the load-bearing wall. **Keep going.**",
 "Right about the middle. That urge is common, and it often means you have reached something that matters. **Slow down instead of quitting: rest, then come back.**"),
("**the renunciation of a ritual covenant does not require you to remember it perfectly.** \"Every covenant made over me, known and unknown\" is legally sufficient. God knows the paperwork even where your memory is a hole.",
 "**you do not need to remember everything perfectly to pray or to heal.** \"Everything done to me, known and unknown, I bring to You\" is enough. God knows what your memory cannot hold."),

# ---- Book Two ----
("A created being. An angel who fell (Isaiah 14:12–15; Ezekiel 28:12–17 — pride, self-exaltation, \"I will make myself like the Most High\"). Judged already. Sentenced already. Waiting for execution of sentence.",
 "A created being. Christian tradition reads Isaiah 14:12–15 and Ezekiel 28:12–17 (originally oracles against the kings of Babylon and Tyre) as also echoing the fall of a proud angel; the clearest New Testament glimpses are Luke 10:18 and Revelation 12:9. Either way: created, limited, already judged, waiting for the sentence to be carried out."),
("**He studies your patterns.** That's why patterns matter and why changing them blinds him.",
 "Scripture never says he can — though anyone who has watched a life for years can guess at patterns. That's one more reason to build healthier ones."),
("This is the one you asked for. Every stage, named. Read it and find yourself in it — and notice that seeing the plan on paper takes most of its power, because **every single stage depends on you not knowing it's a stage.**",
 "*A note before this chapter: this is a pattern-recognition tool, not a revealed schedule. Scripture says we are not to be ignorant of the enemy's designs (2 Corinthians 2:11), and it also says much of our trouble comes from our own hearts, other people, and a broken world. The stages are drawn from what Scripture warns about and from what survivors report. They are interpretation. Use them to notice patterns — never to decide that every hard thing in your life was a scripted attack, and never to blame yourself for what was done to you.*\n\nHere are twelve patterns that keep showing up in the lives of people who have been hurt and stuck. Read them and see where you recognize yourself — seeing a pattern on paper takes some of its power."),
("**This is where the generational curse gets renewed.** It doesn't automatically continue. **It continues because each generation re-signs it.**",
 "**This is where a family pattern gets passed on.** It doesn't automatically continue. **It continues when it goes unnamed and untreated — and it can stop when someone names it and gets help.**"),
("**Which is exactly why this workbook exists, and why THKS exists, and why you're going to open your mouth.**",
 "**Which is exactly why this book exists, and why 7HE H0LY REUP exists, and why you're going to open your mouth.**"),
("**Every single stage requires your unknowing cooperation.** Read that again. Not your consent — your **unknowing**. He needs you to not see the frame.",
 "**Every stage grows in secrecy and silence.** Read that again. Not because you failed — because being seen, known, and supported is what interrupts it. A pattern you can see is a pattern you can work on."),
("If you carry an assignment, the attack is not general. It's engineered. Here's the engineering.",
 "If you feel called to something, watch for these common ways a calling gets derailed. Some may be the enemy; many are simply human. You do not have to decide which in order to guard against them."),
("**Go back and look at what was attacked earliest and hardest. That's the blueprint he read before you did.**",
 "**Go back and look at what hurt earliest and hardest. That may point toward where you are meant to help — or it may simply be where you were hurt. Hold it loosely.**"),
("**Joseph got thirteen years first. That wasn't punishment — that was protection.**",
 "**Joseph got thirteen years first. Scripture doesn't say why, but it may have been preparation rather than punishment.**"),
("That's what THKS is — a building in the gap.", "That's what 7HE H0LY REUP is — a building in the gap."),
("**FAMILIAR SPIRITS** — the same thing, generation after generation, person after person. It knows your house.",
 "**FAMILIAR PATTERNS** — the same thing, generation after generation, person after person. Some believers understand this as a spiritual pattern; whatever you call it, it knows your house."),
("It is the single most reliable relapse predictor there is.", "It is one of the strongest relapse risks there is."),
("and he will time accusation to them.", "and accusation tends to hit harder at those times."),
("- [ ] Movement 20+ minutes daily — the only thing proven to move a craving in real time",
 "- [ ] Movement 20+ minutes daily — one of the best-supported ways to ease a craving in real time"),

# ---- Book Three / Four ----
("**6. Because the enemy is real and has limited legal ground in a fallen world**, and some of that ground was granted by human choices upstream of you.",
 "**6. Because the enemy is real, and some of the harm in a fallen world was made possible by human choices upstream of you.**"),
("## 29. THE TWELVE MARKS OF THE CALLED",
 "## 29. THE TWELVE MARKS OF THE CALLED\n\n*These marks describe patterns seen in Scripture and among survivors. They are not a test that proves you are \"chosen,\" and not having them does not mean you are any less loved or useful. Suffering alone is not a sign of calling.*"),
("- **Targeted attack.** Disproportionate. Read it as intelligence about what you carry, not evidence you're cursed.",
 "- **A brutal season.** It does not mean you are cursed, and it does not prove you are carrying something special. Ask for help either way."),

# ---- Book Five ----
("**Forty steps. Six phases. Twelve months. Nothing skipped.**",
 "**Thirty-three steps. Four phases. About twelve months. Nothing skipped.**"),
("**That is not evidence it isn't working. That is evidence something is trying to get its house back.** Write it down when it happens — naming the pattern removes the fear of it.",
 "**That is not proof it is failing, and it is not proof it is working — it is proof you have touched something real.** Sleep, eat, stay near your people, and tell your counselor or one safe person. Not every hard day is a spiritual attack, and you do not have to decide what caused it before you ask for help. Write it down when it happens — naming it makes it easier to face."),
("Identify where he's working on you **this week.**", "Notice which pattern is loudest **this week.**"),
("## PHASE 2 — LEGAL ACTION (Steps 8–17)", "## PHASE 2 — PRAYING IT THROUGH (Steps 8–17)"),
("**Do these with one trusted believer present if at all possible. Out loud always. Specific always — \"anything and everything\" is not how legal action works.**",
 "**A note before Phase 2:** these are prayers, not a formula. Scripture invites us to confess, forgive, and resist the devil (James 4:7; 5:16), but it does not hand us a script, and nothing here replaces a doctor, a counselor, or a pastor who knows you. You may skip any step that stirs up more than you can hold. Do these with one trusted believer present if you can. Out loud helps. Specific helps — \"anything and everything\" is hard to mean."),
("**This will not feel true the first time. Do it anyway. Feeling follows obedience — sometimes by months.**",
 "**This will not feel true the first time. Do it anyway. Feeling follows obedience — sometimes by months. And forgiving is not the same as trusting them again or letting them back in.**"),
("### STEP 15 — CUT EVERY SOUL TIE", "### STEP 15 — RELEASE EVERY HOLD (\"SOUL TIES\")"),
("> \"In the name of Jesus Christ I sever every ungodly soul tie between me and [name]. I return to them",
 "> \"In the name of Jesus Christ I release my hold on [name] and ask You to loosen every unhealthy bond between us. I return to them"),
("### STEP 17 — COMMAND IT OUT AND SEAL THE DOORS", "### STEP 17 — RESIST AND SEAL THE DOORS (OPTIONAL)"),
("Now — and only now, after everything above — you evict. **You do this last on purpose. You do not evict a tenant while the lease is still valid. Steps 8–16 tore up the lease. Now there's no legal ground, and this part is enforcement, not a fight.**",
 "This step is optional. If you believe something spiritual has been pressing on you, talk it over with a pastor or counselor you trust first, and skip it if it stirs up more than you can hold. Scripture's instruction is simple: submit to God, resist the devil, and he will flee (James 4:7)."),
("> \"Every spirit that entered through any door I have named — through trauma, through vow, through contract, through my bloodline, through what was done to me and what I did — hear me. Your legal ground is gone. It was revoked by the blood of Jesus Christ and by my agreement with God.\n>\n> I am not your house. I am bought, sealed, and occupied by the Holy Spirit.\n>\n> In the name of Jesus Christ: leave. Now. Go where He sends you. You may not transfer to my children, my family, my home, or anyone in this house. You may not return. Go.\"",
 "> \"Jesus, I belong to You. Anything that is not from You — any lie, fear, or influence that took hold through what I have named — has no place in my life, my home, or my family. In Your name I resist it, and I ask You to send it away. I am not its house. I am bought, sealed, and occupied by the Holy Spirit. Stay with me. Amen.\""),
("Naming the pushback in advance kills its power.**",
 "Naming what comes up makes it easier to face.**"),
("### Luke 11:24–26. An empty house gets reoccupied, worse. **Do not skip this phase. This is where most people lose everything they just won.**",
 "### Luke 11:24–26 is Jesus' picture of a swept house left empty. **Do not skip this phase — when something leaves your life, something good has to move in.**"),
("**Isolation is Stage 4 of the enemy's plan for a reason — it's the one that makes all the others work.**",
 "**Isolation makes almost every other harm worse, and being known by safe people is one of the strongest protections there is.**"),
("**That is not failure. That's an enemy running a known play.**",
 "**That is not failure. It's a familiar pull, and you can meet it with a plan.**"),
("Secrecy is the enemy's whole oxygen supply.", "Secrecy keeps shame alive."),

# ---- Book Six: forty questions ----
("Second: some of it absolutely was targeted, because there is something on your life he read early. **Those aren't contradictory.** Disproportionate attack is intelligence about your assignment, not evidence of a curse.",
 "Second: some of it may have been aimed at you, and I cannot know which. **Those aren't contradictory.** A brutal childhood is not evidence of a curse, and it is not proof of a special assignment either — it is something that deserves care."),
("**And every single one closes the same way, by the same blood, at the same price — already paid.** The door inventory is for closing them, not for prosecuting you.",
 "**And everything you carry comes to the same place — the cross, where the price was already paid.** The inventory is for bringing things to Jesus, not for prosecuting you."),

# ---- Book Seven: Brandi ----
("You built a movement because of a sister who didn't make it. You have said, out loud, that if a place like the one you're building had existed and she had reached for it, she might still be here.",
 "You built a movement because of a sister who didn't make it. You have said, out loud, that you wish she'd had a place like the one you're building — somewhere to reach when she knew something was wrong. No one can say whether it would have changed her outcome."),
("- **Part of the shape of your assignment.** Her absence is the exact shape of the thing you build — **a place to reach when you know something is wrong and don't know where to go.** That's the wound becoming a door. That's Joseph, starved of family, put in charge of feeding families.",
 "- **Part of why you build.** Her absence shapes the thing you are building — **a place to reach when you know something is wrong and don't know where to go.** That's a wound becoming a door, a little like Joseph, starved of family and later put in charge of feeding families."),
("**She knew. People in that condition often can't receive it, but not receiving it is not the same as not knowing it.**",
 "**I can't tell you what she knew. But love that was real does not vanish because it could not be received.** People in that condition often can't take it in, and that is not the same as it never mattering."),

# ---- Book Eight: two futures ----
("### Twenty years out, and the honest end of it\n\n**Here's the part nobody says out loud: for some people on this road, there is no twenty years.** Untreated addiction, untreated trauma, and untreated despair have a mortality rate. That's not a scare tactic, that's an obituary column. **You have read those names. You have buried one of them.**",
 "### Twenty years out, and the honest end of it\n\n**Here's the part nobody says out loud: untreated addiction, untreated trauma, and untreated despair do shorten lives.** That is not a scare tactic. It is why getting help matters. If that sentence is loud for you today, call or text 988 before you read another page."),
("The bridge she was supposed to build never got built, and the people who would have crossed it fell in the water, and they have names too, and she'll meet them one day.",
 "The bridge she was supposed to build never got built, and the people who would have crossed it went looking somewhere else."),
("Same woman. Same history. Same wounds. **Different terms.** Here is what actually happens, on a realistic timeline, because this part deserves detail too.",
 "Same woman. Same history. Same wounds. **Different choices.** Here is what *can* happen, on a realistic timeline, because this part deserves detail too. It is a picture of what is possible, not a promise."),
("They will grow up thinking the way you live is normal, and they will have no idea what it cost, and that is the definition of a curse being broken.",
 "They will grow up thinking the way you live is normal, and they will have no idea what it cost, and that is what a broken pattern looks like."),
("| **The contracts** | Still in force, still charging interest | Void, dated, nailed to the cross |",
 "| **The agreements made in pain** | Still running, still charging interest | Named, released, brought to the cross |"),

# ---- Book Nine ----
("Out loud matters — **the spirit realm responds to declared agreement, not private opinion.**",
 "Out loud helps — **saying it makes it real to you.**"),
("> I was consecrated before I was formed. The assignment came before the damage. The damage was aimed at the assignment — which means I know exactly where the treasure is buried, because I know where they dug.\n>\n> My wound is the shape of my assignment. I am the one who reaches back into the gap, because I have been in the gap, and I know the way out by name.",
 "> God knew me before I was formed, and what was done to me never canceled what He had in mind for me. The harm does not get the final word.\n>\n> My wound does not have to stay a wound. I can reach back into the gap, because I have been in the gap, and I know the way out by name."),
("> Every contract I signed in pain is void. Nailed to the cross. Dated and done.",
 "> Every agreement I made in pain, I bring to the cross, where the record of debt was nailed and canceled."),
("> The pattern that ran in my blood for four generations ends with me. I am the pivot. It does not pass to my children, and I have the date written down.",
 "> The pattern that ran in my family for generations can stop with me. I am choosing to be the pivot. I am working to keep it from passing to my children, and I have the date written down."),
("> What tried to end me is going to be the testimony that frees somebody else.",
 "> What tried to end me can become a testimony that helps somebody else."),
("**There is nothing in your life that the blood of Jesus Christ does not have legal authority over.**",
 "**There is nothing in your life that the blood of Jesus Christ does not reach.**"),
]
