# Editorial corrections for Trauma and the Spiritual Realm — Workbook.
# (exact old text, new text). Build fails if any "old" is not found exactly once.

EDITS = [
# ---- 1.4 the body ----
("## 1.4 What trauma does to the body (so you stop thinking you're broken)",
 "## 1.4 What trauma does to the body (simplified, so you stop thinking you're broken)"),
("**Trauma is stored in the body.** That's why talking alone doesn't finish it. You cannot think your way out of a body-level wound. You have to bring the body.",
 "**Trauma leaves its mark on the body.** Talking helps, and for many people it is not enough by itself. You cannot think your way out of a body-level wound. You have to bring the body."),
("Drops heart rate fast. Works when nothing else does.",
 "Can slow the heart rate fast. Works for many people when other things do not. (If you have a heart condition, ask your doctor before using cold water on your face.)"),

# ---- Part II: the realm ----
("This is not metaphor language. Paul means **there is an actual opposing structure.** It has ranks. It has strategy. It has a limit.",
 "Paul is describing something real: **an opposing spiritual reality, with structure and strategy — and a limit.** Christians hold a range of views on the details, and Scripture gives us less of a map than we sometimes wish. What it gives us clearly is Jesus."),
("**The THKS position: it is almost always BOTH, and you work both.**",
 "**Our working position: it is often more than one thing at once, and you work on every part that is there.**"),
("A wound can be real trauma AND an open door. A craving can be real neurochemistry AND a familiar spirit exploiting a groove. A rage can be your amygdala AND something riding it. Treat the body. Close the door. Both.",
 "A wound can be real trauma, and it can also be a place where lies and temptation find footing. A craving can be real neurochemistry, and it can also be a pull toward a false comfort. Treat the body. Tend the wound. Take the spiritual side to God. You do not have to decide which one it \"really\" is before you start getting help."),
("He does not know your thoughts. He studies your patterns. That's why patterns matter.",
 "Scripture never says he can read minds; only God knows the heart (1 Kings 8:39)."),
("**Demonic ranks** — Ephesians 6:12 lists rulers, authorities, cosmic powers, spiritual forces. There's structure. Practical version: some things attack individuals, some attach to bloodlines, some sit over places and systems. Which is why \"I moved and it followed me\" is a real experience and \"my whole family has this\" is a real pattern.",
 "**The enemy's forces** — Ephesians 6:12 names rulers, authorities, cosmic powers, and spiritual forces, and Colossians 2:15 says Christ disarmed them. Scripture says far less about how they work than people online pretend. You do not need a map of ranks. You need Jesus, honest people, and discernment — and you need to hold back from calling a hard experience demonic just because it is hard. A pattern that follows you from place to place, or runs through a whole family, is worth taking seriously, and worth bringing to a doctor, a counselor, and a trusted pastor together."),
("Access is not random. There is usually a **door**. Not to shame you — to give you something to close.",
 "Some struggles keep getting fed by the same things. Naming them is not meant to shame you — it gives you something you can change. Christians disagree about how much of this is spiritual, so use what helps and hold the rest loosely."),
("The #1 door in survivors, and the most understandable one.",
 "Very common in survivors, and very understandable."),
("- [ ] **Agreement with a lie** — every time you said \"I'm worthless,\" you signed something.",
 "- [ ] **Agreement with a lie** — \"I'm worthless\" is a lie you have been rehearsing, and it needs replacing with truth."),
("- [ ] **Sexual soul ties** — 1 Corinthians 6:16. Bodies are joining instruments. Trauma included. This is why some people you barely knew still have a hook in you.",
 "- [ ] **Sexual entanglements (\"soul ties\")** — 1 Corinthians 6:16 says sexual union joins two people. What was done to you against your will was a wrong done to you, not a sin of yours — and it can still leave a hold on your mind and body that is worth bringing to God and a counselor. (\"Soul tie\" is not a phrase in Scripture; it is a name many believers use for this experience.)"),
("- [ ] **Blood-line inheritance** — sin patterns running generations",
 "- [ ] **Family patterns** — sin and wounds running through generations"),
("Those are contracts you wrote in pain.", "Those are promises you made in pain."),
("- [ ] **Substances** — altering the mind removes the gatekeeper. The word \"pharmakeia\" in Galatians 5:20 sits in a list with sorcery for a reason worth thinking about.",
 "- [ ] **Substances** — altering the mind lowers your guard, and addiction can rule a life like an idol. (Galatians 5:20 lists sorcery — *pharmakeia* — next to idolatry; Scripture's concern is what rules you, not medicine taken under a doctor's care.)"),
("- [ ] **Trauma itself** — a wound is an unlocked window. That is not your fault. It is still your window to close.",
 "- [ ] **Trauma itself** — a wound can leave you more exposed and more alone. That is not your fault, and it is something you are allowed to tend."),
("- [ ] **Covenants made by others over you** — dedications, curses spoken by family, things done to you in rooms you don't fully remember.",
 "- [ ] **Things done or spoken over you by others** — dedications, harsh words from family, things you don't fully remember."),
("### WORK PAGE 7 — The door list", "### WORK PAGE 7 — The pattern list"),
("List every door you can identify. Next to it, write **\"CLOSED\"** only after you've done the renouncing in 2.6.",
 "List everything you can identify. Next to it, write **\"BROUGHT TO GOD\"** once you've prayed through it in 2.6, or **\"WORKING ON IT\"** if you're not there yet."),
("| Door | How it opened | Status |", "| Pattern | How it started | Status |"),
("**Revelation 12:11** — they overcame by the blood of the Lamb and the word of their testimony. **Your story is a weapon.** That's not a slogan. Telling the truth about what happened to you breaks the power of the secret it was hiding in.",
 "**Revelation 12:11** — they conquered by the blood of the Lamb and the word of their testimony. **Your story matters.** Telling the truth about what happened to you — to safe people, at your own pace — takes the power out of secrecy."),
("## 2.4 Open doors — how access happens", "## 2.4 What keeps feeding the struggle"),
("## 2.6 THE RENOUNCING — the actual words", "## 2.6 Praying it through — renouncing, forgiving, and handing it to God"),
("Do this out loud. Out loud matters — the spirit realm responds to declared agreement, not private opinion. Do it with one trustworthy believer present if you can. If you can't, do it anyway.",
 "**Before you pray this:** these prayers are a faith practice, not a formula. Scripture invites us to confess, forgive, resist the devil, and pray out loud with others (James 4:7; 5:16), but it does not hand us a script, and nothing here replaces a doctor, a counselor, or a pastor who knows you. You are allowed to skip any step that stirs up more than you can hold. Saying the words aloud helps many people mean them. Do it with one trustworthy believer present if you can. If you can't, you can still pray it alone."),
("**Step 4 — Renounce every door.**", "**Step 4 — Renounce what you've named.**"),
("> \"In the name of Jesus Christ I renounce [each door from Work Page 7, one at a time, out loud]. I break every agreement I made with it, knowingly or unknowingly. I revoke all permission. I close that door and I seal it with the blood of Jesus.\"",
 "> \"In the name of Jesus Christ I renounce [each item from Work Page 7, one at a time, out loud]. I break every agreement I made with it, knowingly or unknowingly. I take my hand off it, and I ask You to close that door and seal it with the blood of Jesus.\""),
("**Step 6 — Cut soul ties.**", "**Step 6 — Release what is not yours.**"),
("> \"In Jesus' name I sever every ungodly soul tie between me and [name, or 'the one whose name I don't know']. I return to them what is theirs. I call back to myself what is mine — my body, my mind, my peace, my identity, my future. What God did not join, I do not keep.\"",
 "> \"Jesus, I release my hold on [name, or 'the one whose name I don't know'], and I ask You to loosen their hold on me. I hand back what is theirs. I take back what is mine — my body, my mind, my peace, my identity, my future. What God did not join, I do not keep.\""),
("**Step 7 — Command it to go.**", "**Step 7 — Resist (optional).**"),
("> \"Every spirit that came in through those doors — I am not your house anymore. I am bought, sealed, and occupied. In the name of Jesus Christ, leave. Go where He sends you. You may not transfer to my children, my family, or my home. Go now.\"",
 "*If you believe something spiritual has been pressing on you, talk it through with a pastor or counselor you trust first. Scripture's instruction is simple: submit to God, resist the devil, and he will flee (James 4:7). Skip this step if it stirs up more than you can hold.*\n\n> \"Jesus, I belong to You. Anything that is not from You — any lie, fear, or influence that took hold through what I have named — has no place in my life, my home, or my family. In Your name I resist it, and I ask You to send it away. I am Yours. Holy Spirit, stay with me. Amen.\""),
("Do not skip this. Luke 11:24–26 — an empty house gets reoccupied, worse. Deliverance without discipleship is a revolving door.",
 "Do not skip this. Luke 11:24–26 is Jesus' picture of a swept house left empty, and the practical lesson is that when something leaves your life, something good has to move in."),
("What came at me in the days after (write it — the pushback is predictable and naming it kills the fear of it):",
 "What came up for me in the days after (write it — naming what comes up makes it easier to face):"),
("**Expect pushback.** Old contacts texting. Old dreams. A sudden crisis. An old craving with a new face. This is not evidence it didn't work. It is evidence something is trying to get its house back. Hold the door.",
 "**Expect a rough few days.** Old contacts texting. Old dreams. A wave of grief. A craving with a new face. This kind of work stirs things up. That is not proof it worked and it is not proof it failed — it is proof you touched something real. Sleep, eat, stay near your people, and tell your counselor or one safe person. Not every hard day is a spiritual attack, and you do not have to decide what caused it before you ask for help."),
("Ephesians 6:14–18. Put it on out loud, every morning, thirty seconds:",
 "Ephesians 6:14–18. Many believers put it on out loud, every morning, thirty seconds:"),

# ---- Part III: chosen ----
("Look at the pattern and find yourself in it:", "Look at the pattern and see whether you recognize yourself in it:"),
("## 3.2 The pattern — every single one of them", "## 3.2 A pattern you can see in many of them"),
("**Read that last one again. The fruit is always in the shape of the wound.**",
 "**Read that last one again: often, the fruit comes in the shape of the wound.** Not always, and not automatically. Scripture never tells us every wound is an assignment, and it never says God planned the harm. It does show Him bringing good out of it (Genesis 50:20)."),
("**Your assignment is in the shape of your wound.** That's not poetry. That's the pattern. That is why the enemy went after that exact spot early — he read the blueprint before you did.",
 "**Your story may point toward what you are meant to do** — look at where your wound and your compassion overlap. That is interpretation, not a guarantee. Hold it loosely and test it with mature people."),
("6. Then used — and the fruit is always in the shape of the wound.",
 "6. Then used — and often the fruit comes in the shape of the wound."),
("### WORK PAGE 9 — Reading your own blueprint", "### WORK PAGE 9 — Reading your own story"),
("Look at those five answers together. **That's the assignment.** Write it in one sentence:",
 "Look at those five answers together. **They may point toward something you are meant to do.** Write it in one sentence:"),
("Not all of it is attack — some of it is God clearing a table so He can seat the right people at it.",
 "Not all of it is attack — some of it may be God clearing a table so He can seat the right people at it."),
("**4. The specific attack.** The enemy fights hardest where he's losing most. If the attack on your life has been disproportionate — if it's been *weirdly* much — read that as intelligence about what you're carrying, not evidence that you're cursed.",
 "**4. A season that feels out of proportion.** If it has been *weirdly* much, that does not mean you are cursed — and it does not prove you are carrying something special, either. Some seasons are just brutal. Ask for help either way."),
("Every time you step up in assignment, it will knock.", "Often when you step up, it will knock."),
("That's what THKS is.", "That's what 7HE H0LY R3UP is for."),
("Brandi's absence does not get smaller because the work is real. It gets *carried better.* Different thing.",
 "The absence of someone you lost does not get smaller because the work is real. It gets *carried better.* Different thing."),

# ---- Part IV ----
("Rage allowed. Cussing allowed.", "Rage allowed. Raw words allowed."),
("Paul held coats at a stoning and murdered believers.",
 "Paul stood by at Stephen's stoning and went on to persecute believers (Acts 7:58–8:3)."),
("**Untreated mental illness is the #1 engine of relapse.**", "**Untreated mental health conditions are a common driver of relapse.**"),
("- [ ] **Remove it all.** Every stash, every backup, every \"just in case.\" Pour it out. Flush it. Have someone with you.",
 "- [ ] **Remove it all.** Every stash, every backup, every \"just in case.\" Dispose of it safely (many pharmacies take pills back). Have someone with you."),
("hard exercise (the only thing proven to move cravings in real time)",
 "exercise (one of the best-supported ways to ease a craving in real time)"),
("| Wake | Same hour, feet on floor, sunlight | Circadian reset; sleep is your #1 relapse predictor |",
 "| Wake | Same hour, feet on floor, sunlight | Body-clock reset; losing sleep is a major relapse risk |"),
("No going back to fix your family.", "No going back to fix your family. (If safety or housing is at stake, safety comes first.)"),
("A craving peaks at about 15–20 minutes. It cannot sustain itself. You only have to outlast a wave.",
 "A craving often peaks within 15–30 minutes and then fades, even when it does not feel like it will. You only have to outlast a wave."),
("- [ ] **Fast something, on purpose, on a schedule.** A meal. A day. Social media. Fasting teaches your body that a craving can be told no and nobody dies. That's the exact muscle you need.",
 "- [ ] **Fast something, on purpose, on a schedule.** Social media. Sugar. Screens. A meal, only if your doctor says it is safe for you — skip food fasting if you are pregnant, diabetic, have an eating-disorder history, or take medication with meals. Fasting practices the muscle of telling a craving no."),
("| 72 hours (the worst is usually here) | | |", "| 72 hours (for many people, the hardest stretch) | | |"),
("| 90 days (brain chemistry starts genuinely turning) | | |",
 "| 90 days (many people notice sleep, mood, and focus improving) | | |"),

# ---- Part VI ----
("**It is:** a pattern of sin, wound, agreement, and spiritual access that runs down a bloodline until somebody stands in the gap and stops it.",
 "**It is:** a way of naming patterns of sin, wound, and unhealed pain that can run down a family until somebody brings them into the light and changes course."),
("- **Biological** — epigenetics. Stress response literally passes down. Trauma changes gene expression in offspring. This is measurable.",
 "- **Biological** — research on epigenetics suggests severe stress can affect how the next generation's bodies respond to stress. It is an active area of science, not a settled verdict, and it is not destiny."),
("- **Spiritual** — access granted by covenant, vow, occult practice, or unrepented pattern, never revoked.",
 "- **Spiritual** — whatever a vow, a practice, or an unhealed wound opened that nobody ever brought to God."),
("You break all four with four different tools.", "You work all four with four different tools."),
("That's the urgency. That's why this isn't optional and isn't someday.",
 "That's why this is worth doing — for you, and for whoever comes after you."),
("an abortion, a murder, a betrayal, a dealing with spirits?", "a betrayal, a killing, a dealing with spirits?"),
("**Naming it here, on paper, has already reduced its power. That's not sentiment. That's how it works.**",
 "**Naming it here, on paper, often takes some of the weight off. Secrets grow in the dark.**"),
("## 6.4 STEP 3 — REPENT FOR THE LINE (IDENTIFICATIONAL REPENTANCE)\n\nThis is the part people skip, and it's the hinge.\n\nYou are not confessing their guilt as if it's yours. You are **standing in the gap as a legitimate representative of your bloodline and agreeing with God about what is true** — so the agreement that kept the door open is broken by an agreement of the opposite kind.",
 "## 6.4 STEP 3 — REPENT FOR THE LINE (IDENTIFICATIONAL REPENTANCE)\n\nMany believers find this meaningful. It is based on how Daniel, Nehemiah, and Ezra prayed for their people. It is a practice to consider, not a requirement for your freedom, and it is not a magic formula. If it does not sit right with you, skip to Step 4 and talk it through with a pastor you trust.\n\nYou are not confessing their guilt as if it's yours. You are **standing in the gap, as someone who belongs to that family, and agreeing with God about what is true.**"),
("> I renounce every covenant, every vow, every oath, every dedication, every word curse, and every agreement made by anyone in my bloodline that gave the enemy access to us. I revoke it. I cancel it. I nail it to the cross of Christ.",
 "> I bring to the cross of Christ every covenant, vow, oath, dedication, harsh word, and agreement made by anyone in my family line that has shaped us for harm, and I ask You to cancel its hold."),
("> Every spirit that has operated in my family line through [pattern] — your assignment is over. Your legal ground is gone. I am not your inheritance. In the name of Jesus Christ, leave my life and my bloodline. You may not pass to my children. Go.",
 "> Jesus, I place myself, my children, and my family line under Your protection. Anything that is not from You — any lie, pattern, or influence that has run through [pattern] — I resist in Your name. Do not let it pass on to my children."),
("**Do this once for every pattern on your list.** One at a time, specifically, out loud.",
 "**If you choose to pray this, do it once for every pattern on your list.** One at a time, specifically, out loud."),
("A curse needs a host. You've probably been agreeing with it without knowing.",
 "A pattern keeps going when we keep agreeing with it, and you have probably been doing that without knowing."),
("Words built the curse; words build the covenant. Speak over them what nobody spoke over you.",
 "Words can wound and words can bless. Speak over them what nobody spoke over you."),
("> I am the pivot. What was meant to bury my family is going to free it.",
 "> I can be the pivot. I am choosing to help what was meant to bury my family become something that frees it."),

# ---- Part VII ----
("**Step 5 — Cut the tie.** (2.6, Step 6.)", "**Step 5 — Release the hold.** (2.6, Step 6.)"),

# ---- Closing ----
("**The spiritual realm is real, you have authority in it, and you are not a victim in it.** Seated, not cowering.",
 "**The spiritual realm is real, and you are not helpless in it.** You belong to Christ, who has already won. Seated with Him, not cowering."),
("You are not being punished. You are being prepared, and the shape of your wound is the shape of your assignment.",
 "You are not being punished. God can use what you have been through, and He does not waste it."),
("**The line stops with you.** Four generations of it and you're the one standing in the gap. That's not a burden. That's the whole reason you're still breathing.",
 "**You can be the one who changes the pattern.** That can feel like a burden. It can also be the beginning of something good."),
("| Narcan / naloxone | Free or low-cost at most pharmacies, no prescription needed in all 50 states |",
 "| Narcan / naloxone | Free or low-cost at many pharmacies and health departments; available without an individual prescription at most pharmacies |"),
]
