# Editorial corrections applied to the 90 Days of Freedom Journal text.
# Every entry is (exact old text, new text). The build stops if an "old" string
# is not found exactly once, so the original wording can never drift silently.
# Purpose: keep the heart and cadence of each page, and correct claims that go
# past what Scripture teaches (see the "Editor's note" printed in the book).

EDITS = [
# ---- Arc One ----
("Ninety days from now you will be a different woman. Today all you have to do is start.",
 "Ninety days from now you may be standing somewhere you cannot see yet. Today all you have to do is start."),
('"If we confess our sins, he is faithful and just to forgive us and to cleanse us." — 1 John 1:9',
 '"If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness." — 1 John 1:9'),
("Everything you keep hidden keeps its power. Secrecy is the enemy's whole oxygen supply, and it is the only thing he genuinely needs from you. Pick one person",
 "Everything you keep hidden keeps its power over you. Secrecy is what shame lives on. Pick one person"),
("Untreated mental illness is the number one engine of relapse. Get bloodwork",
 "Untreated mental health conditions are a common driver of relapse. Get bloodwork"),
("Clear the first seventy-two hours. Stock the house. Decide now where you go if home is not safe.",
 "Clear the first seventy-two hours. Stock the house. Decide now where you go if home is not safe. And if you use alcohol, benzodiazepines, or barbiturates, do not stop cold on your own — withdrawal from those can be deadly. Call a doctor or the SAMHSA helpline (1-800-662-4357) before your date."),

# ---- Arc Two ----
("Most people did it seven times. You were not slow.",
 "Most people try more than once before they leave for good. You were not slow."),
("Fragmented memory is evidence of severity, not evidence of fabrication. The gaps are not you lying. The gaps are the size of the wound.",
 "Fragmented memory is common after trauma, and it does not mean you are lying. The gaps are not a character flaw. They are what a mind does when it is trying to survive."),

# ---- Arc Three ----
("Ephesians 6:12 is not poetry — there is an actual opposing structure with ranks and strategy and a hard limit. You have been fighting in a war you were told was just your personality.",
 "Ephesians 6:12 says our struggle is not only against flesh and blood — Scripture treats unseen opposition as real, and as limited. Some of what you have been calling \"just my personality\" may be wound, body, habit, or something spiritual. These pages will help you start telling the difference."),
("I am not imagining the war. And I am not losing it.",
 "I am not imagining what I have been through. And I am not fighting it alone."),
("Colossians 2:15 — He disarmed the powers and made a public spectacle of them. You are not fighting for a victory. You are enforcing one. Ephesians 2:6 says you are seated with Him in heavenly places. Positional. Above, not below.",
 "Colossians 2:15 says Christ disarmed the rulers and authorities and put them to open shame. Ephesians 2:6 says we are seated with Him in the heavenly places. One way to hold that: you are not praying for a victory that might not come — you are standing on one already won. That is a reading of these verses, not a formula, and it is never a reason to stop getting help."),
("What have I been begging for that I am actually authorized to enforce?",
 "Where have I been acting like the outcome is still undecided?"),
("I am not negotiating. I am enforcing what was already won.",
 "I am not negotiating with fear. I am standing on what Christ has already won."),
("Access is rarely random. Unforgiveness. Agreement with a lie. Occult contact, even the kid version you did for protection because nobody else was protecting you. Sexual ties. Inherited patterns. Vows. Substances. Trauma itself is an unlocked window — not your fault, still your window.",
 "Some struggles keep getting fed by the same things. Unforgiveness. Believing a lie about yourself. Occult contact, even the kid version you did for protection because nobody else was protecting you. Sexual entanglements. Inherited patterns. Vows you made in pain. Substances. And trauma itself, which can leave you more exposed — not your fault, and still something you are allowed to tend. Christians disagree about how much of this is spiritual and how much is human, so list it honestly and bring it to someone wise."),
("Every door I can identify right now:", "Every pattern I can name right now:"),
("Every door has a name, and every named door can be closed.", "Everything I can name, I can bring to God and start to change."),
("One person at a time, out loud. Not because it was okay — it was not okay. Because unforgiveness is a contract that keeps them in the room, and Matthew 18 says the unforgiving servant goes to the jailer. That jailer is not their punishment. It is yours.",
 "One person at a time, out loud. Not because it was okay — it was not okay. Because unforgiveness keeps them in the room with you, and in Jesus' parable in Matthew 18 the servant who will not forgive ends up with the jailers. That is not their punishment. It is yours."),

# ---- Arc Four ----
("Bondage runs on permission — a door, an agreement, a vow, something signed in pain, often before you could spell. That sounds terrifying until you see the other side: anything that runs on legal ground can be revoked. And the revocation was already purchased.",
 "Some of what binds us began as an agreement — a vow, a belief, something you said yes to in pain, often before you could spell. Scripture uses the language of debts and records, and Colossians 2:14 says Christ canceled the record of debt that stood against us. Picture it as paperwork if that helps: what you agreed to in pain does not get the final word over you."),
("What runs on a contract can be voided. Mine already was.",
 "What I agreed to in pain does not get the final word. Christ does."),
('"Do not swear at all... let what you say be simply yes or no." — Matthew 5:34,37',
 '"Do not take an oath at all... Let what you say be simply \'Yes\' or \'No.\'" — Matthew 5:34,37'),
("You said it in the worst hour of your life and it went on the record. Words are legal instruments, which is also why they are how you tear it down.",
 "You said it in the worst hour of your life, and part of you has been living by it ever since. Words carry weight, which is also why saying something truer out loud helps."),
("I renounce every word I spoke in pain. It has no claim.",
 "I take back every word I spoke in pain. It does not get to run my life."),
("Exposure to safe light is the only thing shame cannot survive.",
 "Safe light is what shame cannot stand."),
("Secrets are load-bearing walls for curses — pull one out and a lot comes down at once.",
 "Secrets are load-bearing walls for unhealthy family patterns — pull one out and a lot comes down at once. Do it with support, and never in a way that puts you in danger."),
('"Do you not know that he who joins himself to a prostitute becomes one body with her?" — 1 Cor. 6:16',
 '"Or do you not know that he who is joined to a prostitute becomes one body with her?" — 1 Cor. 6:16'),
("Bodies are joining instruments, and that includes what was taken from you. It is why someone you barely knew still has a hook in you. Cutting a tie is not denying that it happened. It is refusing to keep paying rent on it.",
 "\"Soul tie\" is not a phrase in Scripture, but survivors know the feeling: someone you barely knew, or someone who harmed you, still has a hold on your thoughts. Scripture does say sexual union joins two people in a real way (1 Corinthians 6:16). What was taken from you was a wrong done to you, not a sin you committed. Letting go of a hold like that is not denying it happened. It is refusing to keep paying rent on it."),
("Out loud: in the name of Jesus Christ I sever every ungodly soul tie between me and ___. I return everything of theirs I have carried — their shame, their blame, their voice in my head, their version of me. I call back my body, my mind, my peace, my identity, my future.",
 "Out loud: Jesus, I release my hold on ___ and I ask You to loosen their hold on me. I hand back everything of theirs I have carried — their shame, their blame, their voice in my head, their version of me. I take back my body, my mind, my peace, my identity, my future."),
("But the bill was settled, and continuing to pay it is not humility. It is calling the cross insufficient.",
 "But the bill was settled, and continuing to pay it may feel like humility while it refuses a payment Jesus already made."),
("When did I first agree with death, and do I revoke it?",
 "When did I first start wanting out, and who can I tell about it?"),
("I renounce every agreement I made with death. I choose life.",
 "I turn away from every thought that says I would be better off gone. I choose life, and I will tell someone."),
("The most efficient contract of all: he says it once, and you say it for him for the next thirty years. Every time you finished his sentence — I am worthless, I always ruin things — you signed. He has not had to work in years. Today you take the pen back.",
 "The most efficient lie of all: it gets said once, and you say it to yourself for the next thirty years. Every time you finish the accuser's sentence — I am worthless, I always ruin things — you strengthen it. Today you take the pen back."),
("What sentence of his have I been finishing for him?", "What sentence of the accuser's have I been finishing for him?"),

# ---- Arc Five ----
("You did not inherit their sin. You inherited the terrain — and the door has stood open for four generations because nobody walked over and shut it.",
 "You did not inherit their sin. You inherited the terrain — and the door has stood open for generations because nobody walked over and shut it."),
("But consequence, pattern, wound, and access absolutely do.", "But consequence, pattern, and wound absolutely do."),
("Biological — stress response genuinely passes down, and that is measurable.",
 "Biological — research suggests severe stress can affect how the next generation's bodies respond to stress, though scientists are still learning how."),
("Spiritual — access granted and never revoked.",
 "Spiritual — whatever a vow, a practice, or an unhealed wound opened that nobody ever brought to God."),
("For each pattern ask where it got permission.", "For each pattern ask where it may have started."),
('"Nothing is hidden from him." — Hebrews 4:13', '"O LORD, you have searched me and known me!" — Psalm 139:1'),
("You are not taking their guilt. You are agreeing with God about what is true, and that agreement breaks the one that held the door.",
 "You are not taking their guilt. You are agreeing with God about what is true, and telling the truth about what ran in your family is part of how a pattern loses its hold."),
("Out loud, one pattern at a time: Father, I confess that ___ has run in my family. I do not defend it or hide it. I renounce every covenant, vow, oath, dedication, and word curse made by anyone in my bloodline that gave the enemy access. I revoke it. I nail it to the cross of Christ.",
 "Galatians 3:13 speaks of the curse of the law; applying it to family patterns is a practical application, not the verse's direct subject. Out loud, one pattern at a time: Father, I confess that ___ has run in my family. I do not defend it or hide it. I bring every covenant, vow, oath, dedication, and harsh word made by anyone in my family line to the cross of Christ, and I ask You to cancel its hold."),
("It has no right to me, my body, my children, or any generation after me.",
 "I am choosing to live under Christ, and I will do the work of changing what I can."),
('"According to your faith be it done to you." — Matthew 9:29',
 '"Like a sparrow in its flitting, like a swallow in its flying, a curse that is causeless does not alight." — Proverbs 26:2'),
("A curse needs a host. It is just how we are.", "Sometimes we keep a pattern alive by treating it as fate. It is just how we are."),
("Words built the curse. Words build the covenant. Speak over them what nobody spoke over you.",
 "Words can wound and words can bless. Speak over them what nobody spoke over you."),
("I am the pivot. What was meant to bury my family is going to free it.",
 "I can be the pivot. I am choosing to help what was meant to bury my family become something that frees it."),

# ---- Arc Six ----
("It is a plan, and plans can be read.",
 "Patterns can be read. (This is a pattern-spotting tool, not a revealed schedule — Scripture warns us not to be ignorant of the enemy's designs, and it also warns against blaming the devil for everything. Use it to notice, not to label every hard thing an attack.)"),
("Which stage is he working on me this week?", "Which of these patterns is loudest in my life this week?"),
("Stage four is isolation, and it is the one that makes every other stage work.",
 "Stage four is isolation, and it makes almost everything else harder."),
("Every called person who crashed had this slot empty.", "Many people who crash have this slot empty."),
("His best move is not your destruction. It is delay. A woman who is going to change soon for thirty years causes him no problems at all. Someday costs him nothing. A date costs him everything.",
 "One of the most common traps is not destruction. It is delay. A woman who is going to change soon for thirty years has changed nothing at all. Someday costs nothing. A date changes everything."),
("Most collapses are three of those stacked and none of them are about the substance. Run the check three times a day. Half of what feels like a craving is blood sugar, and half of what feels like despair is sleep.",
 "Many relapses are several of those stacked — and they are not only about the substance. Run the check three times a day. Some of what feels like a craving is blood sugar, and some of what feels like despair is sleep."),
("A craving peaks in fifteen or twenty minutes and cannot sustain itself.",
 "A craving often peaks and fades within fifteen to thirty minutes, even when it does not feel that way."),
("An empty house gets reoccupied, worse. This is why deliverance without discipleship is a revolving door.",
 "Jesus told a story about a swept house left empty, and the last state was worse than the first. Whatever your view of the spiritual side, the practical truth stands: when something leaves your life, something has to take its place."),
("Sleep is the single biggest predictor of everything else.", "Sleep affects almost everything else."),

# ---- Arc Seven ----
("Lamentations is a man accusing God to His face and God kept it in the canon.",
 "Lamentations is grief laid out before God, and God kept it in the canon."),
('"God works all things together for good for those who are called." — Romans 8:28',
 '"And we know that for those who love God all things work together for good, for those who are called according to his purpose." — Romans 8:28'),

# ---- Arc Eight ----
("She is in the hands of someone kinder than the people who scared me.",
 "I am putting her in the hands of someone kinder than the people who scared me."),
("Then write the indictment you have been running against yourself, and burn it outside, and watch it go.",
 "Then write the indictment you have been running against yourself, and — if you can do it safely — burn it outside and watch it go."),

# ---- Arc Nine ----
("The assignment predates the damage. Which means the damage never disqualified it — it was aimed at it. The enemy read the blueprint before you did and went after the exact spot early. So you know precisely where the treasure is buried, because you know where they dug.",
 "God knew you before you were formed, which means what was done to you never canceled what He had in mind for you. (The verse was spoken to Jeremiah about his own call; read it as a window into how God knows His people, not a promise of a particular assignment.) I cannot tell you the harm was aimed at your calling — I do not know that. But the place that hurt most is often the place you understand best, and that can become a place you help from."),
("What was attacked earliest, and what did they try hardest to take?",
 "What hurt earliest, and what did it try hardest to take?"),
("The calling came first. The damage came at it, not instead of it.",
 "God's knowing came first. The harm does not get the final word."),
("The fruit is always in the shape of the wound.",
 "Often the fruit comes in the shape of the wound — not always, not automatically, and never as a reason to call the wound good."),
("My wound is the shape of my assignment. It is a door now.",
 "My wound does not have to stay a wound. It can become a door."),
("Marked early, isolated, delayed, misunderstood, broken in one specific place, then used. Every one of them.",
 "Many of the people in Scripture were marked early, isolated, delayed, misunderstood, broken in one specific place, then used."),
("One future is the woman who knew exactly what she was for, could describe it in detail, told people about it — and did not do it, while the pattern passed on intact. The other has the contracts void, the line stopped in writing, five people who know her, and somebody alive because of what she built. Same woman. Same scars. Different terms.",
 "One possible future is the woman who knew exactly what she was for, could describe it in detail, told people about it — and never started, while the pattern passed on. Another is the same woman, with the agreements she made in pain released, the pattern interrupted, five people who truly know her, and somebody helped because of what she built. Neither is guaranteed. Choices are what you have, and you get to make a small one today."),
("I am not going to be the woman who almost did it.",
 "I am going to do it — scared and imperfect and on a date."),

# ---- Day 91 / back pages ----
("And somebody is going to get out because you did.", "And somebody may get out because you did."),
("Narcan (naloxone) is available without a prescription at most pharmacies, and free through many county health departments and harm-reduction programs. Get it and keep it in the house even if you do not use. It reverses an opioid overdose in minutes and you cannot hurt someone by giving it.",
 "Narcan (naloxone) is available without an individual prescription at most pharmacies, and free through many county health departments and harm-reduction programs. Get it and keep it in the house even if you do not use. It can reverse an opioid overdose, and it will not hurt someone who did not take opioids."),
]
