# Ninety Days of Coming Home — days 1–30.
# (day, title, step, prayer, affirmation, challenge, anchor reference)
# Anchors are cited by reference only (read the verse in your own Bible).

H1 = [
(1, "Build Her a Safe Place", "Before you go anywhere near the past, build a place in the present. Choose a real or imagined room: where is it, what is the light like, what is on the walls, what is soft, what can she hear? Write five details. Nothing from the past comes into this room today. You are only building it.",
 "Lord, make this room real enough to rest in. Be the first one in it.", "I am safe enough to begin, and I can stop whenever I need to.",
 "Put one comforting object (a blanket, a candle, a smooth stone) where you will see it every day this week.", "Psalm 91:1"),
(2, "Choose Who Stands With Her", "Write on a card the names of who stands with her: Jesus, one safe person, a counselor if you have one, and a companion you love (Big Boy, if you want him there). Tell one of them today that you are beginning something tender and ask if you can check in this week.",
 "Father, You do not send me anywhere alone. Put people around her and me.", "She does not have to be alone this time.",
 "Send one text: \"I am starting something hard. Can I check in with you this week?\"", "Ecclesiastes 4:9-10"),
(3, "Two Hands for Her", "No stories today. On two lines write: \"What was done to her:\" and \"What she did to survive:\" Fill each with just a few words. Remind her that she is allowed to have both and that nobody here is judging her.",
 "Jesus, hold both of these with me. Let her be honest without being ashamed.", "I can hold what was done to me and what I did, and still be loved.",
 "Say one kind sentence out loud to a child you see today, or to a photo of one.", "Romans 7:15"),
(4, "Her Shame, Your Compassion", "Find a photo of yourself as a child, or picture her at an age you already know about. Finish her sentence: \"She is ashamed that…\" Then answer as the adult you are now: \"That was never yours.\" If there is no photo, draw a simple figure and write beside it.",
 "God, lift the shame off her. Let her see my face with Yours behind it.", "The shame she carried was never hers to carry.",
 "Drink a full glass of water while you look at her photo or drawing.", "Psalm 34:5"),
(5, "Her Body Kept Guard", "Place a hand where your body holds the most tension. Say to it, quietly: \"You kept her alive. We are safe now. You can rest.\" Stay for ten slow breaths. If that spot is numb, put your hand on your chest instead.",
 "Father, thank You for the body that stood watch. Teach it it is not on duty alone.", "My body is not broken. It remembers, and it can learn rest.",
 "Stretch for two minutes: reach up, roll your shoulders, shake out your hands.", "Psalm 56:8"),
(6, "How Old Is She?", "Notice how old the fear feels today. Not what happened, only the age. Write the number. Say hello to that age: \"I see you. I am the grown-up now. I am here.\" Do not go further than hello today.",
 "Lord, You know every age of me. Come to the one who is waiting.", "I can say hello to her without going back into the fire.",
 "Make yourself a warm drink and drink it slowly, sitting down.", "Isaiah 66:13"),
(7, "Teach Her the Resets", "Teach her one reset the way you would teach a child. Breath: \"smell the flower, blow out the candle,\" four in, a long breath out. Or press your feet into the floor. Practice three times together, then say, \"You can do this any time.\"",
 "Jesus, give her tools she can carry. Let her calm come from You.", "I am teaching her how to feel safe.",
 "Do your reset once at a random time today when nothing is wrong.", "Psalm 46:10"),
(8, "List, Don't Tell", "Write only titles, one line each, no details: the main hard things she lived through. When you finish, ask her: \"Is there anything you want me to know today?\" Write whatever comes in one line. If nothing comes, that is fine.",
 "God, I will go only as far as You and she can bear. Keep the pace gentle.", "Naming is not reliving. I can list without going in.",
 "Close the notebook and do something with your hands for ten minutes: wash dishes, braid, sort a drawer.", "Psalm 139:23-24"),
(9, "Take Her to the Doctor", "Her body is yours to care for now. Make one appointment you have been avoiding: a checkup, bloodwork, a counselor, or a sleep assessment. Tell her: \"I am taking care of you.\" If you are in crisis, call or text 988.",
 "Lord, You made healers. Give me courage to let someone help her.", "Caring for her body is faith, not weakness.",
 "Eat one real meal sitting down, with no phone.", "Jeremiah 8:22"),
(10, "Set the Ground Rules", "Before tomorrow, set three rules in writing: (1) a stop word you can say any time, (2) ten minutes only, with a timer, (3) a landing: warm drink, a walk, and a text to someone after. Also: you will use only what you already know, and you will never hunt for memories. If your history includes severe trauma, dissociation, or ritual abuse, do this with a trained trauma therapist.",
 "Father, set the boundaries of this work with me. Let nothing go further than I can hold.", "I am in charge of the pace, and she can trust that.",
 "Prepare a landing kit: tea, a blanket, a playlist, a phone number. Put it where you will do this work.", "Proverbs 4:26"),

(11, "Visit Her at the Doorway", "Set a ten-minute timer. In your imagination, stand at the doorway of a room at an age you already know about. Do not go in. Just see her from the door: what is she doing? Do not fix anything. When the timer rings, say, \"I will come back,\" take your landing, and write three words for what you saw. This is prayerful imagination, not a memory test.",
 "Jesus, stand at the door with me. Let me see only what I can bear.", "I can look at her from the doorway and come back safe.",
 "After your visit, take a short walk outside and name five colors.", "Psalm 139:12"),
(12, "Ask What She Believes", "Return to the doorway for ten minutes. Ask her gently: \"What did you decide about yourself?\" Write exactly what she says, in her words, without arguing with it. It is not truth yet. It is what she believed.",
 "Lord, let me hear her without correcting her. Then tell us both what is true.", "I can listen to what she believed without believing it myself.",
 "Tell one safe person one thing you learned today. Just one.", "John 8:32"),
(13, "Tell Her What They Called Her", "Write the names she was called, in the words used. Then read them aloud to her as an adult who is on her side, and say after each: \"That was said about you. It was not true of you.\"",
 "Father, You called me by name before anyone else did. Say it over her.", "What was said about me is not who I am.",
 "Write one name on a slip of paper and put it in a drawer, out of sight.", "Isaiah 43:1"),
(14, "Give Her a New Name", "Choose the name God gives her: beloved, chosen, new creation, known. Write it on a card. Put it where you will see it, and say it to her tonight before you sleep.",
 "Jesus, write the new name on her heart. Let it be louder than the old.", "She has a name from God, and I can answer to it.",
 "Say her new name to yourself in the mirror three times today.", "Revelation 2:17"),
(15, "Tell Her It Was Not Her Fault", "Go to the doorway. Say to her, three times, slowly: \"It was not your fault.\" If she argues, let her, and say it again. If she cannot hear it today, say it again tomorrow. It may take many times.",
 "Father, take the blame she picked up and give her compassion in its place.", "It was not my fault. I was a child.",
 "Do one small act of play today: color, hum, jump in a puddle, dance to one song.", "Psalm 103:13"),
(16, "Listen to Why She Went Back", "Ask her: \"Why did you go back?\" Listen for the reasons: it was familiar, she loved them, she had no options. Do not scold. Say, \"Thank you for surviving. We are building a way out that does not hurt.\"",
 "Jesus, You prayed for Peter before he fell. Pray for her. Turn her again.", "She was not stupid. She was surviving.",
 "Write one thank-you to the part of you that survived.", "Luke 22:31-32"),
(17, "Let Her Say What She Misses", "Ask her what she misses, whether a person, a feeling, or a place. Let her say it without shame. Then offer one safe thing that gives a small piece of what she is longing for, such as a hug from a friend, a favorite song, or a sunset.",
 "God, You satisfy the longing soul. Give her what is good and safe.", "What I long for is not shameful. I can feed it safely.",
 "Give someone a real hug today, or hug a pillow while you breathe.", "Psalm 107:9"),
(18, "Thank the Gaps", "You do not need to remember everything. Do not push for memory. Draw a blank page, and write across it: \"Mercy.\" Tell her: \"We do not have to know it all to be free. God sees what we cannot.\"",
 "Lord, the dark is not dark to You. Hold what I cannot hold.", "I do not need perfect memory to tell the truth or to heal.",
 "Do something gentle for your mind: a puzzle, a crossword, a slow walk with no phone.", "Psalm 139:12"),
(19, "Be Kind About What She Had to Do", "Some of what she did to survive still weighs on you. Tell her: \"You did what you had to do to stay alive.\" If someone was hurt, write one living amend you can do (not a confession to them, just an act). Say: \"Jesus came for people like us.\"",
 "Jesus, You came for sinners. Take what she cannot carry and lead us to repair what we can.", "I did what I had to do. I am forgiven, and I can grow.",
 "Do one small, anonymous good deed for someone.", "1 Timothy 1:15"),
(20, "Forgive Her", "You can forgive her, and God already has. At the doorway, say: \"I forgive you for what you had to do.\" If you cannot yet, say: \"I am willing to be willing.\" Then write one sentence of what you will do differently, as her protector.",
 "Father, I take myself out of my own prison. Be the judge, and let it be settled.", "I forgive her, and God has already forgiven me.",
 "Wear or carry something that makes you feel like yourself today.", "Psalm 103:12"),

(21, "Ask Jesus to Come to the Door", "If it feels right, ask Jesus to stand with you at the doorway. This is prayerful imagination anchored in Scripture, not a vision or a memory, and you can skip it. If imagining Him is too hard, simply pray the verse aloud: \"even the darkness is not dark to you.\"",
 "Jesus, I invite You to stand where I stand. Be near her, and near me.", "I do not have to be the only one who is with her.",
 "Pray one sentence aloud at a moment you would normally rush.", "Psalm 139:12"),
(22, "Sort Her Fear", "Take one fear of hers and sort it: is it body (sleep, chemistry), wound (memory), flesh (habit), or something spiritual? Write one small thing for each part. Do not call it demonic first. Treat the body and the wound with care.",
 "Lord, give us discernment instead of panic. Show us what we are really fighting.", "I can tell what kind of thing this is, and I can handle it with help.",
 "Go to bed thirty minutes earlier than usual.", "1 Thessalonians 5:21"),
(23, "Tell Her the Threat Is Over", "If it is true that the danger has passed, tell her: \"That was then. You are safe here.\" Look around the room and name three things that show it is now. If you are still in danger, your first step is safety, not this book. Call 1-800-799-7233 or 911.",
 "Father, show her how safe she is now. Let it sink in.", "That was then. I am safe now, or I am working to be.",
 "Look at the date on your phone and say it out loud, with your age.", "1 John 4:4"),
(24, "Stand Between Her and the Voices", "Imagine the old voices that used to say she was too much or not enough. Stand between her and them as the adult you are. Say to them: \"You do not speak to her anymore.\" You do not need to shout. Say it once, calmly.",
 "Jesus, You stand with me. Silence what should be silent.", "I am her protector now, and I do not have to be loud.",
 "Turn off one source of noise or negativity for the rest of the day.", "Ephesians 6:13"),
(25, "Pray With Her", "Teach her a short prayer, in words a child can say: \"Jesus, help me. I am Yours.\" Say it together. Notice that surrender comes first. Then, if there is something to say no to, say it with Him beside you.",
 "God, I give You my will and my plan. Under Your care, I stand.", "I can say help, and I can say no.",
 "Say your short prayer three times today, once each in the morning, noon, and night.", "James 4:7"),
(26, "Stop Feeding What Scares Her", "Name one thing that keeps feeding her fear: a show, a person's social media, a substance, a habit, a late-night scroll. Remove or limit one thing today. Tell her: \"I will not feed what hurts you.\"",
 "Lord, show me what keeps getting fed. Give me strength to stop feeding it.", "I can decide what I let in.",
 "Take a phone-free hour this evening.", "Ephesians 4:26-27"),
(27, "Put Her Under Cover", "Wrap yourself in a blanket (or hold a pillow) and read Psalm 91:1-2 aloud. As you do, imagine wrapping her in the same cover. Stay for three minutes. This is a comfort practice, not a spell.",
 "Father, You are her refuge. Cover her, and cover me.", "I do not go in uncovered.",
 "Make your bed carefully tonight like you are preparing a room for a child.", "Psalm 91:1-2"),
(28, "Let Her Wait on Forgiveness", "You do not have to force forgiveness today. Ask her: \"Is there anyone you are ready to release?\" If yes, say it. If no, tell her: \"There is no rush. We will do it when you are ready.\" Forgiveness is not trust, and it is not reconciliation.",
 "Lord, free her from carrying this, and do not rush her.", "Forgiveness is mine to give in my time, and it never means going back.",
 "Write one boundary you will keep even after you forgive.", "Colossians 3:13"),
(29, "She Does Not Have to Go Back", "Tell her: \"You do not have to be around people who hurt you.\" Write one safe boundary today: who she will not be left alone with, what she will not answer, where she will not go. Tell a safe person.",
 "God, give me wisdom, not only kindness. Help me guard her well.", "I can forgive and still be safe.",
 "Practice saying \"no, thank you\" out loud to an empty room.", "Proverbs 22:3"),
(30, "Dress Her in Armor", "In the morning, put on the armor out loud with her in mind: truth, righteousness, peace, faith, salvation, the Word, prayer. Picture each piece fitting a child her size. Say: \"You are not built to run. You are built to stand.\"",
 "Father, I put on what You gave me. Keep her upright, and keep us together.", "I stand in Christ, and she stands with me.",
 "Stand tall for thirty seconds, shoulders back, feet apart, and say your armor.", "Ephesians 6:14-17"),
]
