# Ninety Days of Coming Home — days 31–60.

H2 = [
(31, "Find the Paperwork", "List the promises, rules, and beliefs she agreed to without knowing it: \"I will never need anyone,\" \"it is my fault,\" \"I have to be perfect.\" Titles only. Tell her: \"These were survival rules, not who you are.\"",
 "Jesus, You carried the record that stood against her. Show us what to put down.", "What I agreed to in pain does not get the final word.",
 "Move your list to a different room so it is not in your sleeping space.", "Colossians 2:14"),
(32, "Hear the Vow", "At the doorway, ask: \"What promise did you make to stay safe?\" Write it in her exact words. Under it write what it protected her from. Thank her. Do not break it yet.",
 "God, a child made that promise because she had to. Thank You that she lived.", "Her promise protected her, and I honor why she made it.",
 "Do one thing today that is the opposite of her vow, very small (ask for a small favor, show a small feeling).", "Matthew 5:37"),
(33, "Release the Vow With Her", "Say aloud to her: \"I see you. You made that promise because you had to. It worked. I am an adult now and I am taking over. You do not have to hold the door anymore. In Jesus' name I release you from that vow.\" Then say your new sentence three times.",
 "Jesus, welcome her. Come and bring her home.", "I break the old rule and write a new one with God.",
 "Write your new sentence on a card and put it in your pocket.", "Mark 10:14"),
(34, "Words Over Her", "Write the words that were said over her in anger or contempt. Then, beside each, write a blessing in its place. Read the blessings aloud to her. Words can wound and words can bless.",
 "Lord, undo what was said, and speak truth over her.", "I take back every word spoken in pain.",
 "Speak one specific blessing to someone today.", "Ephesians 4:29"),
(35, "Lift the Shame Off Her", "In your imagination (or with a real coat or blanket), take the shame off her shoulders and set it down outside the room. Write on a slip of paper \"shame\" and put it somewhere outside your home, such as a recycling bin. It is a symbol; it does not literally remove anything, but it can help your body practice letting go.",
 "Jesus, You bore shame. Take hers.", "I am not the worst thing that happened to me.",
 "Wear something bright today.", "Psalm 34:5"),
(36, "Break the Silence Gently", "Tell her: \"You are allowed to tell.\" Decide, in writing, who might need to hear what, and when it will be safe. If a child is at risk, protecting them comes first: Childhelp 1-800-422-4453, or 911. You do not have to tell everything today.",
 "Father, You see what was hidden. Give wisdom about when and to whom.", "I am not the keeper of what was done to me.",
 "Say one true thing to a safe person that you normally hide.", "Psalm 32:3"),
(37, "Name What Still Holds Her", "List the names of people who still have a hold on her mind, or write \"the one whose name I do not know.\" Names only, no stories. Tell her: \"We are going to loosen this, slowly.\"",
 "Lord, loosen what is not of You, and give her safe connection.", "I can notice a hold without being stuck in it.",
 "Delete or mute one thing that keeps you attached to someone who hurts you.", "1 Corinthians 6:16-17"),
(38, "Return What Isn't Hers", "Write on paper what you are handing back: their shame, their blame, their version of her. Fold it and put it in an envelope with their name or \"unknown.\" Do not mail it. Say: \"I take back my body, my mind, my peace, my future.\"",
 "Jesus, I release my hold, and I ask You to loosen theirs.", "I hand back what was never mine and take back what was.",
 "Keep the envelope somewhere out of sight, or bury or shred it safely.", "Philippians 3:13-14"),
(39, "What Was She Thirsty For?", "Ask her what she was really thirsty for when she reached for relief: safety, rest, belonging, being seen. Write it. Then give her a small drink of it today in a safe way.",
 "God, You are the fountain. Give her what she was looking for.", "My thirst was real, and God can satisfy it.",
 "Sit with a friend, or call one, for ten minutes just to be together.", "Jeremiah 2:13"),
(40, "Teach Her What Safe Looks Like", "Write a list for her: what a safe person does (is steady, tells the truth, respects no, does not make her afraid). Choose one person who fits it, and one small thing to receive from them.",
 "Lord, teach her what safe love looks like.", "Familiar is not the same as safe.",
 "Notice one calm, safe thing about someone today and tell them.", "1 John 4:18"),
(41, "Let Her Off Guard Duty", "Tell her she does not need to watch the door today. Choose one task to let go of or ask for help with. Practice rest: ten minutes lying down, no problem-solving.",
 "Father, hold what we cannot control.", "I can open my hands. Control was never protection.",
 "Do one thing imperfectly on purpose.", "Matthew 6:27"),
(42, "Love Without Labor", "Do nothing useful for ten minutes with her. No fixing, producing, or serving. Tell her: \"You are loved even when you do nothing.\"",
 "Jesus, let her sit at Your feet without earning it.", "I am loved at rest.",
 "Do something purely for joy: a hobby, a walk, a song.", "Luke 10:41-42"),
(43, "Stop Punishing Her", "Notice one way you punish her: harsh self-talk, denying yourself, staying in what hurts. Replace it with one act of kindness, the kind you would do for a child you love. Tell her: \"You are not on trial.\"",
 "God, the bill is paid. Let her receive it.", "I am not going to keep paying for what Christ already paid.",
 "Cook or buy one thing she would like.", "Romans 8:1"),
(44, "If She Wants to Disappear", "If a part of you wants out, do not argue. Tell her: \"I hear you. I am not leaving you. We are going to get help.\" Then tell a person today. If it is loud, call or text 988 now.",
 "God, feed her, let her sleep, and send someone. Keep us here.", "I choose to stay, and I will tell someone.",
 "Text a safe person: \"Today is heavy. Can you check on me tonight?\"", "1 Kings 19:4-5"),
(45, "Take Back the Pen", "Write one sentence the accuser has said to her. Cross it out. Write over it what God says. Read it to her. She does not have to answer. Just hear it.",
 "Lord, You rebuke the accuser. Clothe her in what is true.", "I do not receive that. I take back the pen.",
 "Rewrite one negative sentence from today into a true one.", "Zechariah 3:2-4"),

(46, "What She Inherited", "Tell her about terrain, not guilt: \"You did not inherit their sin. You inherited a hard place, and we are changing it.\" Write one pattern that ran in your family, and one way you are interrupting it.",
 "Father, I cannot change what I inherited, but I can walk differently.", "I did not inherit guilt. I inherited a terrain I can change.",
 "Do one thing today that is different from how your family would have done it.", "Ezekiel 18:20"),
(47, "Show Her the Good", "Gather the good things in your family: a skill, a joke, a recipe, a person who prayed. Write five. Show them to her. She gets to keep these.",
 "Lord, thank You for every good thing that came down the line.", "There is good in my story, and I get to keep it.",
 "Cook or play something that came from the good side of your family.", "Psalm 78:4"),
(48, "Give Her What She Needed", "Pick one layer (behavior, body, circumstances, faith) and give her what she needed in it: a calm adult, rest, practical help, a prayer. Do one concrete thing today.",
 "God, give her what she did not get, through me and through others.", "I can give her what was missing.",
 "Do one small thing for your health today: a walk, a vitamin, a bedtime.", "Romans 12:2"),
(49, "She Did Not Start It", "Look at one pattern and write: \"This started before me.\" Tell her: \"You did not start this. You are the one who is finally looking at it.\" Hold what you do not know with humility.",
 "Lord, bring light where it helps, and mercy where it does not.", "I am finding where it started, and it did not start with her.",
 "Look up one fact about your family or place that is good.", "Lamentations 5:7"),
(50, "Stand in the Gap for Her", "Pray for your family by name, including yourself: \"Even I and my father's house have sinned.\" You are not taking their guilt; you are agreeing with God and asking mercy. Tell her she is not praying alone.",
 "God, I stand in the gap with You for the people I love.", "I can pray for my family without defending them.",
 "Pray for one family member by name today.", "Nehemiah 1:6"),
(51, "A Prayer for Her Line", "Pray: \"Father, I bring every vow, oath, and harsh word in my family line to the cross of Christ and ask You to cancel its hold. Place her, me, and my family under Your protection.\" Do this once. Date it.",
 "Merciful Father, I bring this to You. Begin with me.", "I trust Jesus to carry what I cannot.",
 "Light a candle while you pray, then blow it out and leave the prayer with God.", "Exodus 34:6"),
(52, "Replace the Words She Heard", "Write the \"we always\" sentences from your family. Cross one out and write a truer one. Teach her the true one.",
 "Lord, put new words in my mouth.", "That was never prophecy. It was a pattern, and it ends.",
 "Say a true sentence aloud in place of a family sentence.", "Proverbs 26:2"),
(53, "Teach Her What Nobody Taught Her", "Name one skill she never got to learn (rest, money, calm, asking). Choose a teacher: a book, a class, a friend. Practice it badly on purpose today, for five minutes.",
 "Father, teach her what she was never shown.", "I am allowed to learn slowly.",
 "Ask someone to teach you one small thing.", "Ephesians 4:23-24"),
(54, "Honor Without Going Back", "Write one honest good thing about each parent or caregiver, if there is one. Write one thing you will not repeat. You can honor without being close or silent.",
 "Lord, show me what honor looks like safely.", "I honor where I came from. I am not repeating it.",
 "Send a safe, kind, short note to someone from your past who was good to you.", "Exodus 20:12"),
(55, "Write Her a Promise", "Write her a promise in one paragraph: \"I will protect you. The line stops here. I will not leave you.\" Sign it. Put it where only you can find it.",
 "God, let it stop here, with You and with me.", "I am the pivot, and I do not have to be perfect.",
 "Read your promise aloud once.", "Joshua 24:15"),

(56, "Notice What Pulls Her Back", "List three patterns that pull her back into old ways (isolation, a coping tool, waiting). Use them to notice, not to label everything an attack. Say: \"I see you. I am not ignorant of this.\"",
 "Lord, give clear eyes, not fear.", "I can read the pattern now.",
 "Do one thing today that breaks one pattern.", "2 Corinthians 2:11"),
(57, "Do Not Leave Her Alone", "Write five roles: someone who knows everything, someone ahead of you, someone behind you, a friend, someone who can correct you. Put a name next to each or leave a blank. Pick one blank to fill.",
 "God, settle the solitary in a home.", "She is not alone, and neither am I.",
 "Reach out to one person you have lost touch with.", "Ecclesiastes 4:9-10"),
(58, "Let Someone Help Her", "Ask a trusted person: \"What is one thing you think I could hear that would help me?\" Listen without defending. Thank them. Tell her: \"We can learn.\"",
 "Lord, make me teachable.", "I would rather be helped than impressive.",
 "Ask for help with one small thing.", "Proverbs 27:17"),
(59, "Stop Making Her Wait", "Give her one small yes today that you have been postponing: an appointment, a call, a class. Put a date on it.",
 "Father, redeem the time, and help me not waste today.", "Not someday. Today has a date on it.",
 "Do the thing you have been putting off for five minutes only.", "Ephesians 5:15-16"),
(60, "Map What Sets Her Off", "Write what sets her off: setting, time of day, body state, the thought, the first action. Circle the earliest link. Write what you will do when you see it.",
 "God, show us the early link.", "I can catch it early.",
 "Set a daily alarm labeled with your early-link action.", "1 Peter 5:8-9"),
]
