# Ninety Days of Coming Home — days 61–90.

H3 = [
(61, "HALT for Her", "Check on her: is she Hungry, Angry, Lonely, or Tired? Feed, rest, call, or calm before you decide anything. Do one right now.",
 "Lord, You give Your beloved sleep.", "I will feed, rest, call, and calm first.",
 "Go to bed on time tonight with the phone out of the room.", "Psalm 127:2"),
(62, "Ride the Wave With Her", "When a craving or urge comes, tell her: \"This is a wave. It will peak and pass.\" Set a timer, change your body, call someone. Write your three phone numbers on a card.",
 "Jesus, I only have to outlast this wave.", "I can outlast a wave. It always breaks.",
 "Practice your wave plan once when you are calm.", "1 Corinthians 10:13"),
(63, "Show Her Tomorrow", "Write a short note to future-you from the worst possible moment: what you would need to read. Keep it where you can find it. Tell her: \"We decide this now, while we can think.\"",
 "God, let me remember what matters when I cannot think.", "I decide this now, while I can still think.",
 "Put your note somewhere you will find it in a hard moment.", "Proverbs 14:12"),
(64, "Give Her Better Comforts", "Make a comfort box for her: five things that soothe without harm (tea, a scent, music, a soft cloth, a card with a verse). Put it where you will reach for it.",
 "Lord, fill the place the old comfort filled.", "I can comfort her in ways that do not cost us.",
 "Use one item from the comfort box today, even if you are okay.", "Isaiah 55:2"),
(65, "Fill Her House With Good", "Add one good thing to your space today: worship music, a plant, a picture, a lit candle, a prayer on the wall. Say: \"This is her home now.\"",
 "Holy Spirit, fill every room that has been emptied.", "I am building a home that is safe and good.",
 "Play a song that makes you feel safe while you tidy one corner.", "Romans 12:21"),
(66, "Give Her a Routine", "Choose three anchors for her day: a wake time, a meal, a bedtime. Write them where you can see them. Be kind when you miss one.",
 "God, You are a God of order. Help me build a day I can stand on.", "I am building walls that hold.",
 "Do your three anchors today and cross them off.", "1 Corinthians 14:40"),
(67, "Put a Fence Around Her", "Set one real boundary today: block a number, say no, change a lock. Write the exact sentence you will use. Tell her: \"I will protect you.\"",
 "Lord, give me a firm yes and a firm no.", "A boundary is a property line, not a punishment.",
 "Say your boundary sentence aloud three times.", "Proverbs 4:23"),
(68, "If She Stumbles", "Write your plan for the day you fall: who you will tell within the hour, where you will go, what you will not do. Tell her: \"If we fall, we get back up. We do not hide.\"",
 "Lord, when I fall, You are my light.", "The identity is in the rising, not in never falling.",
 "Share your plan with one person.", "Micah 7:8"),

(69, "Where Was He?", "If you want, sit at the doorway and ask: \"Where were You, Lord?\" You may sense, imagine, or see nothing, and that is fine. Do not force a scene. You can instead say aloud: \"You are a God of seeing.\" If you are angry, say that too.",
 "God of seeing, show me, gently, how You were there.", "He was in the room. She was never alone in there.",
 "Light a candle and sit quietly with the question for five minutes.", "Genesis 16:13"),
(70, "Let Her Ask Why", "Ask her: \"What do you want to ask God?\" Write her question. Do not answer it. Leave it open. Say: \"We trust His character where we cannot trace His hand.\"",
 "Father, I do not understand. Stay with us.", "I can hold a question without a verdict.",
 "Write one question for God on a card and put it in your Bible.", "Isaiah 49:15"),
(71, "She Was Not Being Punished", "Tell her: \"What happened was not a punishment for who you were.\" Write the sentence you believed, cross it out, and write: \"This was not punishment.\"",
 "Jesus, refuse the lie that suffering is always a sentence.", "I am not being punished. There is no condemnation.",
 "Do one kind thing for someone who is suffering.", "John 9:3"),
(72, "Let Her Be Angry at God", "Give her two minutes to say it all to God, out loud or on paper, unedited. You do not have to fix it. He can handle it.",
 "God, here it is, all of it. I bring it to You instead of holding it against You.", "Anger can be honest prayer.",
 "Take a walk and say it aloud outside.", "Psalm 13:1-2"),
(73, "Let Her Hand Over the Case", "Write her case against those who hurt her. Then write: \"I give this case to God.\" Fold and put it away. You can keep your questions. You are putting down the weight.",
 "Lord, I withdraw the verdict. The case is Yours.", "I keep the questions open and withdraw the verdict.",
 "Take one deep breath and let your shoulders drop three times.", "Romans 12:19"),
(74, "Sit With Her in the Quiet", "Sit two minutes with her in the quiet. Eyes open is fine. If your mind runs, say \"later\" and come back. The coming back is the prayer.",
 "Father, I do not have to say anything. I am not leaving.", "Silence is not rejection.",
 "Eat something and rest ten minutes before praying.", "Lamentations 3:26"),
(75, "Rock Her", "Hold a pillow or soft thing against your chest and rock gently for three minutes while you breathe slowly. Whisper: \"You are not alone. I am here.\" This is comfort, not pressure.",
 "Lord, quiet her soul like a child with its mother.", "I can comfort her the way she needed to be comforted.",
 "Hum a lullaby or a hymn.", "Psalm 131:2"),
(76, "What God Can Use", "Write one thing that was not good, and one thing you ask God not to waste. Tell her: \"It was not good. It will not be wasted.\"",
 "God, I will not call it good, but I ask You not to waste it.", "It was not good. It will not be wasted.",
 "Share something small that you learned with someone.", "Romans 8:28"),

(77, "She Was Not the Savior", "If you lost someone, tell her: \"You were their sister, daughter, friend. You were not their savior.\" Write one thing she did that was love.",
 "God, I loved them, and I was never their God.", "I loved them. I was never their God.",
 "Look at a photo of someone you lost and say one thing you love about them.", "Psalm 147:3"),
(78, "What Wasn't Her Job", "Write who and what contributed to the loss: their choices, the people who hurt them, the systems, the disease, your choices. Count how many lines have her name. Tell her the weight is being redistributed.",
 "Lord, put the weight where it belongs.", "I judge my past self with the resources she had.",
 "Set down something heavy you have been carrying today.", "Psalm 9:9"),
(79, "Hope Without Needing to Know", "Say to her: \"I do not know, and I hope.\" Remember that God judges the heart, and that no one is beyond His love (Romans 8:38-39). Put the one you lost into His hands, and leave them there.",
 "God, You are there, even in Sheol. I put them in Your hands.", "I do not know, and I hope.",
 "Look at the sky for one minute.", "Psalm 139:8"),
(80, "Not a Debt", "Write: \"My life is not a payment.\" Tell her she does not owe anything because she lived. Their name goes on your work as a dedication, not a debt.",
 "Father, free me from owing. Let me carry their name in love.", "My life is not a payment.",
 "Do something joyful in their honor.", "Romans 8:15"),
(81, "Write the Letter", "Write them a letter with everything: love, rage, sorry, what you never said. Then write the case you have been running against yourself, with each count answered. If you can do it safely, burn the second page outside.",
 "Jesus, You wept. Weep with me.", "I am not letting them go. I am putting them down in better hands.",
 "After writing, wash your face and drink water.", "John 11:35"),
(82, "Grief Is Not a Relapse", "Write your hard dates on a calendar with a plan and a person for each. Tell her: \"Missing them is love with nowhere to put itself.\"",
 "Lord, comfort me as You promised.", "I am allowed to grieve, and I am allowed to have a good day.",
 "Have one good, light moment today and do not feel guilty for it.", "Matthew 5:4"),
(83, "Let Go of the Living, Gently", "Ask her about someone living she needs to release or hold at a distance. Choose one: release to God, boundary, distance, or no contact. Write the next step. You can love someone and not be their savior.",
 "Father, You see them. Go where I cannot go.", "Loving someone does not require me to die with them.",
 "Write one boundary or release sentence and say it aloud.", "Jeremiah 31:16-17"),
(84, "Say Goodbye and Hello", "Do a small ritual: write one thing you are saying goodbye to, and one you are saying hello to, on two slips of paper. Put the first in a box and the second where you will see it. Say: \"Out of my hands, into His.\"",
 "God, I release them. Sustain me.", "Out of my hands, into His.",
 "Replace what you released with something good in the space it left.", "Psalm 55:22"),

(85, "Known Before You Were Formed", "Look at her photo or drawing. Say: \"Known and wanted by God before anyone hurt you.\" Write one sentence of how God sees her. The harm does not get the final word.",
 "Father, You knitted her together. Let that be the final word.", "God's knowing came first. The harm does not get the final word.",
 "Look at yourself in the mirror for ten seconds with kindness.", "Psalm 139:13-14"),
(86, "Her Wound Can Become a Door", "Write: \"I am the one who ___ for the people who ___.\" Ask her what she would like to help someone else with one day. Do not rush it.",
 "God of all comfort, comfort me, and let me comfort someone else.", "My wound does not have to stay a wound.",
 "Offer one kind word to someone who is hurting.", "2 Corinthians 1:3-4"),
(87, "Meet the Woman She Is Becoming", "Imagine the future woman walking toward the doorway: how she stands, what she wears, what is in her eyes. Describe her in five lines. Ask her: \"What do you want to tell the girl at the door?\" Write what you hear.",
 "Jesus, let me see who I am becoming, and let it be good.", "She is becoming someone safe, and I get to walk with her.",
 "Dress today like the woman you are becoming.", "John 15:16"),
(88, "A Letter From the New You", "Write a letter from the future woman to the girl: \"I am here now. I am safe. I will not leave you. Here is what I promise.\" Sign it. Then write a short reply from her.",
 "Father, let them know each other.", "I am choosing life, for both of us.",
 "Read your letter aloud to a mirror, or to a friend you trust.", "Deuteronomy 30:19"),
(89, "Bring Her Home", "Walk her in imagination from the doorway into your present room, up to the safe place you built on Day 1. Give her a seat. Then give her something real: a stuffed animal, a plant, a stone, a place at the table. Tell her: \"You live here now, with me.\"",
 "Lord, bring her home, and keep us together.", "She is home, and I am home.",
 "Set a place at your table or put a chair near yours for her.", "Deuteronomy 6:6-7"),
(90, "Meet the New Me", "Sit with three pieces of paper: the letter from her (write it if you have not), the letter from the new you (Day 88), and a promise you sign today. Read them aloud. Say: \"Welcome home. We are a team. We are not finished, and we are not alone.\" Date and sign the last page. Celebrate.",
 "Father, thank You for ninety days. Keep us standing, keep us building, and keep us Yours.", "I am the woman God chose to stand and build, and she is with me.",
 "Do something joyful and celebratory today. Tell someone you finished.", "Nehemiah 4:14"),
]
