R5 = [
(61, "Run the HALT check on yourself: hungry, angry, lonely, tired.",
 "Psalm 127:2 says, “It is in vain that you rise up early and go late to rest, eating the bread of anxious toil; for he gives to his beloved sleep.” Psalm 127 is a song of ascents attributed to Solomon, and it opens with “Unless the LORD builds the house, those who build it labor in vain.” Rest is presented as a gift, not a weakness.",
 ["AVE"], "HALT is a recovery slogan, not a study. But the states it names (hunger, anger, loneliness, tiredness) match the kinds of situations relapse-prevention researchers describe as raising the risk of a lapse. Checking in on your basic needs is a simple, practical defense.",
 ["Ask yourself four questions out loud: Am I hungry? Angry? Lonely? Tired? Say yes or no to each.", "Fix the first yes. Eat something with protein. Drink water. Text someone. Lie down for 20 minutes.", "Write what you will keep in your bag or kitchen so the first one is easy (nuts, a granola bar, water).", "Set one reminder on your phone at your usual low point of the day: “HALT.”", "Say the declaration."],
 "Future Me, I hope you take care of the basics first without thinking about it. Nobody can pray their way out of an empty stomach.",
 "A tired mind makes bad decisions. Rest is a spiritual practice.",
 "Today I choose to meet my basic needs before I fight anything else."),
(62, "Ride one craving wave from start to finish without acting on it.",
 "First Corinthians 10:13 says, “No temptation has overtaken you that is not common to man. God is faithful, and he will not let you be tempted beyond your ability, but with the temptation he will also provide the way of escape, that you may be able to endure it.” Paul is writing to a church in Corinth about Israel’s failures in the wilderness. The promise is that there is a way out, and it comes with the temptation, not after.",
 ["URGE"], "Studies of “urge surfing,” in which people notice a craving rise and fall instead of fighting or obeying it, suggest that cravings tend to peak and pass within a limited time. A mindfulness-based relapse prevention program reduced substance use over time in one large trial. These tools support treatment. They do not replace it.",
 ["When the craving hits, say, “This is a wave.” Set a timer for 10 minutes.", "Notice where you feel it in your body. Rate it from 0 to 10 every two minutes and write the number.", "Breathe in for 4, out for 6, and drink a full glass of water.", "When the timer ends, notice whether the number moved. Write it down.", "Say the declaration. If the craving is dangerous, call someone, go to a meeting, or call 988 or SAMHSA at 1-800-662-4357."],
 "Future Me, I hope you have a whole page of numbers going down. They are proof the wave passes.",
 "A craving is loud, but it is not permanent.",
 "Today I choose to outlast the wave."),
(63, "Play the tape forward and see who else would pay.",
 "Proverbs 14:12 says, “There is a way that seems right to a man, but its end is the way to death.” The verse is repeated word for word in Proverbs 16:25. Proverbs urges people to look at where a path ends, not just how it feels at the start.",
 ["HERSH"], "In studies, people who were shown realistic images of their future selves made choices that favored their future more than people who were not. Seeing the end of the story makes it feel more real.",
 ["Write the choice you are tempted by.", "Write what happens in the first hour, the next day, and the next month if you do it. Be honest and specific.", "Write who else is affected (people, animals, your future).", "Write the other tape: what happens in each of those windows if you do not.", "Say the declaration. Read the second tape out loud."],
 "Future Me, I hope you can see tomorrow clearly enough that tonight is not so loud.",
 "The first minute is persuasive. The tenth minute is honest.",
 "Today I choose to watch the whole tape."),
(64, "Find three better comforts for the same need.",
 "Isaiah 55:2 says, “Why do you spend your money for that which is not bread, and your labor for that which does not satisfy? Listen diligently to me, and eat what is good, and delight yourselves in rich food.” It is part of God’s open invitation to the thirsty to “come, buy and eat” without money. The question is about what satisfies, and it invites real nourishment.",
 ["BA"], "Behavioral activation research suggests that adding even small, rewarding activities can lift mood over time, and that people often do not feel like doing them until after they begin. Replace a coping tool with another coping tool, not with a blank.",
 ["List the three moments you most reach for the old comfort (after work, at night, after conflict).", "Next to each write a replacement that uses a different sense: warm shower, loud song, a walk, cold water, a call, a snack, a candle.", "Put the replacement within reach (in your bag, on your nightstand).", "Use one tonight. Write how you felt after.", "Say the declaration."],
 "Future Me, I hope your comfort kit is worn and well loved.",
 "A comfort is not the enemy. A comfort that costs your life is.",
 "Today I choose comfort that does not charge interest."),
(65, "Fill one space in your home or day with something good.",
 "Romans 12:21 says, “Do not be overcome by evil, but overcome evil with good.” Paul has just told believers not to repay evil for evil and to live peaceably as far as it depends on them. The verse is practical: overcome by doing good, not just by avoiding the bad.",
 ["BA"], "Research on behavioral activation and on environment design suggests that filling empty time and space with planned, meaningful activity makes old habits less automatic. Empty time is risky time.",
 ["Pick one empty block of time (for example, Friday at 8 p.m.).", "Pick one good thing to put in it: a meeting, a class, a call, a walk, a craft, church, volunteering.", "Pick one thing in your home to change (remove something, add something: a candle, a verse, a photo of Big Boy, plants).", "Do the home change today.", "Say the declaration."],
 "Future Me, I hope there are no empty hours that scare you anymore.",
 "Good does not get in only by pushing the bad out. Fill the room.",
 "Today I choose to fill my time on purpose."),
(66, "Build a small daily structure that you can keep when you are tired.",
 "First Corinthians 14:40 says, “But all things should be done decently and in order.” Paul is giving instructions for worship in Corinth, where meetings had become chaotic. Applied to daily life, it supports building routines. That is an application of the principle, not what the verse is directly about.",
 ["WOOD"], "Habit research suggests that routines tied to a consistent place and time become more automatic, so they depend less on motivation. This is why the same wake-up, meal, and wind-down times can steady a hard season.",
 ["Write a simple morning routine with only three steps (for example: water, pray two minutes, make bed).", "Write an evening routine with three steps (for example: dishes, shower, lights low).", "Put both on a card on your fridge or mirror.", "Do the morning routine tomorrow, even if you do not feel like it.", "Say the declaration."],
 "Future Me, I hope the routine is so ordinary now that you only notice it on the days it is missing.",
 "Structure is a kindness to the tired version of you.",
 "Today I choose a routine I can keep on a bad day."),
(67, "Draw one boundary with family, with her, or with him.",
 "Proverbs 4:23 says, “Keep your heart with all vigilance, for from it flow the springs of life.” It is part of a father’s advice to his son about wisdom. Guarding the heart is described as an act of care for the source of your life, not as coldness.",
 ["BAND"], "Self-efficacy research suggests that taking small, successful actions builds confidence for larger ones. Setting and keeping a small boundary makes the next one easier.",
 ["Write one boundary you need: “I will not ______.” “I will ______ instead.”", "Write the exact words you will say: “I can’t talk about that. I’m going to go now.”", "Practice saying it aloud twice.", "Write what you will do if the person pushes back.", "Say the declaration."],
 "Future Me, I hope boundaries feel like fences around a garden and not walls around a prison.",
 "A boundary is not a punishment. It is a way to love people from where you are safe.",
 "Today I choose a fence."),
(68, "Plan what you will do if you stumble, before you stumble.",
 "Micah 7:8 says, “Rejoice not over me, O my enemy; when I fall, I shall rise; when I sit in darkness, the LORD will be a light to me.” Micah is speaking for a people who have fallen and are waiting for God to act. The verse does not say “if I never fall.” It says “when I fall, I shall rise.”",
 ["AVE"], "Relapse-prevention researchers describe the “abstinence violation effect,” where a lapse leads to shame and the thought “I have blown it,” which can lead to continued use. Planning ahead to treat a lapse as a signal instead of a verdict helps.",
 ["Write the plan: “If I slip, I will call ______ within one hour.”", "Write the first three things you will do (call, leave, eat, tell, go to a meeting).", "Write a sentence to say to yourself instead of “I blew it”: “This is a lapse, not a life sentence.”", "Tell the person on your plan that they are on it.", "Say the declaration."],
 "Future Me, if you have ever used that plan, I am proud of you for using it. If you have not needed it, I am glad.",
 "A slip is not the same as a collapse. What you do next is what counts.",
 "Today I choose a way back before I need it."),
(69, "Ask the question out loud: where were you?",
 "In Genesis 16 Hagar, a mistreated servant, runs into the wilderness, and the angel of the LORD finds her. She names God, “You are a God of seeing,” and says, “Truly here I have seen him who looks after me.” She is the only person in Scripture to give God a name in this way. The story does not explain her suffering. It shows that God sees her.",
 ["PEN"], "Writing honestly about painful questions, including spiritual ones, is associated in studies with modest benefits for many people. You do not need an answer to benefit from asking.",
 ["Write the question as plainly as you can: “God, where were you when ______?”", "Write what you feel when you ask it (anger, fear, numbness, hope).", "Read Genesis 16:7–14. Notice who sought whom.", "Write one sentence of what you want from God now, even if it is “I don’t know.”", "Say the declaration. It is okay to leave the question open."],
 "Future Me, I hope the question has become a conversation. If it is still open, God can hold it.",
 "God can handle the question. He has heard it before.",
 "Today I choose honesty with God."),
(70, "Let the “why didn’t he stop it” question be asked without a tidy answer.",
 "Isaiah 49:15 says, “Can a woman forget her nursing child, that she should have no compassion on the son of her womb? Even these may forget, yet I will not forget you.” Isaiah is speaking to Zion, who had said, “The LORD has forsaken me.” God does not argue with the feeling. He says even the most unlikely forgetting will not happen to him.",
 ["PEN"], "Studies of expressive writing show that people often benefit from wrestling with painful questions on paper over several days, even without resolving them. Lament has always been a way to bring pain to God.",
 ["Write the question: “Why didn’t you stop it?” Write it three times if you need to.", "Write what you would say if he answered. Then write what you fear he would say.", "Read Isaiah 49:15 aloud once.", "Write one thing you know about God’s character from Scripture that you are not sure you believe right now.", "Say the declaration."],
 "Future Me, I hope you found some peace with not knowing. Some questions are lived into, not answered.",
 "A good question is not a lack of faith. It is faith wrestling.",
 "Today I choose to ask without pretending."),
(71, "Separate what happened from the idea that you were being punished.",
 "In John 9:1–3 the disciples ask about a man born blind, “Rabbi, who sinned, this man or his parents, that he was born blind?” Jesus answers, “It was not that this man sinned, or his parents, but that the works of God might be displayed in him.” Jesus rejects the assumption that suffering is a direct punishment for a particular sin.",
 ["SHAME"], "Research on shame suggests that blaming yourself for harm done to you increases hiding and distress. Reframing responsibility accurately can reduce the weight.",
 ["Write: “I was afraid that what happened was punishment for ______.”", "Write the facts: who did what, and who was responsible.", "Write the sentence “It was not my fault” and the sentence “It was not God’s punishment.”", "Read John 9:1–3 aloud.", "Say the declaration."],
 "Future Me, I hope you no longer look for the reason in yourself.",
 "God is not punishing you. People were not safe, and that was theirs to answer for.",
 "Today I choose to stop looking for a reason in myself."),
(72, "Be angry at God out loud, with the psalms to lead.",
 "Psalm 13:1–2 says, “How long, O LORD? Will you forget me forever? How long will you hide your face from me? How long must I take counsel in my soul and have sorrow in my heart all the day?” It is a short psalm of David. It begins in complaint and ends in trust (“I will sing to the LORD”). About a third of the psalms are laments, which means God’s own book gives you permission to be honest.",
 ["PEN"], "Writing about strong negative feelings, including anger, is linked in studies to improved well-being for many people when it moves toward meaning-making over time. Expression alone helps most when it leads somewhere.",
 ["Write your own psalm: “How long, Lord? ______.” Do not clean it up.", "Write what you are angry about. Use hard words.", "Write one line of what you still believe, even a small one.", "Read all three aloud, as prayer.", "Say the declaration."],
 "Future Me, I hope your relationship with God has room for your anger now. It is a deeper kind of trust.",
 "Anger at God is still a conversation with God.",
 "Today I choose honesty over politeness."),
(73, "Hand one case over to the only fair judge.",
 "Romans 12:19 says, “Beloved, never avenge yourselves, but leave it to the wrath of God, for it is written, ‘Vengeance is mine, I will repay, says the Lord.’” Paul is quoting Deuteronomy 32:35. The command is not “do nothing” in cases of abuse. Elsewhere Scripture calls on authorities to punish wrongdoing (Romans 13:4). It says personal revenge is not yours to carry out.",
 ["WADE"], "Studies of forgiveness programs find that people who release the desire for revenge, with support, generally report less distress. Releasing revenge does not mean the harm did not matter or that it was not a crime.",
 ["Write the name of the person and what they did, in one factual line.", "Write what justice would look like to you (an apology, a consequence, an acknowledgment).", "Decide whether any of it is something you can pursue legally or safely (a report, a restraining order, therapy). Write the next step.", "Pray: “God, I put this case in your hands. I will do what is mine to do.”", "Say the declaration."],
 "Future Me, I hope you feel lighter. Carrying a case is heavy work.",
 "Releasing revenge is not the same as dropping the charges.",
 "Today I choose to hand over the gavel."),
(74, "Sit with a quiet stretch of faith without forcing a feeling.",
 "Lamentations 3:26 says, “It is good that one should wait quietly for the salvation of the LORD.” It sits in the middle of a poem written after the fall of Jerusalem. The author has just said, “The steadfast love of the LORD never ceases,” in the midst of grief. Quiet waiting is described as good, not as failure.",
 ["BRAT"], "In one study, people who walked for 90 minutes in a natural setting showed less rumination than people who walked in an urban setting. Time in quiet, green places can help a busy mind settle.",
 ["Go outside, or sit by a window. Set a timer for 10 minutes.", "No phone. Look at one thing, like a tree or the sky.", "Whenever your mind runs, say “Waiting,” and look again.", "At the end, write one sentence about what you noticed.", "Say the declaration."],
 "Future Me, I hope quiet has become something you look forward to, not something you run from.",
 "Quiet is not empty. It is where things settle.",
 "Today I choose to wait without a plan."),
(75, "Let yourself be quieted, like a weaned child with its mother.",
 "Psalm 131:2 says, “But I have calmed and quieted my soul, like a weaned child with its mother; like a weaned child is my soul within me.” It is a three-verse psalm of ascent attributed to David. A weaned child is not crying for milk. It simply rests. The psalmist says he has chosen not to occupy himself with things too great for him.",
 ["BREATH", "BEETZ"], "Slow breathing and gentle contact, like petting a calm animal, have both been associated with calmer physiology in studies. Neither is a cure, and both are easy to try.",
 ["Sit or lie down with something soft, or your dog beside you.", "Breathe in for 4 and out for 6, ten times.", "Place a hand on your chest and say, “My soul is quiet. I am not in charge of everything.”", "Rest for three minutes without doing anything.", "Say the declaration."],
 "Future Me, I hope your soul can quiet itself quickly now. I hope you remember how it felt today.",
 "You are allowed to rest like a child who is not afraid.",
 "Today I choose to be quiet and held."),
]
