R6 = [
(76, "Look at “all things work together” honestly, without calling the harm good.",
 "Romans 8:28 says, “And we know that for those who love God all things work together for good, for those who are called according to his purpose.” Paul does not say all things are good. He says God works in all things, for the good of those who love him, inside a chapter that also names suffering, groaning, and waiting. Verse 29 shows the “good” as becoming like Jesus.",
 ["KING"], "Studies of post-traumatic growth suggest that some people report meaning and growth after trauma, and that this tends to come with, not instead of, distress. It is not required, and it is not guaranteed. In life-goal writing studies, making meaning was linked to better well-being.",
 ["Write: “What happened to me was not good. It was ______.” Use real words.", "Write one thing God has brought you that you would not trade (a person, a lesson, a strength).", "Write: “I do not need to call the pain good to believe God is good.”", "Read Romans 8:26–28 aloud.", "Say the declaration."],
 "Future Me, I hope that you can hold both: it was terrible, and God was at work. Neither cancels the other.",
 "God using something is not the same as God causing it.",
 "Today I choose to be honest about the harm and the help."),
(77, "Put down the job of being everyone’s savior.",
 "Psalm 147:3 says, “He heals the brokenhearted and binds up their wounds.” The psalm is a song of praise that celebrates God for rebuilding Jerusalem, gathering the outcasts, and healing. Healing is described as his work, not yours. The verse is a relief, not a charge.",
 [], "Al-Anon (al-anon.org) and similar family groups exist for people affected by someone else’s drinking or drug use. They teach that you did not cause it, cannot control it, and cannot cure it, and many people find that freeing. Support groups are free.",
 ["Write the name of someone you tried to save. Write what you did to try.", "Write what actually happened. Be honest.", "Say aloud: “I did not cause it. I could not control it. I could not cure it.”", "Look up one family support meeting (Al-Anon, Nar-Anon, or another group) and note the time.", "Say the declaration."],
 "Future Me, I hope you have learned to love without rescuing.",
 "You can love someone fully and still not be able to save them.",
 "Today I choose to love without carrying."),
(78, "Sort what was your job and what never was.",
 "Psalm 9:9 says, “The LORD is a stronghold for the oppressed, a stronghold in times of trouble.” David praises God as the one who judges rightly and remembers the afflicted. The verse puts responsibility for justice in God’s hands, not in the hands of the victim.",
 ["ACE"], "Research on adverse childhood experiences makes the point that children are not responsible for the adversity they experience. Accurately assigning responsibility is part of healing.",
 ["Make two columns: “Not my job” and “My job.”", "Under “Not my job” list what you were made responsible for as a child (adults’ feelings, safety, secrets, fixing).", "Under “My job” list what is yours now (my choices, my recovery, my relationships, my peace).", "Cross out one thing from your “Not my job” list that you still try to carry. Say, “I am putting this down.”", "Say the declaration."],
 "Future Me, I hope you know whose job is whose.",
 "A child cannot do an adult’s job. You were a child.",
 "Today I choose to carry only what is mine."),
(79, "Practice hope without needing certainty.",
 "Psalm 139:8 says, “If I ascend to heaven, you are there! If I make my bed in Sheol, you are there!” Sheol is the place of the dead in Hebrew thought. The psalm says there is no place so far that God is not present. It is a statement of presence, not a prediction about outcomes.",
 ["KING"], "Writing about a hopeful but realistic future has been linked to better well-being in studies, and works best when paired with concrete steps. Hope is not a guarantee, and it is not a denial of how things are.",
 ["Write one thing you do not know and cannot know about your future.", "Write one thing you do know about God’s presence from Psalm 139.", "Write one hope you have for next year, in plain words, and one step toward it.", "Say, “I do not need to know how it ends to take the next step.”", "Say the declaration."],
 "Future Me, I hope some of those hopes came true. I hope the ones that did not did not break you.",
 "Hope is not certainty. It is choosing to walk toward light.",
 "Today I choose to hope without proof."),
(80, "Receive a place in the family that is not earned.",
 "Romans 8:15 says, “For you did not receive the spirit of slavery to fall back into fear, but you have received the Spirit of adoption as sons, by whom we cry, ‘Abba! Father!’” Paul uses adoption language. In Roman culture an adopted son had the same legal rights as a natural child. The verse is about belonging, not debt.",
 ["ROIS"], "Attachment research suggests that people who did not feel secure as children can come to feel more secure through steady relationships later, including with God, mentors, and community, although the evidence on religious attachment is still developing.",
 ["Write: “I used to think I had to earn a place by ______.”", "Write: “In God’s family I am a child, not a servant.”", "Name one place or person where you already feel you belong.", "Do one small thing to belong more: go to a service, a group, or a meeting.", "Say the declaration."],
 "Future Me, I hope you are finding seats at tables without fear.",
 "Adoption is a legal and a loving thing. You were chosen.",
 "Today I choose to be a daughter, not a debtor."),
(81, "Write the letter, to her, to him, and to Brandi, and do not mail it.",
 "John 11:35 is the shortest verse in the Bible: “Jesus wept.” It comes at the tomb of his friend Lazarus, though Jesus was about to raise him. Even knowing how the story would turn, he cried. Grief is not a lack of faith.",
 ["PEN"], "Letters you never send, a form of expressive writing, have been used in grief and trauma work and are linked in studies to emotional processing. They are most helpful when you can stop and care for yourself afterward.",
 ["Pick one: a letter to the child you were, to the person who hurt you, or to Brandi Renee. Write the date at the top.", "Write for 15 minutes without stopping. Begin with “I need you to know.”", "End with one sentence of what you want to say goodbye to, or thank, or forgive.", "Read it aloud only if you feel steady. Then put it away. Do not mail it.", "Say the declaration. Do something kind for yourself afterward."],
 "Future Me, I hope you kept that letter or burned it, and that it did what you needed.",
 "Some things need to be said even if nobody ever hears them.",
 "Today I choose to say what has been waiting."),
(82, "Remember that grief is not a relapse.",
 "Matthew 5:4 says, “Blessed are those who mourn, for they shall be comforted.” It is the second Beatitude, in the Sermon on the Mount. Jesus names mourning as a blessed state, because those who mourn will be met with comfort. Grief is not treated as something to hide.",
 ["BONN"], "Research on bereavement suggests people grieve in many different ways and that the most common outcome is resilience, though grief can be intense and can come in waves. Grief waves are normal, and prolonged or overwhelming grief deserves professional help.",
 ["Write her name and dates: Brandi Renee, January 27, 1986 to December 17, 2021. Or write the name and dates of someone you have lost.", "Write one thing you miss and one thing you are glad you had.", "Light a candle or hold something of theirs for two minutes. Cry if you need to.", "Write: “Grief is love with nowhere to go.” Then write one place to send it today (a walk, a prayer, a kind act).", "Say the declaration. If grief tips toward using or self-harm, call someone or 988."],
 "Future Me, I hope the grief has softened into a place you can visit.",
 "Grief does not mean you are failing. It means you loved.",
 "Today I choose to let grief be grief."),
(83, "Practice gentle distance if the person is still living.",
 "Luke 5:16 says, “But he would withdraw to desolate places and pray.” Jesus, surrounded by crowds who needed healing, regularly stepped away. It is permission to have limits and to prioritize time with the Father.",
 ["NEFF"], "Self-compassion research suggests that treating your own needs as valid lowers burnout and shame. Taking space is not selfish, and it can make your care more sustainable.",
 ["Write the person you need distance from or from whom you want more space.", "Write what you will do with the space (pray, rest, recover).", "Write one gentle sentence you can say: “I love you, and I need space right now.”", "Decide the first small step (a shorter call, a later reply, a limit on visits).", "Say the declaration."],
 "Future Me, I hope you give love from a healthy distance. It is okay to love and keep your boundaries.",
 "Even Jesus withdrew.",
 "Today I choose to love with limits."),
(84, "Release what you cannot carry.",
 "Psalm 55:22 says, “Cast your burden on the LORD, and he will sustain you; he will never permit the righteous to be moved.” David wrote this in distress over betrayal by a close friend. “Cast” is a physical word, like throwing something off your back. The promise is that God sustains, not that the burden vanishes instantly.",
 ["LIEB"], "Naming heavy feelings in words has been linked to reduced intensity of emotional reactions in lab studies. Naming each burden before you hand it over can make the handing-over more real.",
 ["Write three burdens you are still carrying, in a line each.", "Next to each write: “I cannot fix this.”", "Hold a heavy object (a book, a bag of rice). Say, “I cast this on you, Lord.” Put it down.", "Notice the lightness in your hands. Take three breaths.", "Say the declaration."],
 "Future Me, I hope your hands are free.",
 "You were not made to carry everything.",
 "Today I choose to put the weight down."),
(85, "Believe that you were known and wanted before you were hurt.",
 "Psalm 139:13–14 says, “For you formed my inward parts; you knitted me together in my mother’s womb. I praise you, for I am fearfully and wonderfully made. Wonderful are your works; my soul knows it very well.” David wrote this as a song of praise. The verse says that God was involved in your making, no matter what the circumstances of your birth or your parents’ choices were.",
 ["NEFF"], "Studies on self-compassion suggest that seeing yourself as worthy of care, not because of achievement, is linked to better emotional health. Worth is not something you have to prove.",
 ["Write: “Before anything happened, God made me. He saw me as ______.”", "Write three things about yourself that you like or that make you you (your laugh, your grit, your love for animals).", "Look in the mirror and say, “I am fearfully and wonderfully made,” once.", "Write one thing you would like to say to the child who was hurt: “You were wanted by God.”", "Say the declaration."],
 "Future Me, I hope you believe it, and I hope others see it.",
 "What was done to you does not undo how you were made.",
 "Today I choose to see what God sees."),
(86, "Notice that your wound can become a door for someone else.",
 "Second Corinthians 1:3–4 says, “Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort, who comforts us in all our affliction, so that we may be able to comfort those who are in any affliction, with the comfort with which we ourselves are comforted by God.” Paul wrote it after severe hardship in Asia. Comfort is received so it can be passed on. It does not say your pain was good, only that it can be used.",
 ["PAGANO"], "In a study of people in alcohol recovery, those who helped other people in Alcoholics Anonymous were more likely to stay sober over the following year than those who did not. Helping from a place of stability seems to benefit the helper as well.",
 ["Write one lesson from your journey that someone else could use.", "Write who might need it (a newcomer in a meeting, a friend, a younger woman).", "Write one safe way to share it (a text, a meeting share, a card).", "Only share what is stable and healed enough for you. You are not required to reopen anything.", "Say the declaration."],
 "Future Me, I hope someone told you your story helped them. You are not a project. You are a person who can offer comfort.",
 "You do not have to be healed to help. You just need to be honest and safe.",
 "Today I choose to offer comfort from where I am."),
(87, "Meet the woman you are becoming and say hello.",
 "John 15:16 says, “You did not choose me, but I chose you and appointed you that you should go and bear fruit and that your fruit should abide, so that whatever you ask the Father in my name, he may give it to you.” Jesus says this to the disciples at the Last Supper, in the passage about the vine and the branches. “Appointed” and “bear fruit” mean you are chosen for something, but the fruit comes from staying connected to him.",
 ["BAND"], "Self-efficacy research suggests that imagining and practicing the person you want to be, then taking small steps that match, builds confidence over time. Identity is built by actions.",
 ["Write a description of the woman you are becoming in five lines (how she wakes up, speaks, rests, loves).", "Write one thing she does that you already do.", "Write one thing she does that you will do this week.", "Say, “Hello, ______. I see you.” (Use her name or a nickname.)", "Say the declaration."],
 "Future Me, I hope we are good friends by now.",
 "You are not becoming someone else. You are becoming who you were made to be.",
 "Today I choose to act like her."),
(88, "Choose between carrying it on and ending it here, and write the choice.",
 "Deuteronomy 30:19 says, “I call heaven and earth to witness against you today, that I have set before you life and death, blessing and curse. Therefore choose life, that you and your offspring may live.” Moses is speaking to Israel at the end of his life. The choice is repeated, and it is presented as real, with help from God (v. 20).",
 ["GOLL"], "Specific, written plans are linked to higher follow-through. A choice you have written and told someone about is more likely to hold.",
 ["Write: “Carrying it on looks like ______.”", "Write: “Ending it here looks like ______.” Be specific.", "Write three actions you will take in the next thirty days that fit the second.", "Tell one safe person your three actions.", "Say the declaration."],
 "Future Me, I hope your thirty days turned into ninety, then more.",
 "Choosing is not one big moment. It is many small ones.",
 "Today I choose life, and I will show it in my calendar."),
(89, "Plan what you will pass on without having children.",
 "Second Timothy 1:5 says, “I am reminded of your sincere faith, a faith that dwelt first in your grandmother Lois and your mother Eunice and now, I am sure, dwells in you as well.” Paul writes to Timothy, his spiritual son. Faith was passed through relationship. Paul himself had no biological children and passed faith on through discipleship.",
 ["HERSH"], "Studies on “future self continuity” suggest that feeling connected to your future self helps with long-term choices. Legacy is a way of caring for the people who will come after you, including your future self.",
 ["Write who you could pass something on to (a niece, a mentee, a younger friend, a neighbor, a newcomer in recovery).", "Write what you want to pass on (a recipe, a skill, a verse, a boundary, a way to ask for help).", "Write one small act this month (a coffee, a card, a call).", "Do it or schedule it.", "Say the declaration."],
 "Future Me, I hope somebody carries something good because of you.",
 "Legacy is not only blood. It is who you invest in.",
 "Today I choose to pass on something good."),
(90, "Close the ninety days by commissioning yourself, honestly and with a next step.",
 "Nehemiah 4:14 says, “And I looked and arose and said to the nobles and to the officials and to the rest of the people, ‘Do not be afraid of them. Remember the Lord, who is great and awesome, and fight for your brothers, your sons, your daughters, your wives, and your homes.’” Nehemiah is rebuilding the wall of Jerusalem under threat. The people worked with a tool in one hand and a weapon in the other, and they finished.",
 ["LALLY", "KING"], "Habit research suggests new behaviors can take around two months or more to become automatic, and that missing days does not undo progress. Writing about your future in a realistic way is associated with better well-being.",
 ["Look back through your ninety days. Write three things that changed.", "Write one practice you will keep (morning armor, craving surfing, HALT, a daily call, a meeting).", "Write one thing you will do in the next thirty days to build on this.", "Write a short commission to yourself: “I am ______. I am here to ______.”", "Say the declaration. Tell one person what you finished."],
 "Future Me, you finished. Whatever comes next, remember that you did this. You survived. Now we rebuild.",
 "Ninety days is not the end. It is a foundation.",
 "Today I choose to keep building."),
]
