R2 = [
(16, "Understand why you went back, without calling yourself stupid.",
 "In Luke 22:31–32 Jesus tells Peter at the Last Supper, “Simon, Simon, behold, Satan demanded to have you, that he might sift you like wheat, but I have prayed for you that your faith may not fail. And when you have turned again, strengthen your brothers.” Jesus says “when,” not “if,” and he knows Peter is about to fail. He prays for him ahead of time and gives him a future.",
 ["PROCH"], "Researchers who study how people change describe it as a loop with relapses, not a straight line. Many people who eventually change a deep habit go through the cycle several times. It does not make the attempts worthless.",
 ["Write the last time you went back (to a person, a place, a substance, a belief). Just the facts, in one sentence.", "Write what you were hoping to get. Common answers: comfort, belonging, numbness, being chosen.", "Write what it actually cost you.", "Write one need you could meet a different way this week.", "Say the declaration. Say, “I am turning again.”"],
 "Future Me, I hope you can say “turned again” without shame now. Peter did. So did every person God has ever used.",
 "Going back is information. It tells you what you were reaching for.",
 "Today I choose to learn from the return trip."),
(17, "Let yourself miss the people who hurt you, without going back to them.",
 "Psalm 107 is a song of thanks for God’s rescue of people in different kinds of trouble: wanderers, prisoners, the sick, sailors in storms. Verse 9 says, “For he satisfies the longing soul, and the hungry soul he fills with good things.” The refrain, “Let them thank the LORD for his steadfast love,” returns after each rescue. Longing is treated as real and God as the one who meets it.",
 ["LIEB"], "Putting a mixed feeling into words (“I miss him and I am angry at him”) is linked to lower emotional intensity in lab studies of affect labeling. Mixed feelings are normal after harm, and they do not mean you should return.",
 ["Write two sentences: “I miss ______ because ______.” and “I do not miss ______ because ______.”", "Say both aloud. Notice that you can feel both without choosing one.", "Write one thing that satisfied you today that did not involve them (food, music, sunshine, a laugh).", "If the longing gets very loud, text a safe person: “I’m missing something I shouldn’t go back to.”", "Say the declaration."],
 "Future Me, I hope the missing has softened. If it has not, you still got through it again this time.",
 "Missing someone is not the same as needing them.",
 "Today I choose to honor the longing without obeying it."),
(18, "Make peace with the gaps in your memory.",
 "Psalm 139:12 says, “even the darkness is not dark to you; the night is bright as the day, for darkness is as light with you.” The whole psalm is David’s meditation on being known by God from before birth. The verse does not say you must remember. It says nothing is hidden from him.",
 ["SIEG"], "Dan Siegel’s “window of tolerance” describes the zone where a person can feel and think at the same time. Many trauma-informed therapists work on widening that window in the present rather than pressing for memories. It is one model among several.",
 ["Write: “What I know for sure about my early life is ______.” Two or three lines.", "Write: “What I don’t know, and may never know, is ______.”", "Say, “I do not have to remember to heal.”", "Put a hand on your chest. Take five slow breaths.", "Say the declaration. Do not go looking for anything today."],
 "Future Me, I hope you stopped treating the missing pieces like a debt you owe. You are allowed to build a life on what you have.",
 "You do not need a complete file to be a whole person.",
 "Today I choose present safety over past evidence."),
(19, "Name what you did to survive, without lying and without self-hatred.",
 "In 1 Timothy 1:15 Paul writes to Timothy in Ephesus, “The saying is trustworthy and deserving of full acceptance, that Christ Jesus came into the world to save sinners, of whom I am the foremost.” Paul says this about a man who had persecuted the church. He names what he did and builds his life on grace anyway.",
 ["SHAME"], "Studies of shame and guilt in people with substance problems have found that shame-prone people tend to do worse over time, while guilt (“I did something wrong, and I want to repair it”) is linked to better outcomes. How we name what we did matters.",
 ["List three things you did to survive that you do not like. One line each.", "Next to each write what you were protecting yourself from.", "Mark each with “Own it” (needs repair) or “Understand it” (it was survival).", "For any “Own it,” write one small repair, such as an apology you can send or an amends you can plan.", "Say the declaration."],
 "Future Me, I hope you can read that list with kindness and accuracy. Some of those things were survival. Some need repair. Both can be true.",
 "Understanding is not excusing, and excusing is not required for understanding.",
 "Today I choose honesty without cruelty."),
(20, "Plan one living amends and one act of self-forgiveness.",
 "Proverbs 28:13 says, “Whoever conceals his transgressions will not prosper, but he who confesses and forsakes them will obtain mercy.” It sits in a section the book itself says was copied by the men of Hezekiah (Proverbs 25:1). Notice the two verbs: confess and forsake. Mercy follows both.",
 ["WADE"], "A meta-analysis of forgiveness programs found that people who took part reported more forgiveness and less distress than people who did not. Forgiving someone is not the same as reconciling with them.",
 ["Write the name of someone you owe an amends. If it is not safe to contact them, write what you would do instead (a letter you do not send, a changed behavior).", "Write one sentence of the amends: “I am sorry for ______. I will ______ from now on.”", "Write one thing you need to forgive yourself for. Say, “I release myself from carrying this alone.”", "Pick a day this week to act. Put it on the calendar.", "Say the declaration."],
 "Future Me, I hope you followed through. Amends are lived, not just said.",
 "Forgiveness is a decision. Trust is rebuilt. They are not the same thing.",
 "Today I choose repair over replay."),
(21, "Practice holding two realities: what you see, and what you cannot.",
 "In 2 Corinthians 4:16–18 Paul writes that “we do not lose heart,” and that “as we look not to the things that are seen but to the things that are unseen. For the things that are seen are transient, but the things that are unseen are eternal.” He is writing from deep affliction. The unseen realm is described as real and lasting, not as a place to hunt for threats.",
 ["RUM"], "Research on rumination suggests that repetitive worry about causes and meanings tends to deepen distress and does not solve the problem. A deliberate shift to a concrete action or to something you can see and touch is often more useful.",
 ["Write: “Things I can see and touch right now: ______.” Name five.", "Write: “Things I believe are true but cannot see: ______.” Name two or three, such as God’s presence, that I am forgiven, that this will end.", "Say, “Both are real. I will not chase the unseen to prove it.”", "Do one tangible, ordinary thing (wash a dish, fold a towel) as an act of faith in the visible world.", "Say the declaration."],
 "Future Me, I hope your faith has room for both the seen and the unseen without making you jumpy. Peace is a sign of presence, not proof of absence.",
 "You can believe in an unseen realm without searching every shadow for it.",
 "Today I choose attention over alarm."),
(22, "Sort what scares you into four plain categories.",
 "First Thessalonians 5:21 says, “but test everything; hold fast what is good.” Paul is closing a letter to a young church in Thessalonica and has just said, “Do not despise prophecies” (v. 20). The instruction is to evaluate carefully, not to believe everything and not to dismiss everything.",
 ["GROSS"], "Cognitive reappraisal, which means looking at a situation again and asking what else could explain it, has been associated with healthier emotion outcomes than suppressing the feeling. Sorting is a form of reappraisal.",
 ["Write the thing that scares you at night in one line.", "Check one: Is it (1) a body/medical thing, (2) a memory or trauma response, (3) a real-world danger, or (4) a spiritual concern I should pray and test?", "Match it to a next step: doctor, grounding and a counselor, a safety plan, or prayer and a trusted pastor.", "Write the next step and when you will do it.", "Say the declaration."],
 "Future Me, I hope you learned that not every scare is spiritual and not every scare is only physical. Sorting is wisdom.",
 "Not everything that feels like an attack is an attack. Not everything that feels like nothing is nothing.",
 "Today I choose to test before I label."),
(23, "Say what the enemy cannot do, using only what Scripture says.",
 "First John 4:4 says, “Little children, you are from God and have overcome them, for he who is in you is greater than he who is in the world.” John is writing to believers about false teachers and about testing spirits (4:1). The “greater” is the Spirit of God in the believer. The verse is not about us being powerful. It is about him.",
 ["BAND"], "Albert Bandura’s work on self-efficacy suggests that people who believe they can handle a challenge, often because they have handled smaller ones, are more likely to try again after setbacks. Believing you can does not guarantee you will.",
 ["Write: “Three things I have already survived that I once thought I could not: ______.”", "Write the verse in your own words: “The One in me is greater than ______.”", "Say it standing up, out loud, once.", "Write one small hard thing you will do today to prove you can.", "Say the declaration."],
 "Future Me, remember today. You were not strong because you never wavered. You were strong because he was with you when you did.",
 "Your authority is borrowed, and the loan is good.",
 "Today I choose to stand on what is promised, not on how I feel."),
(24, "Practice standing: feet down, breath slow, words true.",
 "Ephesians 6:13 says, “Therefore take up the whole armor of God, that you may be able to withstand in the evil day, and having done all, to stand firm.” The armor imagery likely echoes what Paul saw on the Roman soldiers guarding him. Notice the goal: stand firm. The armor is mostly defense, and every piece is something God provides.",
 ["BREATH"], "Slow, controlled breathing is associated with a calmer heart rate and with a sense of steadiness in many studies, though results vary. It is a tool, not a cure.",
 ["Stand with your feet hip-width. Press them into the floor.", "Breathe in for 4, out for 6, five times.", "Say out loud: “I stand on what is true. I do not have to run.”", "Name one thing in your day today that you are tempted to run from. Write what standing would look like.", "Say the declaration."],
 "Future Me, I hope you can find your feet any time you need to. They have been under you the whole time.",
 "Standing is not the same as fighting. It is refusing to be moved.",
 "Today I choose to stay on my feet."),
(25, "Do the verse in order: submit first, then resist.",
 "James 4:7 says, “Submit yourselves therefore to God. Resist the devil, and he will flee from you.” James wrote to scattered Jewish Christians, and this verse sits in a passage about pride, worldliness, and humility (4:1–10). Notice the order: submission to God comes first, and resistance rests on that, not on your own strength.",
 ["GOLL"], "Making specific if–then plans (“If I feel the pull at 9 p.m., I will call my sponsor”) helps people carry out intentions more reliably than good intentions alone, according to a large body of work on implementation intentions.",
 ["Write the temptation or the thought you most often fight on your own.", "Write a submit sentence: “God, I give this to you: ______.” Say it as a prayer.", "Write an if–then resist plan: “If ______ happens, then I will ______ (call, leave, pray, drink water, go outside).”", "Put the plan on your phone as a note.", "Say the declaration."],
 "Future Me, I hope that plan has been used so many times it does not feel like a plan anymore. Just a reflex.",
 "Resistance without submission is just white-knuckling.",
 "Today I choose to hand it over before I push back."),
(26, "Find what is feeding your anger and starve that part, not the person.",
 "Ephesians 4:26–27 says, “Be angry and do not sin; do not let the sun go down on your anger, and give no opportunity to the devil.” Paul is quoting Psalm 4:4 and is not forbidding anger. He is warning about letting it sit and grow. Anger itself is treated as a signal, not as a sin.",
 ["RUM"], "Studies on rumination suggest that replaying anger in your head tends to keep it going rather than release it. Doing something physical, writing it out, or talking with someone safe may work better than rehearsing it.",
 ["Write what you are angry about. Use hard words if you need. No one will read this.", "Write what you would want to say to each person, in a letter you will not send.", "Walk fast for 5 minutes, or squeeze a towel, or do 20 pushes against a wall.", "Write one boundary you can set that protects you without punishing them.", "Say the declaration."],
 "Future Me, I hope the anger became something you can use for good: a boundary, a decision, a rebuilt life.",
 "Anger is a smoke alarm. Do not burn down the house, but do not ignore it either.",
 "Today I choose to move anger out of my body safely."),
(27, "Practice the thought that God takes you in when no one else did.",
 "Psalm 27:10 says, “For my father and my mother have forsaken me, but the LORD will take me in.” Psalm 27 is a psalm of David about trusting God in danger. The line acknowledges real abandonment and says God receives the one who was abandoned. It does not say that the abandonment was fine.",
 ["HOLT"], "A large meta-analysis found that people with stronger social relationships had a lower risk of early death than people with weaker ones. Belonging seems to matter for health, and God’s taking you in is not the only kind of belonging he provides.",
 ["Read the verse aloud three times, slower each time.", "Write the two names of people who have been safe for you, even briefly. Add one place, one animal, or one community.", "Write: “God, take me in. Here is where I feel unsheltered: ______.”", "Plan one contact with a safe person this week and put it on the calendar.", "Say the declaration."],
 "Future Me, I hope you have a table by now. If not, keep going. There are people you have not met who would pull a chair up for you.",
 "Being taken in is not a reward for being easy. It is a gift for being loved.",
 "Today I choose to let myself be held."),
(28, "Start the long, honest work of forgiving without pretending it is done.",
 "Colossians 3:13 says, “bearing with one another and, if one has a complaint against another, forgiving each other; as the Lord has forgiven you, so you also must forgive.” Paul is writing to a church about clothing themselves in compassion. Forgiveness here is rooted in what Jesus has done, and it does not erase the “complaint.” The wrong is real.",
 ["WADE"], "In a meta-analysis of forgiveness interventions, people who were helped to forgive reported better outcomes, but the best results came in programs that took time and addressed the emotional experience, not just the decision.",
 ["Write the name of the person you are working toward forgiving.", "Write what you are still angry about. Do not skip it.", "Write: “I am willing to be willing to forgive. I am not there yet, and that is okay.”", "Pray: “Jesus, you forgave from the cross. Help me with this one, one inch at a time.”", "Say the declaration. Do not contact the person unless it is safe and wise."],
 "Future Me, I hope forgiveness has become a place you can rest in. If it is still unfinished, that is not failure.",
 "Forgiveness is not forgetting, and it is not reconciliation.",
 "Today I choose one inch."),
(29, "Write what forgiven-but-not-back-in looks like for you.",
 "Proverbs 22:3 says, “The prudent sees danger and hides himself, but the simple go on and suffer for it.” Proverbs treats wisdom as seeing a real danger and acting. It is not unloving to stay out of a place that has hurt you.",
 ["ACE"], "People with several adverse childhood experiences are at higher average risk for later problems, which is why safe relationships and stable environments matter so much in recovery. This supports staying away from places and people that repeat the harm.",
 ["Write: “I forgive ______ and I will not ______.” Fill in the blank with a real boundary.", "Write three warning signs that you are being pulled back in.", "Write what you will do when you see them (leave, call someone, close the app, drive away).", "Share your boundary with one safe person.", "Say the declaration."],
 "Future Me, I hope you keep this boundary. It is not a punishment. It is how you protect what God has restored.",
 "You can forgive someone and still keep the door locked.",
 "Today I choose wisdom over wishful thinking."),
(30, "Put on the armor, one piece at a time, with your hands.",
 "Ephesians 6:14–15 says, “Stand therefore, having fastened on the belt of truth, and having put on the breastplate of righteousness, and, as shoes for your feet, having put on the readiness given by the gospel of peace.” Verses 16–17 add the shield of faith, the helmet of salvation, and the sword of the Spirit, which is the word of God. Paul is describing what God provides, and in verse 18 he adds prayer.",
 ["WOOD"], "Habit research suggests that actions repeated in the same place and time become automatic partly because the setting itself becomes a cue. Pairing the armor practice with a regular cue, like brushing your teeth, can make it easier to keep.",
 ["Stand up. Touch your waist and say, “Truth.” Touch your chest and say, “Righteousness, the right standing Jesus gave me.” Touch your feet and say, “Peace.”", "Raise one arm as if holding a shield. Say, “Faith.” Touch your head and say, “Salvation.” Open your hand and say, “The word.”", "Say a one-sentence prayer: “Lord, I put on what you provide.”", "Pick a cue (brushing your teeth, starting the car) to repeat this each morning.", "Say the declaration."],
 "Future Me, I hope the armor practice has become a morning habit that takes less than two minutes and settles you every time.",
 "You are not dressing for a fight you started. You are dressing so you can stay on your feet.",
 "Today I choose to get dressed on purpose."),
]
