# New per-day layer: (day, goal, context, [research keys], research, [steps], future_me, nugget, choose)
# context = what the day's Standing passage is, in its setting. research = hedged, one finding, not a promise.
R1 = [
(1, "Name that the fight is real, and that you are not fighting it alone.",
 "Paul wrote Ephesians while under arrest in Rome, around AD 60–62, to believers in Ephesus. “Struggle” translates a wrestling word. He is not saying people are never responsible for what they do. He is saying there is more going on in the world than what we can see, and that we are told to stand, not to panic.",
 ["ACE"], "The large ACE study of more than 17,000 adults found that the more kinds of childhood adversity a person reported, the higher their risk of later problems, including substance use. It describes risk across a group. It does not say what will happen to you.",
 ["Sit or stand where your feet can touch the floor. Set a timer for 2 minutes.", "Say out loud, “I am here. It is today. I am an adult.” Look around and name three things you can see.", "Read today’s verse once, slowly. Then read the “In context” box.", "Write on the Journal page the one sentence you most need to be true about this book.", "Say the declaration out loud. Check the box. Stop."],
 "Future Me, I am writing this on Day 1 so you can see where it started. I was scared and I did it anyway. If you are reading this, I kept going. Thank me.",
 "Seeing the whole battlefield is not the same as living on it. You can learn the map and still sleep at night.",
 "Today I choose to begin before I feel ready."),
(2, "Tell the truth about both parents without lying in either direction.",
 "First John was written by the apostle John to believers who were being taught confusing things about sin and about Jesus. Verse 7 says walking in the light brings fellowship and that Jesus’s blood cleanses us from all sin. Light in this letter means honesty before God, not performance.",
 ["PEN"], "In the classic 1986 study, people who wrote about a distressing event for a few days reported fewer health-center visits afterward than people who wrote about neutral topics. Later work found the average effect is modest and varies from person to person.",
 ["Get two sheets of paper. Head one “Mother” and one “Father.”", "For 5 minutes each, list what was true: what they did, what they failed to do, and what they did well. Use short phrases, not paragraphs.", "Put a star by anything you have never said to anyone. Do not explain it yet.", "Fold the pages and put them where no one will find them. You do not have to show anyone.", "Say the declaration. If you feel flooded, stop and do the 5-things-you-can-see reset."],
 "Future Me, you are going to be able to say both things: that you were hurt and that you were loved by somebody, sometimes in the same breath. That is not betrayal. That is accuracy.",
 "You are allowed to write a sentence you will later cross out. Honesty gets drafted before it gets polished.",
 "Today I choose accuracy over loyalty to a story."),
(3, "Hold what was done to you and what you did, without letting one erase the other.",
 "In Romans 7:15 Paul describes the struggle of doing what he does not want to do. He is writing to the church in Rome about the law, sin, and grace, and he is not hiding his own struggle. Chapter 8 follows with “There is therefore now no condemnation for those who are in Christ Jesus.”",
 ["SHAME"], "Researchers who study shame and guilt have found that shame (“I am bad”) tends to go with hiding and relapse risk, while guilt (“I did something wrong”) tends to go with repair. This is a pattern in groups of people, not a rule for you.",
 ["Draw a line down the middle of a page. Left: “What was done to me.” Right: “What I did.”", "Write three to five words in each column. No stories.", "Read the right-hand column aloud, then say, “I am accountable for this, and I am not disposable.”", "Read the left-hand column aloud, then say, “This was not my fault.”", "Say the declaration, then put a hand on your chest for five breaths."],
 "Future Me, I hope you can look at that two-column page without flinching now. It was never meant to be a verdict. It was a map.",
 "Accountable and ashamed are not the same room. You can live in the first without ever moving into the second.",
 "Today I choose responsibility without self-hatred."),
(4, "Spot the accuser’s voice and answer it with what Jesus has already said.",
 "Revelation 12:10 is part of John’s vision, written to churches under pressure around the end of the first century. The “accuser of our brothers” is cast down, and verse 11 says believers conquered him “by the blood of the Lamb and by the word of their testimony.” The accuser’s main work in Scripture is accusation, not creativity.",
 ["LIEB"], "In a brain-imaging study, simply putting a name on an emotion (“angry,” “afraid”) was linked to less amygdala activity than other responses. Naming the feeling is a small, free tool, and it is not a cure.",
 ["Write down the accusing sentence you hear most (for example, “It was your fault”). Use the exact words.", "Next to it write who is saying it: “My shame,” “My family,” “The accuser,” or “I don’t know.” Any answer is fine.", "Under it write one true sentence, such as “I was six months old,” or “I am forgiven.”", "Say the true sentence three times out loud, slowly.", "Say the declaration. Drink a glass of water."],
 "Future Me, there will be days the old sentence still shows up. You will not have to believe it to hear it. You will know what to write underneath.",
 "A lie said often does not become true. It becomes familiar. Familiar is not the same as accurate.",
 "Today I choose to check the sentence before I obey it."),
(5, "Learn what your body learned, without needing the story.",
 "Psalm 56 is attributed to David “when the Philistines seized him in Gath.” Verse 8 says, “You have kept count of my tossings; put my tears in your bottle. Are they not in your book?” God is described as someone who notices and keeps track of pain.",
 ["BREATH", "KOLK"], "A review of slow-breathing studies found that breathing slowly (around six breaths a minute) is linked to measurable changes in heart-rate variability and to feeling calmer in many people. Trauma writers like Bessel van der Kolk describe how stress can be held in the body, though the science is still being refined.",
 ["Sit with your feet flat. Put one hand on your belly. Set a timer for 3 minutes.", "Breathe in through your nose for 4 counts. Let it out slowly for 6 counts. Repeat.", "Notice where your body is tight. Do not fix it. Just say, “There.”", "Say to your body, quietly: “Thank you for watching out for me. We can rest now.”", "If breathing makes you dizzy or anxious, stop and press your feet into the floor instead."],
 "Future Me, I hope your body feels like a house you live in and not a trap you escaped. If it still startles easily, that is okay. It has a long memory.",
 "Your nervous system is not your enemy. It is a very loyal employee working off an old job description.",
 "Today I choose to be gentle with the part of me that stays alert."),
(6, "Give the very young part of you a place to be held, without going back into the fire.",
 "Isaiah 66:13 says, “As one whom his mother comforts, so I will comfort you.” Isaiah is speaking to Jerusalem after exile. God is described with a mother’s tenderness, which does not mean your own mother did that for you. It means God offers it.",
 ["BEETZ"], "A review of human–animal interaction research reported that contact with a friendly animal is linked to lower stress and, in some studies, changes in oxytocin and cortisol. The findings are mixed and often small, but many people feel steadier with a companion nearby.",
 ["Pick one soft thing: a blanket, a stuffed animal, or your dog’s warm back. Hold it for 2 minutes.", "Say softly, “I am here. I am the grown-up now.”", "Ask, “How old does the fear feel today?” Write only the number.", "Do not ask what happened. Just say hello to that age.", "Say the declaration and keep the soft thing close for the rest of the day."],
 "Future Me, remember that she did not need an explanation. She needed someone to show up. You can.",
 "You do not have to dig to be kind. You can just knock and say hello.",
 "Today I choose comfort over interrogation."),
(7, "Learn one reset you can do anywhere in under two minutes.",
 "Psalm 46:10 says, “Be still, and know that I am God.” The Hebrew word for “be still” can mean to relax your grip or let go. The psalm opens with God as “a very present help in trouble” and describes earthquakes, roaring waters, and nations in uproar, so “be still” is spoken in the middle of noise, not after it clears.",
 ["BREATH", "GROSS"], "Slow breathing is linked in studies to calmer physiology. Separately, research on emotion regulation suggests that changing how we think about a situation early on (reappraisal) tends to work better than trying to push the feeling down once it is big.",
 ["Choose one reset to practice: (a) feet-on-floor, (b) 4-in/6-out breathing, (c) cold water on wrists, or (d) naming five things you see.", "Practice it now for 90 seconds while you are calm. Calm practice is how it works when you are not.", "Write on a card: “When it spikes, I will ______.” Put the card where you will see it.", "Tell one person which reset you chose.", "Say the declaration."],
 "Future Me, I hope that card is worn soft from use. A reset you practiced when you were calm is the one you can find at 2 a.m.",
 "You do not rise to the occasion. You fall to the level of your practice. So practice small and early.",
 "Today I choose a tool I can reach."),
(8, "Make a list of who and what, without telling the whole story to anyone.",
 "Psalm 139:23–24 reads, “Search me, O God, and know my heart! Try me and know my thoughts! And see if there be any grievous way in me, and lead me in the way everlasting!” It is David’s prayer to be examined by someone who already knows him. He asks God to search, not to condemn.",
 ["PEN", "GOLL"], "Writing about hard experiences helps some people more when they also make plans for what to do next. Research on “if–then” plans found that people who wrote a specific plan (“If X happens, I will do Y”) were more likely to follow through than people who only intended to.",
 ["Make three columns: “Mother,” “Father,” “Me.” Under each write short phrases for what was never dealt with.", "Circle one item in each column you are ready to look at first. Leave the rest.", "Write one if–then plan: “If I start to feel numb or flooded, then I will ______.”", "Read the plan aloud.", "Say the declaration, then close the page."],
 "Future Me, I am sure the list is shorter than it feels today. Most things are, once they are on paper.",
 "A list is not a confession. It is a way to stop carrying it all in your head.",
 "Today I choose to organize the weight instead of just carrying it."),
(9, "Ask the practical questions: sleep, body, medication, safety, and professional help.",
 "Jeremiah 8:22 asks, “Is there no balm in Gilead? Is there no physician there? Why then has the health of the daughter of my people not been restored?” Gilead was known for healing balm. Jeremiah is grieving that help existed and the people were not being healed. The verse is not telling anyone to skip medicine. It is lamenting an unhealed wound.",
 ["EX"], "A Cochrane review concluded that exercise is moderately more effective than no treatment for depression symptoms, although the quality of evidence varies. Exercise is not a replacement for therapy or medication when those are needed.",
 ["Write down when you last had a medical check-up, a dental visit, a blood test, or talked to a counselor.", "Circle one overdue thing. Write how you will start: “Call ______ on ______.”", "Write your top three sleep problems (falling asleep, staying asleep, nightmares). Underline one to bring up with a doctor.", "If you take medication, write one question you have about it. Do not stop or change it on your own.", "Say the declaration. Put the appointment in your phone before you close this book."],
 "Future Me, I hope you went. Taking yourself to the doctor is a spiritual act, too. Bodies are not the enemy of faith.",
 "God made physicians and God made your body. Using them is not a lack of faith.",
 "Today I choose to treat my body like it matters."),
(10, "Set a start date, a reason bigger than fear, and one person who knows.",
 "Proverbs 4:26 says, “Ponder the path of your feet; then all your ways will be sure.” Proverbs is a collection of wisdom sayings, many of them written as a father instructing his child. Here the instruction is to pay attention to where you are walking, which is a call to be deliberate.",
 ["LALLY"], "A study that tracked people forming a new daily habit found that it took anywhere from about 18 to 254 days to feel automatic, with a typical figure of about 66 days. Missing a single day did not ruin the process.",
 ["Write today’s date at the top of a card. Write a start date for your daily practice time (same time, same place).", "Write your reason in one sentence. It has to be bigger than “because I should.”", "Choose one person to tell. Write their name.", "Send them a text: “I’m doing 90 days of something hard. Will you check on me on day 10, 30, and 60?”", "Say the declaration. Put the card on your mirror or fridge."],
 "Future Me, you did the first ten. That is already a streak most people never see. Look at the card on your wall.",
 "Habits aren’t built by mood. They are built by showing up, imperfectly, in the same spot.",
 "Today I choose a time, a place, and a witness."),
(11, "See one thing your home taught without words, and name what you would teach instead.",
 "In John 8:31–36 Jesus speaks to people who had believed in him: “If you abide in my word, you are truly my disciples, and you will know the truth, and the truth will set you free.” In the very next lines he says that everyone who sins is a slave to sin and that “if the Son sets you free, you will be free indeed.” Truth here is tied to Jesus himself and to staying with his word.",
 ["ROIS"], "Attachment researchers have found that some adults who had difficult childhoods can describe them honestly and coherently and still have secure relationships in adulthood. The term is “earned security.” It suggests that the past shapes us without sealing our future.",
 ["Write the sentence: “In my house, nobody ever said it out loud, but the rule was ______.” Fill it in three different ways.", "Pick one. Write the opposite rule that you want for your life now.", "Say the new rule out loud once.", "Write one small action you did today that fits the new rule, even if it is tiny.", "Say the declaration."],
 "Future Me, I hope the new rule is a habit by now. If it still feels strange, that is how a new language feels at first.",
 "What was never said still got learned. What is said now can be learned too.",
 "Today I choose to speak the rule I want to live by."),
(12, "Write one lie, the evidence against it, and the truth, in a three-line row.",
 "In 2 Corinthians 10:3–5 Paul is defending his ministry to a church that had doubts about him. He says, “the weapons of our warfare are not of the flesh but have divine power to destroy strongholds,” and speaks of taking every thought captive to obey Christ. The battle in this passage is over arguments and thoughts, not over bodies or people.",
 ["GROSS"], "Cognitive therapy, which teaches people to check their thoughts against evidence, has been shown in clinical trials to help with depression and anxiety. Checking a thought is different from arguing with it, which usually feeds it.",
 ["Write the lie in the first line: “I wasn’t worth protecting.”", "Second line, “Evidence against this:” list two facts. For example, “I was an infant,” “Infants are not responsible for protecting themselves.”", "Third line, “What Scripture says:” write the verse reference from today’s page and put it in your own words.", "Read all three lines aloud in order.", "Say the declaration."],
 "Future Me, I wonder how many of those lies have lost their grip by now. If one is still stubborn, we have a plan: lie, evidence, truth, repeat.",
 "You do not have to win an argument with a lie. You just have to stop signing its paperwork.",
 "Today I choose evidence over echo."),
(13, "Write down the names you were called, and hand them back.",
 "Isaiah 43:1 comes in the middle of God’s word to Israel after the Babylonian exile was announced: “But now thus says the LORD, he who created you… ‘Fear not, for I have redeemed you; I have called you by name, you are mine.’” In Scripture, to be called by name means to be known and claimed. The promise was spoken to a people, and Christians read it as the character of the God who calls his own.",
 ["NEFF"], "Self-compassion researchers have linked treating yourself kindly, remembering you are not alone in suffering, and noticing pain without exaggerating it to lower depression and anxiety. In one trial, an eight-week self-compassion program improved well-being compared with a waiting list.",
 ["Write three names or labels you were called growing up. Write who said each one.", "Under each write: “That was their word, not mine.”", "Write one name God uses in Scripture for those who are his (child, beloved, redeemed, called).", "Say that name out loud, then say, “That is what I answer to.”", "Say the declaration."],
 "Future Me, I hope you have a name now that fits. If you still flinch at the old ones, remember they were handed to you. You can put them down.",
 "The names we carry often belong to somebody else’s pain.",
 "Today I choose to answer to the name God gives."),
(14, "Choose a new name or phrase and practice answering to it.",
 "Revelation 2:17 is part of Jesus’s message to the church in Pergamum: “To the one who conquers I will give some of the hidden manna, and I will give him a white stone, with a new name written on the stone that no one knows except the one who receives it.” The meaning of the white stone is debated by scholars. What is clear is the picture of being personally known and renamed by Jesus.",
 ["KING"], "In a study on writing about life goals, people who wrote for a few days about their best possible future selves reported better well-being afterward than people who wrote about neutral topics. It is a small effect, and it works best when the writing is realistic.",
 ["Write down three words you would want someone to use for you in five years (for example, steady, tender, brave).", "Pick one as your word for this week. Write it on a card.", "Say, “My word is ______. I am practicing it.” Out loud once.", "Write one small thing you did today that matches the word.", "Say the declaration."],
 "Future Me, what word did you pick? I hope it is one that other people use about you now.",
 "A new name is not a costume. It is a direction you start walking.",
 "Today I choose a word to grow toward."),
(15, "Say it to yourself in the words you would say to a baby: “It was not your fault.”",
 "Psalm 103:13 says, “As a father shows compassion to his children, so the LORD shows compassion to those who fear him.” The psalm is attributed to David and praises God for forgiving, healing, and redeeming. It also says, “He knows our frame; he remembers that we are dust” (v. 14). God knows how small and fragile we are.",
 ["NEFF"], "Self-compassion studies suggest that speaking to yourself with the kindness you would give a friend is linked to lower self-criticism and less shame. It can feel odd and unearned at first, which is normal.",
 ["Find a photo of yourself as a baby or small child, or picture one. If you have none, write “baby me” on a card.", "Hold it for 30 seconds. Say, “It was not your fault.”", "Say it again slower. Notice your breath.", "If you feel overwhelmed, stop and press your feet on the floor.", "Say the declaration and finish with a glass of water."],
 "Future Me, I am hoping you can say that sentence without flinching and mean it. If you cannot yet, tomorrow is not too late.",
 "A six-month-old cannot be at fault. This is not opinion. It is a fact.",
 "Today I choose to believe what is true about her."),
]
