R4 = [
(46, "Separate what you inherited from what you are guilty of.",
 "Ezekiel 18:20 says, “The soul who sins shall die. The son shall not suffer for the iniquity of the father, nor the father suffer for the iniquity of the son. The righteousness of the righteous shall be upon himself, and the wickedness of the wicked shall be upon himself.” Ezekiel was speaking to Judean exiles in Babylon who were saying, “The fathers have eaten sour grapes, and the children’s teeth are set on edge.” God answers that each person is accountable for their own sin. You may inherit terrain, but not guilt.",
 ["GOLDM", "ACE"], "Twin and family studies suggest that genetics account for a meaningful share (often estimated around 40–60 percent) of vulnerability to addiction, and adverse childhood experiences add risk. Both describe risk, not destiny, and neither is moral guilt.",
 ["Make two columns: “What I may have inherited (terrain)” and “What I am responsible for now (choices).”", "Under terrain, list things like family history of addiction, early stress, learned coping.", "Under choices, list things you can do: treatment, meetings, boundaries, sleep, supports.", "Say: “I did not choose the terrain. I do choose the path.”", "Say the declaration."],
 "Future Me, I hope you carry the terrain without shame and walk the path with wisdom.",
 "Risk is not guilt. Knowing your terrain is how you plan the route.",
 "Today I choose to work with my terrain, not against myself."),
(47, "Find one good thing in your family line and honor it.",
 "Psalm 78:4 says, “We will not hide them from their children, but tell to the coming generation the glorious deeds of the LORD, and his might, and the wonders that he has done.” Psalm 78 is a long historical psalm attributed to Asaph that tells Israel’s story, including their failures, so that the next generation will not repeat them and will trust God. Passing on truth, good and hard, is the point.",
 ["EMM"], "In a series of studies, people asked to list things they were grateful for each week reported greater well-being than those who listed hassles. Gratitude does not erase pain, but it can balance what we notice.",
 ["Write three good things from your family, however small (a recipe, a song, a strong aunt, a funny phrase, a work ethic).", "Circle the one you want to carry forward.", "Write one way you will carry it (cook it, sing it, say it, do it).", "If you cannot find any good, write a good thing you would want to start.", "Say the declaration."],
 "Future Me, I hope you are passing on what is worth keeping.",
 "A broken line can still have good threads. Pull the ones worth keeping.",
 "Today I choose to keep what is good."),
(48, "Map the four layers: body, home, learning, and spirit, and how each can change.",
 "Romans 12:2 says, “Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect.” Paul writes this after eleven chapters of explaining what God has done. Transformation is described as ongoing and as happening by renewal, which fits how habits are changed.",
 ["GOLDM", "BAND"], "Addiction risk is shaped by biology, environment, and learning, and each of those layers can be addressed. Bandura’s work suggests that behaviors we learn from watching others can be replaced by new ones we see modeled and practice.",
 ["Draw four boxes: Body, Home, Learning, Spirit.", "In each, write one way it affected you, and one change you can make (Body: sleep and treatment; Home: who you live with; Learning: new habits; Spirit: prayer and community).", "Choose one change to start this week.", "Write the first step and the date.", "Say the declaration."],
 "Future Me, I hope all four boxes have a check mark in them by now.",
 "You can change what you can reach. Start with the layer closest to your hands.",
 "Today I choose one layer to work on."),
(49, "Remember that you did not start it.",
 "Lamentations 5:7 says, “Our fathers sinned, and are no more; and we bear their iniquities.” Lamentations is a collection of laments over the fall of Jerusalem in 586 BC. This verse is the cry of people feeling the weight of what came before. Notice that it is a lament, not a doctrine. It describes pain and does not command anyone to accept it forever.",
 ["KAUF"], "Early research on abuse found that a minority (often cited around one-third) of abused children went on to abuse their own children, which means most did not. The finding is old and debated, but it supports the point that the pattern can be broken.",
 ["Write: “It started before me. The first person in my family I know of who ______ was ______.” If you do not know, write “I do not know.”", "Write: “I am not the beginning of this.”", "Write: “I can be the end of it.”", "Pray: “Lord, I name what I have inherited. I am asking you to meet me here.”", "Say the declaration."],
 "Future Me, I hope you see that you are a link, and you can be the last link of that kind.",
 "You are not the origin, but you may be the interruption.",
 "Today I choose to be the one who interrupts."),
(50, "Stand in the gap in prayer, without taking on the family’s sin as your debt.",
 "In Nehemiah 1:6 Nehemiah prays, “let your ear be attentive and your eyes open, to hear the prayer of your servant that I now pray before you day and night for the people of Israel your servants, confessing the sins of the people of Israel, which we have sinned against you. Even I and my father’s house have sinned.” He was cupbearer to the Persian king, hearing that Jerusalem’s walls were broken. He prays honestly, includes himself, and then acts.",
 ["KELLY"], "A review of studies on Alcoholics Anonymous and similar programs found that they were as effective as or more effective than other treatments at helping people stay abstinent, and they cost less. Community matters in recovery.",
 ["Write one prayer for your family, naming what you see: “Lord, we have struggled with ______.”", "Write one honest line about yourself: “I too have ______.”", "Write one action that follows the prayer, as Nehemiah’s did (go to a meeting, book an appointment, call someone).", "Do the action today or schedule it.", "Say the declaration."],
 "Future Me, I hope that prayer led somewhere real. Prayer and a phone call can go together.",
 "Standing in the gap is not paying the debt. It is leading the way out.",
 "Today I choose to pray and do something about it."),
(51, "Write a prayer for those who came before and those who come after.",
 "Exodus 34:6 says, “The LORD, the LORD, a God merciful and gracious, slow to anger, and abounding in steadfast love and faithfulness.” In the next verses God also says he visits the iniquity of fathers on the children to the third and fourth generation. Read together, verse 6 is the lead: his character is mercy. The generational line is a real consequence of sin spreading, while his steadfast love extends to thousands.",
 ["KING"], "Writing about your best possible future, as in studies of life-goal writing, has been linked to better well-being. It tends to help most when you also say what you will do.",
 ["Write a prayer for your parents (whatever their state), in your own words.", "Write a prayer for yourself.", "Write a prayer for anyone who comes after you (nieces, nephews, friends’ children, people you will mentor).", "Read all three aloud.", "Say the declaration."],
 "Future Me, I hope that prayer is part of you now. The line can turn around.",
 "You can pray for people without taking their place.",
 "Today I choose mercy in both directions."),
(52, "Replace one family saying with a true one.",
 "Proverbs 26:2 says, “Like a sparrow in its flitting, like a swallow in its flying, a curse that is causeless does not alight.” Proverbs uses vivid images from nature. The verse says an undeserved curse does not land. Words spoken over you that have no cause do not have the power they claimed.",
 ["KROSS"], "Research on self-talk suggests that how you speak to yourself, even something as small as using your name, can change how a stress response feels. Replacing a familiar phrase with a new one takes repetition.",
 ["Write the saying you heard growing up (for example, “We’re all addicts,” “Nothing ever works out for us”).", "Write who said it and what they were afraid of.", "Write a true replacement: “Some of us struggled. I am choosing recovery.”", "Say the replacement ten times today when you notice the old one.", "Say the declaration."],
 "Future Me, I hope you catch the old words and swap them without thinking.",
 "A saying repeated enough sounds like fate. It is not.",
 "Today I choose words that match the future."),
(53, "Practice one thing nobody taught you, as a beginner.",
 "Ephesians 4:23–24 says, “and to be renewed in the spirit of your minds, and to put on the new self, created after the likeness of God in true righteousness and holiness.” Paul talks about taking off the old self and putting on the new, like changing clothes. It is something you practice, not something you feel your way into.",
 ["BAND"], "Bandura’s research on learning suggests that people learn by watching others and by practicing in small steps, and that early successes increase confidence. Being a beginner is a normal part of learning.",
 ["Choose one skill nobody taught you (asking for help, saying no, budgeting, apologizing, resting).", "Watch or read about it for ten minutes (a safe person, a short video, a book).", "Practice it once today in a small way.", "Write what happened and how it felt.", "Say the declaration."],
 "Future Me, I hope you are no longer ashamed to be a beginner. Everyone who is good at something was bad at it first.",
 "Not knowing is not the same as not being able.",
 "Today I choose to practice badly."),
(54, "Honor without repeating.",
 "Exodus 20:12 says, “Honor your father and your mother, that your days may be long in the land that the LORD your God is giving you.” It is the fifth of the Ten Commandments. In the Bible, honor is not blind obedience to harm, and elsewhere in Scripture God warns against abuse and calls parents to care for their children. Honor can mean treating someone with basic dignity, telling the truth about them, and keeping your distance when needed.",
 ["ROIS"], "Attachment research suggests that people with painful childhoods can build secure relationships over time, even if they keep boundaries with their families. Distance and dignity are not opposites.",
 ["Write one way you can honor your parent(s) without getting hurt (pray for them, speak kindly of the good, keep the peace from a distance).", "Write one thing that would not be honor (taking blame, enabling, lying).", "Write one boundary you will keep.", "Say, “I can honor the person without repeating the pattern.”", "Say the declaration."],
 "Future Me, I hope your honor is clean: truth, dignity, and distance as needed.",
 "Honor is not a blank check.",
 "Today I choose honor with boundaries."),
(55, "Write the promise: the line stops here.",
 "Joshua 24:15 says, “And if it is disagreeable in your sight to serve the LORD, choose this day whom you will serve, whether the gods your fathers served in the region beyond the River, or the gods of the Amorites in whose land you dwell. But as for me and my house, we will serve the LORD.” Joshua says this at Shechem, near the end of his life. Notice “choose this day.” He names what came before and picks anyway.",
 ["GOLL"], "Specific, written commitments with if–then plans are linked to higher follow-through. The more concrete the promise, the more likely it is to be kept.",
 ["Write: “The line stops with me. This means ______.” Be specific (I will stay in recovery, I will get help, I will tell the truth).", "Write: “If I am tempted to ______, then I will ______.”", "Sign and date the promise.", "Show it to one safe person or put it where you can see it.", "Say the declaration."],
 "Future Me, I hope you still have that signed promise. Look at it on the days you feel like giving up.",
 "You are not carrying it on. You are carrying it out.",
 "Today I choose to sign my name to a new direction."),
(56, "Learn your own list of patterns, the way an investigator would.",
 "Second Corinthians 2:11 says, “so that we would not be outwitted by Satan; for we are not ignorant of his designs.” Paul has just urged the church to forgive and comfort a repentant man. He says being unforgiving would give Satan an advantage. Knowing the patterns of temptation and division is a defensive skill.",
 ["AVE"], "Relapse-prevention research found that identifying high-risk situations (people, places, feelings) and planning responses to them helps people avoid a lapse becoming a full relapse.",
 ["List your top three high-risk situations (for example, payday, being alone at night, arguments).", "Next to each write the early warning sign (a thought, a feeling, a pull).", "Next to each write your plan (call, leave, eat, pray).", "Share one with a safe person.", "Say the declaration."],
 "Future Me, I hope you know your patterns so well that you see them coming and step aside.",
 "Naming the pattern is half of stopping it.",
 "Today I choose to see it coming."),
(57, "Reach out to one person today. Not tomorrow.",
 "Ecclesiastes 4:9–10 says, “Two are better than one, because they have a good reward for their toil. For if they fall, one will lift up his fellow. But woe to him who is alone when he falls and has not another to lift him up!” The author, called the Preacher, is looking at life under the sun and sees the cost of isolation. Companionship is described as a practical good.",
 ["HOLT"], "A large analysis found that stronger social connection was associated with a substantially lower risk of death, on a scale comparable to well-known health risks. Isolation is a real risk, not just a mood.",
 ["Write the name of one person you can contact (safe, even if you only know them a little).", "Write what you will say: “I’m having a rough day. Do you have ten minutes?”", "Send it now.", "If they do not respond, write a second name and try again.", "Say the declaration."],
 "Future Me, I hope you have a person you reach for without thinking. If it is still hard, keep reaching.",
 "You are allowed to need help. That is what other people are for.",
 "Today I choose to reach before I fall."),
(58, "Let someone who loves you tell you the truth.",
 "Proverbs 27:17 says, “Iron sharpens iron, and one man sharpens another.” Verse 6 in the same chapter adds, “Faithful are the wounds of a friend; profuse are the kisses of an enemy.” Proverbs treats honest friends as a gift. It also assumes you pick them with care.",
 ["KELLY"], "Mutual-help and peer-support groups have been shown in reviews to support recovery, partly through accountability and shared experience. Being known by people who care is protective.",
 ["Write the name of one person who has told you the truth in love (or one you would trust to).", "Write one question to ask them: “What do you see that I am missing?”", "Ask it this week and listen without defending.", "Write one thing you heard and one thing you will do about it.", "Say the declaration."],
 "Future Me, I hope you chose your people well and kept them. Sharp friends keep you from going dull.",
 "The right friend will say what you need to hear, not just what you want.",
 "Today I choose honest company."),
(59, "Stop waiting for permission to start.",
 "Ephesians 5:15–16 says, “Look carefully then how you walk, not as unwise but as wise, making the best use of the time, because the days are evil.” Paul urges careful, intentional living. “Making the best use of the time” points to seizing opportunities, not to panic.",
 ["LALLY"], "Habit research shows that new behaviors become easier with daily repetition, and that missing a day here and there does not ruin the process. Starting small and starting now matters more than starting perfectly.",
 ["Write one thing you have been waiting to start (treatment, a call, a job application, a meeting, a hobby).", "Make the first step ridiculously small (find a phone number, write one sentence).", "Do that step in the next 10 minutes.", "Write when you will do the next step.", "Say the declaration."],
 "Future Me, I hope you are not waiting on anything anymore. Look what the first small step started.",
 "Waiting for the perfect time is how the years pass.",
 "Today I choose the first step."),
(60, "Map one trigger chain from start to finish.",
 "First Peter 5:8–9 says, “Be sober-minded; be watchful. Your adversary the devil prowls around like a roaring lion, seeking someone to devour. Resist him, firm in your faith, knowing that the same kinds of suffering are being experienced by your brotherhood throughout the world.” Peter writes to believers facing persecution. “Sober-minded” and “watchful” describe alert, steady attention. “Resist him, firm in your faith” puts the weight on staying planted, not on running around.",
 ["URGE"], "Research on urge surfing and mindfulness-based relapse prevention suggests that cravings rise, peak, and pass, and that noticing the process without acting can reduce relapse risk. Cravings tend to be shorter than they feel.",
 ["Pick the last time you felt a strong urge or fell into an old pattern.", "Write the chain: What happened first? Then what did you feel? Then what did you think? Then what did you do?", "Circle the earliest link where you could have done something different.", "Write what you would do at that link next time.", "Say the declaration."],
 "Future Me, I hope you catch it at the first link now. The earlier you act, the easier it is.",
 "Triggers are chains. Break the chain at the weakest link.",
 "Today I choose to interrupt the chain early."),
]
