R3 = [
(31, "Find one agreement you made as a child and read it as a child’s conclusion.",
 "Colossians 2:14 speaks of God “by cancelling the record of debt that stood against us with its legal demands. This he set aside, nailing it to the cross.” Paul is writing to a church being pressured by rules and spiritual experiences, and he says Christ has dealt with the list of charges. For Christians this is the basis for believing that the “paperwork” against you is not the last word.",
 ["PEN"], "Writing about an experience several days in a row is associated, on average, with modest improvements in well-being, partly because people begin to organize what happened into a story. It does not work equally well for everyone, and it is not a substitute for treatment.",
 ["Finish this sentence three ways: “When I was little, I decided that ______.”", "Circle the one that has run your life the most.", "Write how old you were when you decided it. A guess is fine.", "Say, “That was a child’s conclusion. It was reasonable then. I can revisit it now.”", "Say the declaration."],
 "Future Me, I hope that conclusion no longer sits at the head of the table. You were just trying to make sense of something nobody should have had to make sense of.",
 "A child’s conclusion is not a life sentence.",
 "Today I choose to revisit a decision I made before I could vote."),
(32, "Hear the vow plainly: “I will never need anyone.”",
 "In Matthew 5:37 Jesus says, “Let what you say be simply ‘Yes’ or ‘No’; anything more than this comes from evil.” He is teaching in the Sermon on the Mount about oaths, and says people should not need to swear to be believed. The point is honest, simple speech. Vows made out of fear and pain are not treated here as binding on you in Jesus’s name.",
 ["ROIS"], "Attachment research suggests that people who learned early not to rely on others can learn to depend on safe people later, often through repeated experiences with someone steady. It takes time and it is not about willpower.",
 ["Write the vow you made in your own words: “I will never ______.”", "Write what it protected you from.", "Write what it has cost you: friendships, love, help, rest.", "Say it out loud once: “I made this vow to survive. I understand why.”", "Say the declaration. Do not try to release it today. Just look at it."],
 "Future Me, I hope that vow has loosened. You do not have to need everyone. You just don’t have to need no one.",
 "Self-reliance was the right answer once. It might not be the right answer forever.",
 "Today I choose to see my vow without being ruled by it."),
(33, "Release a child’s promise in prayer, in your own words.",
 "In Mark 10:13–14 people were bringing children to Jesus and the disciples scolded them. Jesus was indignant and said, “Let the children come to me; do not hinder them, for to such belongs the kingdom of God.” The scene shows Jesus welcoming the young and the powerless, and removing the obstacles people put in front of them.",
 ["NEFF"], "Compassion-focused approaches suggest that people who speak to their younger or hurting selves with kindness often feel less shame over time. The effects are modest on average and vary a lot from person to person.",
 ["Read yesterday’s vow aloud.", "Write a prayer: “Jesus, she made this promise to survive. I am letting her put it down. Hold it for her.”", "Pray it aloud or whisper it.", "Write what you will do differently in one small way this week (ask for help, accept an offer, say no to something).", "Say the declaration. Do something kind for the child in you, such as a favorite snack or a nap."],
 "Future Me, I hope you feel lighter. If you do not, that is okay. This is a seed, not a harvest.",
 "Releasing a vow is not the same as being weak. It is the same as being free.",
 "Today I choose to put down what I picked up in fear."),
(34, "Replace one thing you say to yourself with something true and kind.",
 "Ephesians 4:29 says, “Let no corrupting talk come out of your mouths, but only such as is good for building up, as fits the occasion, that it may give grace to those who hear.” It is addressed to a church about how they speak to each other. It also fits how we speak to ourselves, though that is an application, not the verse’s direct subject.",
 ["KROSS"], "In studies of self-talk, people who addressed themselves by name or as “you” (instead of “I”) while stressed often reported less anxiety and performed better under pressure. It is a simple tool, and results differ among people.",
 ["Write the mean thing you say to yourself most. Exact words.", "Cross it out with one line.", "Write what you would say to a friend in the same situation.", "Say it to yourself using your name: “______, you are doing the best you can with what you have.”", "Say the declaration."],
 "Future Me, I hope the kind voice is the one that answers first now. If it is not yet, you are building it.",
 "You would never talk to a child like that. She is still in there.",
 "Today I choose a kinder sentence."),
(35, "Notice the shame that belongs to somebody else and hand it back.",
 "Psalm 34:5 says, “Those who look to him are radiant, and their faces shall never be ashamed.” The psalm is attributed to David after he escaped from Abimelech (Achish) by pretending to be insane. The shame in view is the disgrace of being abandoned, and the answer is looking to God.",
 ["SHAME"], "Research on shame and addiction suggests that shame often drives hiding, and hiding often drives relapse. People who tend toward guilt (“I did something wrong”) over shame (“I am wrong”) tend to take more steps to repair.",
 ["Write one thing you are ashamed of that someone else did to you or put on you.", "Write: “This is not mine. I am handing it back.”", "Take a piece of paper, write the shame on it, and tear it in four pieces. Throw it away.", "Say a short prayer: “Jesus, take it. I do not need it.”", "Say the declaration."],
 "Future Me, I hope your face lifts easily now. If shame still shows up, you know where to send it.",
 "Shame is a heavy coat someone else put on you. You can take it off.",
 "Today I choose to look up."),
(36, "Break one silence in a safe way.",
 "Psalm 32:3 says, “For when I kept silent, my bones wasted away through my groaning all day long.” David is describing what concealing sin did to him, and verse 5 continues, “I acknowledged my sin to you, and I did not cover my iniquity; I said, ‘I will confess my transgressions to the LORD,’ and you forgave the iniquity of my sin.” The relief came when he spoke. This is about confession to God, which can include a safe person.",
 ["PEN"], "Studies of expressive writing suggest that putting secrets into words can reduce the load they carry, even when no one reads them. When possible, telling a safe, trained person can help more than writing alone.",
 ["Write one secret in a sentence. No details needed.", "Decide who is safe: a counselor, a pastor you trust, a recovery sponsor, a close friend, or God alone for now.", "Write what you would say in one sentence, such as “There is something I have never told anyone, and I need to say it.”", "Practice saying it aloud once.", "Say the declaration. Choose a day this week to tell one safe person."],
 "Future Me, I hope that secret has lost its power. Secrets get smaller when someone else knows.",
 "A secret is a heavy thing to carry alone.",
 "Today I choose one safe disclosure."),
(37, "Name what still holds you, in plain words, with no spooky language.",
 "First Corinthians 6:17 says, “But he who is joined to the Lord becomes one spirit with him.” Paul is writing to the church at Corinth about sexual immorality and about bodies belonging to the Lord. The ties we form to people and substances are real emotionally and in the body. The Bible’s answer is a stronger union with Christ, not a ritual.",
 ["ROIS"], "Attachment research shows that early bonds shape how we connect later, including to people who are not good for us. Trauma-informed therapists often describe this as a pattern that can be understood and gradually changed.",
 ["List three people, substances, or places you still feel pulled toward.", "Next to each write what the pull feels like in your body (tight chest, craving, heat).", "Write what you got from each that you needed (comfort, escape, belonging).", "Write one safer source for that need.", "Say the declaration."],
 "Future Me, I hope the pulls feel quieter. If any are still loud, you know what you are really hungry for.",
 "A tie is a real thing. So is freedom.",
 "Today I choose to name what holds me."),
(38, "Practice releasing: give back what was never yours to carry.",
 "Philippians 3:13–14 says, “Brothers, I do not consider that I have made it my own. But one thing I do: forgetting what lies behind and straining forward to what lies ahead, I press on toward the goal for the prize of the upward call of God in Christ Jesus.” Paul wrote from prison and in the same letter says he has not yet arrived. Forgetting here means not letting the past define the race, not erasing it.",
 ["WOOD"], "Research on habits suggests that changing cues in your environment can make it easier to break old patterns. Removing reminders, changing routes, and changing routines help more than relying on willpower alone.",
 ["Write one object, number, place, or app connected to what pulls you back.", "Decide: delete, hide, move, or give away. Do it now, or put a time on it.", "Write one new cue to replace it (a photo, a verse card, a different route).", "Say, “I am pressing on.”", "Say the declaration."],
 "Future Me, I hope those cues are gone and you do not miss them. Look how far you have pressed on.",
 "You are not forgetting what happened. You are refusing to live there.",
 "Today I choose to remove one reminder."),
(39, "Find what you were really thirsty for.",
 "Jeremiah 2:13 says, “for my people have committed two evils: they have forsaken me, the fountain of living waters, and hewed out cisterns for themselves, broken cisterns that can hold no water.” God, speaking through Jeremiah, describes his people trying to meet a real need in places that cannot hold it. It names the thirst as legitimate and the cistern as the problem.",
 ["BA"], "Behavioral activation, a well-studied approach, helps people re-engage with activities that give a sense of meaning and pleasure instead of avoiding or numbing. In one trial it did as well as other treatments for depression. It works by doing, not by waiting to feel like it.",
 ["Write what the substance or pattern gave you: relief, belonging, energy, quiet, feeling chosen.", "Next to each, write one healthier source of it.", "Pick one activity from that list and schedule it for a specific time today or tomorrow.", "Do it, even for ten minutes. Note afterward how you feel.", "Say the declaration."],
 "Future Me, I hope that list became your routine. The thirst was real. You found water that holds.",
 "Your hunger was never the problem. The cistern was.",
 "Today I choose a well that holds water."),
(40, "Learn the difference between a trauma bond and love.",
 "First John 4:18 says, “There is no fear in love, but perfect love casts out fear. For fear has to do with punishment, and whoever fears has not been perfected in love.” John is writing about God’s love and about how believers love each other. Love here is described as safe, not as a source of terror.",
 ["ACE"], "Studies of adverse childhood experiences show that early harm can make unsafe relationships feel familiar. Many people feel strongest pulled toward patterns that echo childhood, even when the patterns hurt them.",
 ["Make two columns: “Feels like love but isn’t” and “Is love.”", "Under the first list three things from your past (intense highs and lows, constant fear, being needed to fix someone).", "Under the second list three things you want (steady, consistent, kind, safe to disagree).", "Circle one thing in the second column to look for this month.", "Say the declaration."],
 "Future Me, I hope calm no longer feels boring. I hope it feels like home.",
 "Love that makes you afraid is not the love John is talking about.",
 "Today I choose safe over intense."),
(41, "Put down the control you used to survive.",
 "In Matthew 6:27 Jesus asks, “And which of you by being anxious can add a single hour to his span of life?” It is part of the Sermon on the Mount, in a stretch about not being anxious about food, clothes, or tomorrow. He points to birds and flowers, and he is not telling people to be careless. He is telling them they are not in charge of everything.",
 ["RUM"], "Studies of rumination suggest that trying to think your way to total certainty usually increases worry. Acting on one small thing and then letting go tends to help more.",
 ["Write three things you are trying to control that you cannot.", "Write one thing in each area that is yours to do (call, schedule, decide).", "Do one of them.", "Pray: “God, I release ______ to you.”", "Say the declaration."],
 "Future Me, I hope you sleep better. Control was a way of staying safe. You can hold it more loosely now.",
 "Control is a comforting lie. Trust is a harder, truer thing.",
 "Today I choose to do my part and leave the rest."),
(42, "Receive worth that is not earned by work or rescue.",
 "In Luke 10:38–42 Jesus visits Martha and Mary. Martha is “distracted with much serving” and asks him to tell Mary to help. Jesus answers, “Martha, Martha, you are anxious and troubled about many things, but one thing is necessary. Mary has chosen the good portion, which will not be taken away from her.” He is not shaming work. He is pointing out that Martha is being pulled apart by it.",
 ["NEFF"], "Self-compassion research has linked treating yourself kindly with greater motivation and resilience, not laziness. People who are kind to themselves after a failure are often more likely to try again.",
 ["Write the ways you try to earn love (fix, give, please, perform).", "Write how you feel when you stop doing them.", "Choose a 15-minute period today to simply sit and do nothing useful. Sit.", "Say, “I am loved at rest.”", "Say the declaration."],
 "Future Me, I hope you can sit in a room with no tasks and not panic. If you can, that is a miracle.",
 "You were never meant to earn your place at the table.",
 "Today I choose worth that does not need a job."),
(43, "Stop punishing yourself for what the Lord has already carried.",
 "Romans 8:1 says, “There is therefore now no condemnation for those who are in Christ Jesus.” It comes after Romans 7, where Paul describes struggling with sin. “Therefore” ties it to the argument: the verdict has already been handled in Christ. Conviction that moves you toward repair can come from God. Condemnation that keeps you in the dock does not.",
 ["SHAME"], "Research suggests that harsh self-punishment tends to increase hiding, not repair. Repair after a mistake is more likely when people feel responsible but not worthless.",
 ["Write one way you punish yourself (starving, isolating, overworking, using, harming).", "Write what you think it pays for.", "Write: “Jesus already paid for this. I do not need to.”", "Replace the punishment with one kind, concrete act (a meal, a shower, a nap, a call).", "If the urge to hurt yourself is strong, call or text 988 or tell a safe person now. Say the declaration."],
 "Future Me, I hope you no longer feel you owe anyone your suffering.",
 "Self-punishment feels like justice. It is just more hurt.",
 "Today I choose repair over penance."),
(44, "Get through a dark day safely.",
 "In 1 Kings 19:4–5 Elijah, exhausted and afraid after Jezebel’s threat, goes a day’s journey into the wilderness and asks that he might die: “It is enough; now, O LORD, take away my life.” God does not scold him. An angel touches him and says, “Arise and eat.” Rest and food come first. The fuller conversation with God comes later.",
 [], "If you are thinking about ending your life, the 988 Suicide & Crisis Lifeline offers free, confidential support by call or text, any hour, in the U.S. Wanting to disappear is a sign of overwhelming pain, not a character flaw, and it can be spoken about out loud.",
 ["If you are in danger right now, call or text 988 (or call 911). Stay with someone if you can.", "Tell one safe person in plain words: “I am having a dark day. Can you stay on the phone with me?”", "Eat or drink something. Elijah’s first step was food and sleep.", "Remove anything you could use to hurt yourself from reach, or ask someone to hold it for you.", "Say the declaration. Do one tiny thing today and tell someone how it went."],
 "Future Me, if you are reading this, you made it through a day when you did not think you could. Thank you for staying.",
 "You do not have to want to live every minute. You only have to get through this one with help.",
 "Today I choose to stay and reach out."),
(45, "Take back the pen from the accuser’s “You’re just like her.”",
 "In Zechariah 3:1–4 the prophet sees Joshua the high priest standing before the angel of the LORD, with Satan at his right hand to accuse him. The LORD says, “The LORD rebuke you, O Satan!” and asks, “Is not this a brand plucked from the fire?” Joshua’s filthy garments are removed, and he is told, “Behold, I have taken your iniquity away from you, and I will clothe you with pure vestments.” The accuser speaks, God answers, and the clothing is changed.",
 ["KROSS"], "Self-talk research suggests that how we address ourselves, with distance and kindness, can reduce the sting of harsh self-evaluation. A small shift in wording can change how a thought lands.",
 ["Write the accusation: “You’re just like her.”", "Write what is the same about you and her and what is different. Be honest and specific.", "Write three choices you made this year that she did not make or could not make.", "Rewrite the pen line: “I am not her. I am my own woman, and I am choosing differently.”", "Say the declaration."],
 "Future Me, I hope you hear that voice less and less. When you do, you know who is holding the pen.",
 "The accuser wants you to write your future in your parents’ handwriting.",
 "Today I choose to write in my own."),
]
