"""Notes of love: a short note from the author to the reader, then an ESV verse that says what the note leans on.
The note is the author's words. The verse is what Scripture explicitly says."""
LV = {
"Zeph 3:17": "The LORD your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.",
"Ps 34:18": "The LORD is near to the brokenhearted and saves the crushed in spirit.",
"Isa 41:10": "Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.",
"Rom 8:38–39": "For I am sure that neither death nor life, nor angels nor rulers, nor things present nor things to come, nor powers, nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord.",
"Jer 31:3": "I have loved you with an everlasting love; therefore I have continued my faithfulness to you.",
"Isa 43:1": "Fear not, for I have redeemed you; I have called you by name, you are mine.",
"Matt 11:28": "Come to me, all who labor and are heavy laden, and I will give you rest.",
"Ps 147:3": "He heals the brokenhearted and binds up their wounds.",
"Lam 3:22–23": "The steadfast love of the LORD never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.",
"Isa 40:31": "but they who wait for the LORD shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint.",
"Phil 4:6–7": "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.",
"Josh 1:9": "Have I not commanded you? Be strong and courageous. Do not be frightened, and do not be dismayed, for the LORD your God is with you wherever you go.",
"Ps 23:1–3": "The LORD is my shepherd; I shall not want. He makes me lie down in green pastures. He leads me beside still waters. He restores my soul.",
"John 14:27": "Peace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid.",
"2 Cor 12:9": "My grace is sufficient for you, for my power is made perfect in weakness.",
"Gal 6:9": "And let us not grow weary of doing good, for in due season we will reap, if we do not give up.",
"Ps 126:5": "Those who sow in tears shall reap with shouts of joy!",
"Rom 5:8": "but God shows his love for us in that while we were still sinners, Christ died for us.",
"1 John 3:1": "See what kind of love the Father has given to us, that we should be called children of God; and so we are.",
"Ps 121:1–2": "I lift up my eyes to the hills. From where does my help come? My help comes from the LORD, who made heaven and earth.",
"Heb 4:16": "Let us then with confidence draw near to the throne of grace, that we may receive mercy and find grace to help in time of need.",
"Ps 40:2": "He drew me up from the pit of destruction, out of the miry bog, and set my feet upon a rock, making my steps secure.",
"Ps 30:5": "For his anger is but for a moment, and his favor is for a lifetime. Weeping may tarry for the night, but joy comes with the morning.",
"Ps 18:19": "He brought me out into a broad place; he rescued me, because he delighted in me.",
"Prov 3:5–6": "Trust in the LORD with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.",
"Rom 15:13": "May the God of hope fill you with all joy and peace in believing, so that by the power of the Holy Spirit you may abound in hope.",
"Ps 119:105": "Your word is a lamp to my feet and a light to my path.",
"2 Tim 1:7": "for God gave us a spirit not of fear but of power and love and self-control.",
"Eph 2:10": "For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.",
"2 Cor 5:17": "Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.",
"Phil 1:6": "And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ.",
"Ps 94:19": "When the cares of my heart are many, your consolations cheer my soul.",
"Ps 62:8": "Trust in him at all times, O people; pour out your heart before him; God is a refuge for us.",
"Ps 73:26": "My flesh and my heart may fail, but God is the strength of my heart and my portion forever.",
"1 Pet 5:7": "casting all your anxieties on him, because he cares for you.",
"Ps 28:7": "The LORD is my strength and my shield; in him my heart trusts, and I am helped; my heart exults, and with my song I give thanks to him.",
"Isa 26:3": "You keep him in perfect peace whose mind is stayed on you, because he trusts in you.",
"Deut 31:8": "It is the LORD who goes before you. He will be with you; he will not leave you or forsake you. Do not fear or be dismayed.",
"Luke 15:20": "And he arose and came to his father. But while he was still a long way off, his father saw him and felt compassion, and ran and embraced him and kissed him.",
"Ps 46:1": "God is our refuge and strength, a very present help in trouble.",
"Ps 131:2": "But I have calmed and quieted my soul, like a weaned child with its mother; like a weaned child is my soul within me.",
"Ps 91:1": "He who dwells in the shelter of the Most High will abide in the shadow of the Almighty.",
"Ps 36:7": "How precious is your steadfast love, O God! The children of mankind take refuge in the shadow of your wings.",
"Ps 86:15": "But you, O Lord, are a God merciful and gracious, slow to anger and abounding in steadfast love and faithfulness.",
"Ps 145:18": "The LORD is near to all who call on him, to all who call on him in truth.",
"Ps 56:3": "When I am afraid, I put my trust in you.",
"Ps 118:6": "The LORD is on my side; I will not fear. What can man do to me?",
"Matt 28:20": "And behold, I am with you always, to the end of the age.",
"Rom 8:31": "What then shall we say to these things? If God is for us, who can be against us?",
"Luke 12:7": "Why, even the hairs of your head are all numbered. Fear not; you are of more value than many sparrows.",
"John 16:33": "I have said these things to you, that in me you may have peace. In the world you will have tribulation. But take heart; I have overcome the world.",
"Rev 21:4": "He will wipe away every tear from their eyes, and death shall be no more, neither shall there be mourning, nor crying, nor pain anymore, for the former things have passed away.",
}
N = [
("I know the first step is the hardest one. You took it. I am proud of you and I am not even in the room.", "Isa 41:10"),
("It is okay to love people who were not safe. It is okay to stop going near them, too. Both can be true tonight.", "Ps 34:18"),
("You are not the sum of what you did to survive. You are the girl who lived through it.", "Isa 43:1"),
("The voice that says it was your fault was never God’s voice. Listen for the One who speaks gentler.", "Rom 8:31"),
("Your body has been on guard for a long time. Today, let it be off duty for one breath.", "Ps 23:1–3"),
("If the youngest part of you only needed a hand to hold, go be that hand.", "Zeph 3:17"),
("You do not need to be calm to practice calm. Show up shaky. It still counts.", "Ps 46:1"),
("You are allowed to take your time with your own list. Nobody is grading it.", "Ps 145:18"),
("Going to the doctor is not a lack of faith. It is how some of the help arrives.", "Ps 147:3"),
("Ten days in. You have already outlasted a lot of promises you made yourself. Keep going.", "Lam 3:22–23"),
("What you learned in that house was real. What you choose now is real too, and it is yours.", "Ps 119:105"),
("You can check a thought before you obey it. That one skill changes more than you think.", "Prov 3:5–6"),
("Somebody gave you names that did not fit. I would like you to try on some that do.", "Isa 43:1"),
("A new name is not a costume. It is a direction you are allowed to face.", "2 Cor 5:17"),
("You were six months old. Say it again slower. You were six months old.", "Ps 36:7"),
("You went back because you were hungry for something good. Now we help you find it where it is safe.", "Luke 15:20"),
("Missing them does not make you weak. It makes you someone who loved. Love is not the problem.", "Ps 94:19"),
("You do not have to remember everything to be healing. Your body is not asking for a file. It is asking for safety.", "Ps 62:8"),
("What you did to live through it was not your whole self. Take responsibility where it is yours and be kind where it is not.", "1 John 3:1"),
("An amends is a long walk with small steps. Take one this week.", "Gal 6:9"),
("You can believe in a world you cannot see without being scared of every shadow in this one.", "Phil 4:6–7"),
("A scare at 2 a.m. is a scare. Sort it, then sleep. You do not have to solve the whole night.", "Ps 121:1–2"),
("You do not have to feel strong to stand on something strong.", "Josh 1:9"),
("Standing looks like feet on the floor and one honest sentence. That is enough today.", "Isa 40:31"),
("Handing something over before you push back is not weakness. It is the order that works.", "1 Pet 5:7"),
("Your anger makes sense. Let it move through your body in a way that does not hurt you.", "Ps 18:19"),
("Somebody should have taken you in sooner. I am glad you are letting Someone do it now.", "Ps 91:1"),
("Forgiveness can take a lifetime. You are allowed to start with one inch.", "Heb 4:16"),
("You can forgive and still keep the door locked. That is wisdom, not bitterness.", "Ps 28:7"),
("Putting on armor in the morning is just remembering whose you are before the day starts talking.", "2 Tim 1:7"),
("You made the best decision a small child could. We can look at it together now without blaming her.", "Matt 11:28"),
("A promise you made to survive can be set down gently. You do not have to rip it off.", "Isa 26:3"),
("A child’s promise comes out like a splinter from a small hand: gently, with the light on, and with someone holding still beside you.", "Ps 147:3"),
("You get to say a new thing out loud in a house with no one to correct you. Try it.", "Ps 40:2"),
("I would like to see you be as patient with yourself as you are with people you love.", "Jer 31:3"),
("A heavy coat of shame was put on you by someone else. It will not take much to slip it off.", "Ps 30:5"),
("A secret told to a safe person gets smaller. Not all at once, but it does.", "Ps 56:3"),
("The pull is real. The pull is also not in charge of you.", "Rom 8:38–39"),
("Letting go of a number, an app, an object: that is not small. That is a door.", "Ps 28:7"),
("You were thirsty. Of course you were. Come drink from somewhere that does not run dry.", "Ps 36:7"),
("Calm should not feel boring. It should feel like a place you can finally unpack.", "John 14:27"),
("You are not guarding the whole house tonight. Somebody else is on watch.", "Ps 121:1–2"),
("You do not have to earn a seat. Come sit. The chair has your name on it.", "Luke 15:20"),
("You have been paying for something that was already paid. You can stop.", "Rom 5:8"),
("If today is dark, call 988. Then call me again tomorrow, in a way: open this book and write one line.", "Ps 34:18"),
("It is true that you and she are different women. Say it until your shoulders drop.", "Isa 43:1"),
("You came from a hard terrain. That does not mean you have to plant the same crop.", "Eph 2:10"),
("There are good things in your line too. Go find them and keep them.", "Lam 3:22–23"),
("Four small changes can be more powerful than one big promise. Start with the one in reach.", "Ps 23:1–3"),
("You did not start this. You get to be the one who ends it, without taking on the blame for the start.", "Rom 8:31"),
("You can pray for people you are not going near. Prayer does not require proximity.", "Jer 31:3"),
("A good prayer can be one sentence long. God is not waiting for a speech.", "Ps 145:18"),
("Nobody taught you. That is not your failing. It is a gap, and gaps can be filled.", "Phil 1:6"),
("You can honor someone from a safe distance, with the truth in one hand and a boundary in the other.", "Ps 62:8"),
("Sign your name to your own promise. You have kept worse ones for other people.", "Josh 1:9"),
("The pattern is easier to see when you stop being ashamed of it. Take a look.", "Ps 119:105"),
("You are not a burden. You are a person who is allowed to need.", "Heb 4:16"),
("Let someone tell you the truth in love. It might be the kindest thing you do for yourself.", "Prov 3:5–6"),
("Today is a fine day to start. So is tomorrow. But today has the advantage of being here.", "Isa 40:31"),
("You can name a chain without being chained. Look at it, then break the weakest link.", "Ps 40:2"),
("Rest is not something you earn after you fix everything. You are allowed it before.", "Matt 11:28"),
("A wave is not the ocean. Ride it. It breaks.", "Ps 46:1"),
("Play the whole tape. Then call someone. Both help.", "Ps 56:3"),
("A better comfort exists. It may take a few tries to find it. Keep trying.", "Ps 23:1–3"),
("An empty hour is a lot easier to fill on purpose than by accident.", "Gal 6:9"),
("The routine you can keep when you are tired is the right routine.", "Lam 3:22–23"),
("A fence is not a wall. It has a gate, and you are the one who holds the key.", "2 Tim 1:7"),
("If you slip, you are still mine to love, and still God’s. Come back the same day.", "Luke 15:20"),
("It is okay to ask where He was. He has heard the question before and He is still listening.", "Ps 145:18"),
("You can ask why without getting an answer. Some of us just get a presence. That is not nothing.", "Matt 28:20"),
("You were not being punished. Hold on to that sentence with both hands.", "Rom 8:38–39"),
("Anger at God means you still think He is worth being angry at. He knows. Keep talking.", "Ps 62:8"),
("You can lay down a case you are tired of carrying. The Judge is fair and He is not asleep.", "Ps 28:7"),
("Waiting in the quiet is not the same as being forgotten.", "Isa 40:31"),
("You are allowed to be quieted like a child on a lap. I wish someone had done that for you. Let Him.", "Ps 131:2"),
("You do not have to call it good to believe He can use it.", "Rev 21:4"),
("I love that you loved them. Now let someone love you back.", "1 John 3:1"),
("You were a child. It was not your job. Take that sentence with you today.", "Ps 18:19"),
("You do not have to know how it ends to take the next small step.", "Prov 3:5–6"),
("You were chosen. Not for your résumé. For you.", "1 John 3:1"),
("Write the letter. You do not have to mail it. It only has to be said.", "Rev 21:4"),
("Grief is love with nowhere to go. Let it sit in the room with you today.", "Ps 34:18"),
("Loving someone from a distance is still loving them. It is also still protecting you.", "Ps 91:1"),
("You are allowed to put the weight down. Your hands were made for more than carrying.", "1 Pet 5:7"),
("You were wanted before anyone hurt you. Say it where you can hear it.", "Jer 31:3"),
("What you have been through can become somebody else’s way out. Only the part you are ready to share.", "Isa 41:10"),
("She has been waiting for you. The woman you are becoming says thank you for not quitting.", "Phil 1:6"),
("You can choose, and you can choose again tomorrow. That is how the line gets bent.", "Rom 15:13"),
("There are people who will inherit something good from you, and you do not have to have children for that to be true.", "Ps 126:5"),
("You did it. You survived. Now we rebuild, and you already started.", "Isa 40:31"),
]
