"""Sources for the 'What research suggests' lines. Written from memory — verify before relying on any citation."""
SRC = {
"PEN": ("Pennebaker & Beall, 1986", "Pennebaker, J. W., & Beall, S. K. (1986). Confronting a traumatic event: Toward an understanding of inhibition and disease. Journal of Abnormal Psychology, 95(3), 274–281."),
"LIEB": ("Lieberman et al., 2007", "Lieberman, M. D., et al. (2007). Putting feelings into words: Affect labeling disrupts amygdala activity in response to affective stimuli. Psychological Science, 18(5), 421–428."),
"BREATH": ("Zaccaro et al., 2018", "Zaccaro, A., et al. (2018). How breath-control can change your life: A systematic review on psycho-physiological correlates of slow breathing. Frontiers in Human Neuroscience, 12, 353."),
"ACE": ("Felitti et al., 1998", "Felitti, V. J., et al. (1998). Relationship of childhood abuse and household dysfunction to many of the leading causes of death in adults: The Adverse Childhood Experiences (ACE) Study. American Journal of Preventive Medicine, 14(4), 245–258."),
"URGE": ("Bowen & Marlatt, 2009", "Bowen, S., & Marlatt, A. (2009). Surfing the urge: Brief mindfulness-based intervention for college student smokers. Psychology of Addictive Behaviors, 23(4), 666–671. See also Bowen, S., et al. (2014). Relative efficacy of mindfulness-based relapse prevention, standard relapse prevention, and treatment as usual for substance use disorders. JAMA Psychiatry, 71(5), 547–556."),
"HOLT": ("Holt-Lunstad et al., 2010", "Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social relationships and mortality risk: A meta-analytic review. PLoS Medicine, 7(7), e1000316."),
"SHAME": ("Tangney & Dearing, 2002", "Tangney, J. P., & Dearing, R. L. (2002). Shame and Guilt. Guilford Press. See also Dearing, R. L., Stuewig, J., & Tangney, J. P. (2005). On the importance of distinguishing shame from guilt: Relations to problematic alcohol and drug use. Addictive Behaviors, 30(7), 1392–1404."),
"AVE": ("Marlatt & Gordon, 1985", "Marlatt, G. A., & Gordon, J. R. (Eds.). (1985). Relapse Prevention: Maintenance Strategies in the Treatment of Addictive Behaviors. Guilford Press."),
"LALLY": ("Lally et al., 2010", "Lally, P., van Jaarsveld, C. H. M., Potts, H. W. W., & Wardle, J. (2010). How are habits formed: Modelling habit formation in the real world. European Journal of Social Psychology, 40(6), 998–1009."),
"GOLL": ("Gollwitzer, 1999", "Gollwitzer, P. M. (1999). Implementation intentions: Strong effects of simple plans. American Psychologist, 54(7), 493–503."),
"GROSS": ("Gross, 2002", "Gross, J. J. (2002). Emotion regulation: Affective, cognitive, and social consequences. Psychophysiology, 39(3), 281–291."),
"NEFF": ("Neff, 2003", "Neff, K. D. (2003). Self-compassion: An alternative conceptualization of a healthy attitude toward oneself. Self and Identity, 2(2), 85–101. See also Neff, K. D., & Germer, C. K. (2013). A pilot study and randomized controlled trial of the Mindful Self-Compassion program. Journal of Clinical Psychology, 69(1), 28–44."),
"HERSH": ("Hershfield et al., 2011", "Hershfield, H. E., et al. (2011). Increasing saving behavior through age-progressed renderings of the future self. Journal of Marketing Research, 48(SPL), S23–S37."),
"BA": ("Dimidjian et al., 2006", "Dimidjian, S., et al. (2006). Randomized trial of behavioral activation, cognitive therapy, and antidepressant medication in the acute treatment of adults with major depression. Journal of Consulting and Clinical Psychology, 74(4), 658–670."),
"BRAT": ("Bratman et al., 2015", "Bratman, G. N., et al. (2015). Nature experience reduces rumination and subgenual prefrontal cortex activation. Proceedings of the National Academy of Sciences, 112(28), 8567–8572."),
"BEETZ": ("Beetz et al., 2012", "Beetz, A., Uvnäs-Moberg, K., Julius, H., & Kotrschal, K. (2012). Psychosocial and psychophysiological effects of human-animal interactions: The possible role of oxytocin. Frontiers in Psychology, 3, 234."),
"PROCH": ("Prochaska & DiClemente, 1983", "Prochaska, J. O., & DiClemente, C. C. (1983). Stages and processes of self-change of smoking: Toward an integrative model of change. Journal of Consulting and Clinical Psychology, 51(3), 390–395."),
"EMM": ("Emmons & McCullough, 2003", "Emmons, R. A., & McCullough, M. E. (2003). Counting blessings versus burdens: An experimental investigation of gratitude and subjective well-being in daily life. Journal of Personality and Social Psychology, 84(2), 377–389."),
"KELLY": ("Kelly et al., 2020", "Kelly, J. F., Humphreys, K., & Ferri, M. (2020). Alcoholics Anonymous and other 12-step programs for alcohol use disorder. Cochrane Database of Systematic Reviews, Issue 3, CD012880."),
"SIEG": ("Siegel, 1999", "Siegel, D. J. (1999). The Developing Mind: How Relationships and the Brain Interact to Shape Who We Are. Guilford Press. (Source of the “window of tolerance” idea.)"),
"BAND": ("Bandura, 1977", "Bandura, A. (1977). Self-efficacy: Toward a unifying theory of behavioral change. Psychological Review, 84(2), 191–215."),
"KAUF": ("Kaufman & Zigler, 1987", "Kaufman, J., & Zigler, E. (1987). Do abused children become abusive parents? American Journal of Orthopsychiatry, 57(2), 186–192."),
"ROIS": ("Roisman et al., 2002", "Roisman, G. I., et al. (2002). Earned-secure attachment status in retrospect and prospect. Child Development, 73(4), 1204–1219."),
"KOLK": ("van der Kolk, 2014", "van der Kolk, B. (2014). The Body Keeps the Score: Brain, Mind, and Body in the Healing of Trauma. Viking."),
"EX": ("Cooney et al., 2013", "Cooney, G. M., et al. (2013). Exercise for depression. Cochrane Database of Systematic Reviews, Issue 9, CD004366."),
"KING": ("King, 2001", "King, L. A. (2001). The health benefits of writing about life goals. Personality and Social Psychology Bulletin, 27(7), 798–807."),
"WADE": ("Wade et al., 2014", "Wade, N. G., et al. (2014). Efficacy of psychotherapeutic interventions to promote forgiveness: A meta-analysis. Journal of Consulting and Clinical Psychology, 82(1), 154–170."),
"WOOD": ("Wood & Neal, 2007", "Wood, W., & Neal, D. T. (2007). A new look at habits and the habit-goal interface. Psychological Review, 114(4), 843–863."),
"RUM": ("Nolen-Hoeksema et al., 2008", "Nolen-Hoeksema, S., Wisco, B. E., & Lyubomirsky, S. (2008). Rethinking rumination. Perspectives on Psychological Science, 3(5), 400–424."),
"KROSS": ("Kross et al., 2014", "Kross, E., et al. (2014). Self-talk as a regulatory mechanism: How you do it matters. Journal of Personality and Social Psychology, 106(2), 304–324."),
"GOLDM": ("Goldman et al., 2005", "Goldman, D., Oroszi, G., & Ducci, F. (2005). The genetics of addictions: Uncovering the genes. Nature Reviews Genetics, 6(7), 521–532."),
"BONN": ("Bonanno, 2004", "Bonanno, G. A. (2004). Loss, trauma, and human resilience: Have we underestimated the human capacity to thrive after extremely aversive events? American Psychologist, 59(1), 20–28."),
"PAGANO": ("Pagano et al., 2004", "Pagano, M. E., et al. (2004). Helping other alcoholics in Alcoholics Anonymous and drinking outcomes: Findings from Project MATCH. Journal of Studies on Alcohol, 65(6), 766–773."),
}
