# Ninety Days of Standing — rewrite, days 31–60.

R2 = {
31: ("Conclusions Drawn Before You Could Speak", "Warfare · Childhood",
 "Scripture uses the language of debts and records, and Colossians 2:14 says Christ canceled the record that stood against us. This book uses a courtroom picture for the beliefs, vows, and conclusions people live by without choosing them. A baby does not make vows, but a body draws conclusions: I am not safe, no one comes, I have to take care of myself. Those can run an adult life. Christians hold different views on how literally to take the picture. What is clear is that Jesus came to set captives free, and you may look honestly at what you have been living by.",
 ["What conclusions do I think my body drew very early?", "How do they run my choices now, especially around addiction and love?", "What is it like to think they do not get the final word?"],
 "Write one conclusion you suspect you live by, in plain words.",
 "Jesus, You carried the record that stood against me. Show me what I have been living by, and show me what You say instead. Amen.",
 "What I concluded in pain does not get the final word. Christ does."),
32: ("The Survival Vow: \"I'll Never Need Anyone\"", "Childhood · Cycle-Breaking",
 "Somewhere in childhood most survivors make a rule to stay alive. I will never need anyone. I will never cry. I will never be like her. It worked then, and it may be running your adult life, including the reason you cannot let anyone hold you. Even a vow made to be the opposite of someone binds you to her, because you are still living in reaction. Jesus told us to stop swearing oaths. Not because He is harsh, but because He knows vows made in fear are heavy.",
 ["What rule did I make to stay alive?", "How old was I when I made it?", "What is it costing me now, especially in recovery and in love?"],
 "Write the vow in the exact words you remember. Under it write what it protected you from.",
 "God, a child made that promise because she had to. Thank You that she survived. Show me what it costs now. Amen.",
 "It kept me alive. It does not get to run me."),
33: ("Releasing a Child's Promise", "Childhood · Warfare",
 "Jesus welcomed children and did not make them earn it. When you find the vow, speak to the child who made it, not to scold her but to release her. Say: I see you. You made that promise because you had to, and it worked. I am the adult now, and you do not have to hold the door anymore. Then, in Jesus' name, release the vow and replace it with something true: I can let safe people in. I can feel and still be okay. I can want things. A woman who learns this breaks a chain that ran before her.",
 ["What would I say to the child who made the vow?", "What new, true sentence do I want to live by?", "Who could witness me saying it aloud?"],
 "Say the release aloud, in your own words, then say your new sentence three times.",
 "Jesus, You welcomed children. Welcome her. Come and bring her home. I take over from here, with You. Amen.",
 "I break the old rule and write a new one with God."),
34: ("Words Over You, and Words You Say to Yourself", "Mother Wound · Cycle-Breaking",
 "Words matter. Many of us can still hear what was said over us: you will never amount to anything, you are just like your mother. We also repeat those words to ourselves, and sometimes to others in our worst hour. You cannot unsay what was said to you, but you can say something truer, and you can stop passing it on. Say it plainly. Repair what you can. Words can wound, and words can bless.",
 ["What was said over me that I still hear?", "What do I say to myself that sounds like them?", "What truer sentence can I say, and to whom?"],
 "Speak one blessing today to someone, or to yourself, in the mirror. Make it specific.",
 "Lord, heal what was said over me. Teach me to speak life where there was death. Amen.",
 "I take back every word spoken in pain. It does not get to run my life."),
35: ("The Shame Covenant: Being Her Daughter", "Mother Wound · Warfare",
 "Shame is not the same as guilt. Guilt says I did something wrong. Shame says I am something wrong. A child of an addicted, absent, or complicit parent often carries shame that is not hers: the family's reputation, the secrets, the smell of the house. Shame hides, and the hiding feeds it. Safe light is what shame cannot stand. That means looking toward Him, not at your reflection in other people's faces.",
 ["What do I feel most ashamed of about my family or myself?", "Who taught me this shame?", "What does looking toward Jesus instead look like?"],
 "Tell one shame-heavy true thing to your safe person. Notice that you are still here.",
 "Jesus, I look to You. Lift the shame I have worn like a coat. Let my face be uncovered. Amen.",
 "I am not the worst thing that happened to me, and I am not the worst thing I did."),
36: ("The Silence Contract: Family Secrets", "Mother Wound · Childhood",
 "Somebody told you not to tell, or no one needed to. Families protect secrets over children, and a mother who allows abuse is often keeping the secret too. Telling should be done with support and never in a way that puts you in danger. If a child is at risk now, whether a sibling, a niece, a nephew, or any child near the person who harmed you, protecting that child comes before the family secret: call the Childhelp hotline at 1-800-422-4453, or 911 in an emergency. Your story matters. You are not the keeper of what was done to you.",
 ["What does my family never say out loud?", "What has the silence cost me?", "What would telling safely look like?"],
 "Write the secret for yourself only, then decide who, if anyone, should hear it, and when.",
 "Father, You see what was hidden. Give me courage and wisdom to speak when it is time and safe. Protect every child involved. Amen.",
 "I am not the keeper of what was done to me."),
37: ("Soul Ties, Plainly: To Her, To Him, To the Substance", "Warfare · Mother Wound · Addiction",
 "\"Soul tie\" is not a phrase found in Scripture. It names a real experience: someone you barely knew, or someone who harmed you, still has a hold on your thoughts. The deepest holds are often to the first people. You may feel bound to your mother and to the substance, and in the same way. What was taken from you was a wrong done to you, not a sin you committed. Being joined to the Lord is the tie that holds.",
 ["Who still has a hold on my mind or body?", "Is it a person, a place, or a substance?", "What would a healthier connection look like, if any?"],
 "List names, or write \"the one whose name I do not know.\" Do not write the stories.",
 "Lord, You are the one I want to be joined to. Loosen what is not of You, and show me what safe connection looks like. Amen.",
 "What God did not join, I do not keep."),
38: ("Releasing the Hold", "Warfare · Cycle-Breaking",
 "You can release your hold on a person and ask God to loosen their hold on you. Hand back what is theirs: the shame, the blame, the voice in your head, their version of you. Take back what is yours: your body, your mind, your peace, your future. Where contact is ongoing, the release is internal and the practical is separate: boundaries, limited contact, someone who can help you hold them. Pressing forward is not pretending. It is a direction.",
 ["What am I handing back today?", "What am I taking back?", "What practical boundary supports the release?"],
 "Pray the release in your own words, by name. Then take one practical step.",
 "Jesus, I release my hold, and I ask You to loosen theirs. I hand back what was never mine. Amen.",
 "I take back what was mine and hand back what was never mine."),
39: ("The Cistern: What the Substance Gave You That She Didn't", "Addiction · Mother Wound",
 "Every addiction promised something real: peace, escape, belonging, courage, rest, a feeling of being held. A baby who was not protected may find that a substance is the first reliable comfort she ever had. That is not an excuse and not a moral failing; it is an explanation, and it points toward what was missing. The cistern is not the sin. Digging your own is. If you can answer what it gave you that you could not get anywhere else, you can find a legitimate source for the need.",
 ["What did it give me that I could not get anywhere else?", "What did it let me stop feeling?", "What was I truly thirsty for?"],
 "Write the job it did. We will replace each one by Day 64.",
 "God, I dug my own cistern because I was thirsty and no one handed me water. Teach me to drink from You. Amen.",
 "I put it down as my savior, my comfort, and my god."),
40: ("The Bond You Mistook for Love", "Mother Wound · Addiction",
 "When harm and love arrive in the same package, your instrument for detecting safety gets miscalibrated. You may be drawn to people who feel like home because they feel like her, or him. Your alarm works; your identifier is off. It is rebuilt by new evidence, slowly, with safe people. If love has always had fear in it, real love may feel boring or suspicious at first. Trust the pattern over time, not the intensity.",
 ["Where has fear been tangled in love for me?", "Who in my life has been consistently safe?", "What evidence would I want before trusting someone?"],
 "List three signs of a safe person. Check it against someone in your life.",
 "Lord, teach me what safe love looks like. Be the standard I measure by. Amen.",
 "I am building new evidence. Familiar is not the same as safe."),
41: ("Control and the Fear of Becoming Her", "Cycle-Breaking · Childhood",
 "If you can manage every variable, nobody can ambush you again. That made sense. It also means you cannot rest, cannot receive, and may be gripping your life so tightly that you squeeze out the good. The fear of becoming your mother can make you control every move, and the fear itself can pull you toward the very patterns you dread. Hypervigilance feels like safety. Sometimes it is a wound wearing competence as a uniform.",
 ["Where am I controlling because I am afraid of being ambushed again?", "What am I afraid will happen if I let go?", "What is one thing I could let be a little messy?"],
 "Choose one thing to loosen your grip on this week, and tell someone you are trying.",
 "Father, You see what I am afraid of. Hold what I cannot control. Let me rest in You. Amen.",
 "I open my hands. Control was never protection."),
42: ("Worth That Isn't Work or Rescue", "Mother Wound · Childhood",
 "I only matter when I am useful. Many children of addicted parents learn to earn love by fixing, caretaking, or staying quiet. Jesus did not shame Martha. He named what she was carrying and invited her to sit. If rest feels like disappearing, ask who you were responsible for rescuing as a child, and whether you are still doing it. Test it honestly: who are you when you produce nothing and rescue no one?",
 ["Who was I responsible for as a child?", "Where do I feel guilty when I rest?", "What would it mean to be loved at rest?"],
 "Do ten minutes of nothing useful today. Notice what comes up. Do not fix it.",
 "Lord, I am anxious about many things. Let me sit at Your feet without earning it. Amen.",
 "I am loved at rest. My worth was never output."),
43: ("Self-Punishment: Paying for Her Sins and Yours", "Addiction · Mother Wound",
 "Part of you decided that as long as you keep paying, it is not unpunished. So you sabotage, deny yourself, stay in what hurts, or relapse after good news. Some of the debt you are paying belongs to people who never paid it. The bill was settled. Continuing to pay may feel like humility while it refuses a payment Jesus already made. Repair with people, where it is safe, is good. Punishing yourself is not repair.",
 ["How do I still punish myself?", "Whose debt am I paying?", "What would accepting grace cost me, and what would it give?"],
 "Do one kind thing for yourself today that you would do for a friend.",
 "Jesus, You already paid. Teach me to receive it and to stop collecting. Amen.",
 "I am not going to keep paying for what He already bought."),
44: ("Wanting Out", "Warfare · Addiction",
 "A death wish is a symptom, not a sin, and not a truth. Elijah, Jonah, Job, and Moses all asked to die, and God's answer to Elijah was food, sleep, a whisper, and a new job, not a rebuke. Early trauma and addiction both raise the risk of wanting out. If that thought has teeth today, call or text 988 (or call 911) before you read another word. You can also tell your sponsor, a counselor, or a friend. This is not weakness; it is the correct use of help.",
 ["When did I first start wanting out?", "What is the pain underneath the wish?", "Who can I tell today?"],
 "If the thought is loud, stop here and call or text 988. If it is quieter, tell one person you trust today.",
 "God, I am tired. Feed me, let me sleep, and send me someone. Keep me here. Amen.",
 "I choose life. I will tell someone."),
45: ("The Accuser's Pen: \"You're Just Like Her\"", "Warfare · Cycle-Breaking",
 "In Zechariah's vision, Joshua stands in filthy clothes with the accuser at his right hand. God does not argue Joshua's case. He rebukes the accuser and says, Remove the filthy garments. I have taken your iniquity away. The accuser says it once, and you say it to yourself for thirty years: you are just like her, you will always be an addict, you ruin everything. Today you take the pen back. A defeated prosecutor does not get to write your story.",
 ["What sentence have I been finishing for the accuser?", "What are the filthy garments I am still wearing?", "What clothing does God offer instead?"],
 "Cross out the sentence in your writing, and write God's sentence over it: \"Remove the filthy garments.\"",
 "Lord, You rebuke the accuser. Take the filthy clothes I have been wearing and clothe me. Amen.",
 "I do not receive that. That is not mine. I take back the pen."),
46: ("Terrain, Not Guilt: What You Inherited", "Mother Wound · Cycle-Breaking",
 "Guilt does not transfer. You are not guilty of your mother's addiction or your father's abuse. But terrain does: patterns, wounds, habits, biology, silence. Research suggests addiction runs in families through both genes and environment, and scientists are still learning how. Exodus 20:5 says consequences reach down generations; Ezekiel 18 says each person answers for their own; the same Bible says God's steadfast love reaches thousands. You did not inherit their sin. You inherited the ground it grew on, and you get to change what grows.",
 ["What has run in my family for three generations or more?", "Where do I see it in me?", "What would it mean to see myself as not guilty of any of it?"],
 "Write one pattern that has run in your family, and one way you are interrupting it.",
 "Father, I cannot change what I inherited, but I can walk differently. Meet me where they could not. Amen.",
 "I did not inherit guilt. I inherited a terrain, and I can change what grows on it."),
47: ("Drawing the Family Line", "Mother Wound · Childhood",
 "Draw it. Three or four generations, both sides. Mark the patterns: addiction, abuse, suicide, early death, mental illness, poverty, abandonment, incarceration, silence. Notice which columns have marks in three or more generations. This is not to blame your family. It is to see clearly, and to also see the good: faith, resilience, a grandmother who prayed. The same line that carried the pain carries gifts, and you get to choose what to carry.",
 ["What patterns do I see?", "What good has also come down my line?", "What do I choose to carry, and what to leave?"],
 "Start the family map on the page, even partially. Add one good thing next to each side.",
 "Lord, show me my family as You see it. Thank You for the good, and help me carry it forward. Amen.",
 "I am looking straight at it. And I am looking at what is good, too."),
48: ("Four Layers: How It Passed to You, and How It Stops", "Cycle-Breaking · Warfare",
 "A pattern can travel four ways. Behavioral: you learn what you saw. Biological: severe stress can shape how bodies respond, and addiction risk runs in families. Systemic: poverty, instability, and lack of support are real walls. Spiritual: Scripture speaks of the enemy and of unhealed wounds, and Christians differ on how to understand this layer. Most people fight one layer and wonder why it did not hold. Work all four: practice new behavior, protect sleep and health, build support, and bring it to God.",
 ["Which layer have I been ignoring?", "What is one small action for each layer?", "Who could help with the one I cannot reach alone?"],
 "Write the four layers and one action for each, small enough to do this week.",
 "God, renew my mind and teach me to work all of it. Give me patience with the pace of change. Amen.",
 "I am working all four layers, not just the one I can see."),
49: ("Where It May Have Started", "Mother Wound · Childhood",
 "For each pattern, ask where it may have started. What was done to your mother? What was done to your grandmother? What did your family lose, flee, or hide? You will not always find an answer, and you are not required to. Understanding your mother's story is not excusing it, and it does not mean you owe her anything. It may help you see that the harm did not start with you, and that some of what looked like cruelty was another wounded person's survival. Hold it with humility.",
 ["What do I know about my mother's own childhood?", "What do I not know, and can I let that be?", "How does understanding differ from excusing for me?"],
 "Write one possible starting place for one pattern. Label it \"maybe.\"",
 "Lord, You know what I cannot find. Bring light where it helps and mercy where it does not. Amen.",
 "Understanding is not excusing. It is seeing clearly."),
50: ("Standing in the Gap for a Family That Didn't Stand for You", "Cycle-Breaking · Warfare",
 "Nehemiah prayed for his people with the words we have sinned, including himself. Daniel did too. Many believers find this meaningful for family patterns: you do not take on their guilt, you agree with God about what is true, and you ask for mercy on your line. It is a practice to consider, not a requirement for freedom or a magic formula. If it does not sit right, skip it and talk to a pastor you trust. It may feel strange to pray for those who failed you; you can do it without defending them.",
 ["Which pattern would I bring to God by name?", "What would it be like to pray without defending anyone?", "What do I want to ask God for the ones who come after me?"],
 "Pray for one pattern in your family in your own words, with no one else listening.",
 "God, I stand in the gap with You for a family that did not stand for me. I tell the truth and ask for mercy. Amen.",
 "I stand in the gap as a daughter of this family. I do not defend it."),
51: ("A Prayer for the Line, Including Whoever Comes After You", "Cycle-Breaking · Warfare",
 "Before any prayer about a family line, remember who is being prayed to: merciful, gracious, slow to anger, abounding in steadfast love. Pray specifically: Father, I confess that ___ has run in my family. I do not defend it or hide it. I bring every vow, oath, and harsh word in my family line to the cross of Christ and ask You to cancel its hold. Place me and whoever comes after me, whether children, nieces, nephews, friends, or people I mentor, under Your protection. Nothing here guarantees an outcome. It hands the outcome to the One who is merciful.",
 ["Which pattern am I praying over?", "Who comes after me, in any sense?", "What am I willing to do differently in response?"],
 "Pray the prayer once for one pattern. Write the date.",
 "Merciful Father, I bring this pattern and my family to You. Protect whoever comes after me. Begin with me. Amen.",
 "I trust Jesus to carry what I cannot, and I will do the work of changing what I can."),
52: ("Agreements We Repeat: \"We're All Addicts\"", "Mother Wound · Cycle-Breaking",
 "It is just how we are. Everybody in my family is like this. We die young. We do not do money. We are all addicts. We say these like fate, and they become fate in the telling. That is not prophecy. It is a pattern, and patterns can end. Proverbs 26:2 says a causeless curse does not land. And Christ has redeemed us (Galatians 3:13 speaks of the curse of the law; applying it to family patterns is a practical application, not the verse's direct subject). Watch the sentences you say over yourself.",
 ["Which of these sentences do I say?", "Who taught them to me?", "What truer sentence could replace each?"],
 "Cross out one family \"we always\" sentence and write a truer one beside it.",
 "Lord, I do not want to speak fate over myself. Put new words in my mouth. Amen.",
 "That was never prophecy. It was a pattern, and it ends."),
53: ("New Behavior, Practiced Badly: Learning What Was Never Modeled", "Cycle-Breaking · Addiction",
 "You can renounce a pattern perfectly and still repeat it, because nobody ever showed you something different. Prayer closes a door. Practice builds a house. You may have to learn calm, boundaries, money, rest, and asking for help like a second language. Find someone who does the thing you never saw: a sponsor, a mentor, a therapist, a friend with a steady life, and get close enough to watch. Practice badly on purpose, because practicing badly is how it is learned. This is also reparenting yourself.",
 ["What behavior did I inherit?", "What is the one I am building instead?", "Who can I watch or learn from?"],
 "Choose one replacement behavior and tell your sponsor, counselor, or a friend what it is.",
 "Father, teach me what I was never shown. Give me patience with myself and with the slow pace of learning. Amen.",
 "I am not just closing a door. I am building a different house."),
54: ("Honor Without Repeating", "Mother Wound · Cycle-Breaking",
 "You can honor your parents and refuse their pattern. Honor is not obedience, agreement, access, or silence. It means you do not degrade them, you do not build your identity on hating them, and you do not hand them your life as payment. If your mother failed to protect you, honoring may look like praying for her from a distance, speaking truthfully of her, and keeping safe boundaries. It is not betrayal to be the one who stopped it.",
 ["What can I genuinely honor about where I came from?", "What am I refusing to carry forward?", "What boundary protects both of us?"],
 "Write one honest good thing about each parent, if there is one. Then one thing you will not repeat.",
 "Lord, You asked me to honor, and You never asked me to be hurt. Show me what honor looks like safely. Amen.",
 "I honor where I came from. I am not repeating it."),
55: ("The Line Stops Here: How You Do Not Carry It On", "Cycle-Breaking · Warfare",
 "Write it, sign it, put it where you will see it. Three things that end with me. Three things that begin with me. Not carrying it on is not one prayer; it is a way of living. It means staying in recovery. Staying in therapy. Choosing safe partners and safe friends. Not handing your pain to people who did not cause it. If you ever raise children, mentor, or love someone vulnerable, you will have done your healing first. And it means blessing the people around you with what nobody gave you.",
 ["Three things that end with me:", "Three things that begin with me:", "Who will I bless this week?"],
 "Write your declaration and sign it. Bless one person aloud, by name.",
 "God, let it stop here, with You and with me. I place whoever comes after me in Your hands. Amen.",
 "I can be the pivot. I am choosing to turn what was meant to bury my family into something that frees it."),
56: ("Twelve Patterns", "Warfare · Mother Wound",
 "Volume II lays out twelve patterns that show up in the lives of people who have been hurt and stuck: being unwanted, early wounds, a false name, isolation, a coping tool, a shame loop, agreements, normalizing, passing it on, derailing the calling, waiting too long, silencing the story. This is a pattern-recognition tool, not a revealed schedule. Scripture also says much of our trouble comes from our own hearts, other people, and a broken world. Use it to notice, not to decide every hard thing was a scripted attack, and never to blame yourself for what was done to you.",
 ["Which of the twelve patterns do I recognize?", "Which is loudest right now?", "What would I need to interrupt it?"],
 "Mark the two patterns that fit you best. Do not analyze. Just notice.",
 "Lord, I do not want to be outwitted, and I do not want to see attacks everywhere. Give me clear eyes. Amen.",
 "I can read the pattern now. Predictable is beatable."),
57: ("Isolation: Your Family Taught You to Be Alone", "Addiction · Mother Wound",
 "Isolation makes almost every harm worse. Abusers isolate. Addiction isolates. Families that keep secrets isolate their children, and a baby who learned that no one comes may still believe it. This is why you need five kinds of people, not one: the one who knows everything, the one further ahead, the one behind you, the one who is just a friend, and the one allowed to correct you. A meeting, a sponsor, a counselor, and a church small group can fill the first of these.",
 ["Which of the five roles is empty for me?", "Where could I find one this month?", "What keeps me from reaching out?"],
 "Write the five roles with one name beside each, or a blank. Choose one blank to work on.",
 "God, You settle the solitary in a home. Put people around me, and give me courage to let them in. Amen.",
 "I will not do this alone. Alone was the plan, not the answer."),
58: ("Who Can Tell You You're Wrong", "Cycle-Breaking · Warfare",
 "A person who cannot be corrected is dangerous, and that includes a survivor who has been wrong-footed so many times she can only defend. If nobody is allowed to tell you you are wrong, that is this month's assignment. Correction from someone who loves you is a gift, and it is uncomfortable. Learn to hear it without collapsing into shame or attacking in defense. Teachable people break cycles; defended people repeat them.",
 ["Who is allowed to tell me I am wrong?", "How did I take it the last time?", "What would help me receive correction without falling apart?"],
 "Ask one trusted person, \"What is one thing I could hear that would help me?\" Listen without answering.",
 "Lord, make me teachable. Give me friends who will tell me the truth with love. Amen.",
 "I would rather be corrected than be impressive."),
59: ("Running Out the Clock", "Addiction · Cycle-Breaking",
 "One of the most common traps is not destruction. It is delay. Someday I will get sober. Someday I will tell the truth. When I am ready. A woman who is going to change soon for thirty years has changed nothing. This is not a call to panic or perfection. It is an invitation to pick one small, real step with a date on it. Every day you wait is a day the pattern keeps running.",
 ["What have I been about to do for years?", "What is the smallest version I could do this week?", "Who will hold me to it?"],
 "Put one date on the calendar for one small step. Tell one person.",
 "Father, redeem the time I have lost, and help me not to waste today. Amen.",
 "Not someday. Today has a date on it."),
60: ("The Trigger Chain: When Abandonment Is the Link", "Addiction · Mother Wound",
 "Relapse is never one moment. It is a chain with six to ten links: the setting, the emotional state, the body, the thought, the justification, the first action, the point of no return, the use, the aftermath. For a daughter of an unprotective mother, the early links are often feeling abandoned, unseen, or dismissed, and the thought, no one cares anyway. Circle link three or four. That is where you intervene, because by link seven you had already decided.",
 ["What does my chain look like, step by step?", "Which link is earliest and detectable?", "What will I do the moment I see it?"],
 "Write your chain and circle the earliest link. Write one action for it, such as a phone call or a walk.",
 "God, help me see the early links, and give me a plan for the moment I feel left alone. Amen.",
 "I fight at link three. Link seven is not a fight, it is a formality."),
}
