# Ninety Days of Standing — rewrite, days 61–90.

R3 = {
61: ("HALT: Hungry, Angry, Lonely, Tired", "Addiction · Cycle-Breaking",
 "Many relapses are several of these stacked, and they are rarely only about the substance. Lonely is the one that hits hardest for a child who was left. Some of what feels like a craving is blood sugar. Some of what feels like despair is sleep. Run the check three times a day: what is loudest, and what can I do about it in the next hour? Feed yourself, rest, call someone, calm your body. That is how you give yourself what no one gave you.",
 ["Which of the four is loudest right now?", "What can I do about it in the next hour?", "Who could I call when it is lonely?"],
 "Eat something real and drink water. Set a bedtime and put the phone out of reach.",
 "Lord, You give Your beloved sleep. Help me care for myself like someone worth caring for. Amen.",
 "I will feed, rest, call, and calm before I decide anything."),
62: ("The Craving Wave", "Addiction",
 "A craving often peaks and fades within fifteen to thirty minutes, even when it does not feel that way. Say it aloud: I am having a craving. It will peak and pass. Set a timer. Change your body: cold water, twenty pushups, walk outside. Change your location. Call, do not text. Eat and drink. Pray short. Play the tape forward. You only have to outlast a wave. A body that never learned to self-soothe can learn it, one wave at a time.",
 ["Who are the three numbers I will call, memorized?", "What changes my body fastest?", "What is my short prayer?"],
 "Write your three numbers on a card and tape one copy where you will see it.",
 "Jesus, I do not have to win this hour, only this wave. Give me a way out and the sense to take it. Amen.",
 "I only have to outlast a wave. It always breaks."),
63: ("Play the Tape Forward: Who Else Pays", "Addiction · Cycle-Breaking",
 "Not the first hour. The forty-eighth. The call you would have to make. The face you would have to look at. Write it now, while you are clear, because you will not be able to write it in the moment. Add the people who would pay: your sponsor, your friends, whoever looks up to you, whoever you hope to be a different example for. Include where the naloxone is if opioids are in your history. This is not a scare tactic. It is a gift to your future self.",
 ["If I use today, what happens within forty-eight hours?", "Whose face do I see?", "What do I most want to protect?"],
 "Write your tape on a card. Keep it where you keep your keys.",
 "God, I want to keep what You have given me. Let me remember it when I cannot think. Amen.",
 "I decide this now, while I can still think."),
64: ("Replace the Function: What Your Mother Couldn't Give", "Addiction · Mother Wound",
 "You cannot leave a vacancy. For every job the substance did, find a legitimate replacement. It numbed pain, so find a place to put pain: therapy, a journal, a friend. It gave energy, so find food, movement, sleep. It gave belonging, so find a meeting or a church group. It quieted your head, so find music, a walk, or silence. It held you, so find real human touch, safe and chosen, and the comfort practices you are learning. God invites us to what satisfies.",
 ["What jobs did it do for me?", "What legitimate replacement could do each job?", "When will I do it?"],
 "Complete the job and replacement list from Day 39. Choose one to start today.",
 "Lord, I do not want to leave an empty room. Fill it with what is good. Amen.",
 "I am not removing something. I am replacing it."),
65: ("Fill the House", "Warfare · Cycle-Breaking",
 "Jesus tells a story of a swept house left empty (Luke 11:24-26), and the last state was worse than the first. Whatever your view of the spiritual side, the practical truth stands: when something leaves your life, something must take its place. Where fear lived, put love. Where shame lived, put belonging. Where craving lived, put satisfaction. For a home, this can mean worship music, a routine, a regular meal, a table prayer. Overcome with good, in small and visible ways.",
 ["What am I emptying that needs filling?", "What small good thing could fill it?", "What would my \"filled\" home feel like?"],
 "Choose one new, simple good habit for your home this week. Start tonight.",
 "Holy Spirit, fill every room that has been emptied. Leave nothing vacant. Amen.",
 "Holy Spirit, occupy every room. Leave nothing empty."),
66: ("Architecture, Not Willpower", "Addiction · Cycle-Breaking",
 "Freedom is architecture. Same wake hour. Sunlight in the first hour. Prayer out loud. Protein and water before caffeine. Movement. A HALT check. A meeting or a call. Same bedtime, phone out of the room. Pick the three that matter most and let the others wait. If you did not grow up with structure, you are building it from scratch, and that is hard and holy. Sleep affects almost everything else.",
 ["Which piece of daily structure am I missing most?", "What is the smallest version I could try?", "What would I need to ask someone for?"],
 "Choose three anchors for your day and write them where you can see them.",
 "God, You are a God of order. Help me build a day I can stand on. Amen.",
 "Freedom is architecture. I am building the walls."),
67: ("Boundaries With Family, With Her, With Him", "Mother Wound · Warfare",
 "Boundaries that exist only in your heart are wishes. Block the number. Change the lock. Tell the relative who relays messages to stop. Decide in advance what you will do when they reach out, because they usually do right when you get peaceful. Decide what contact with your mother or father, if any, looks like, and what is non-negotiable (no substances, no abuse, no guilt trips). A boundary is a property line, not a punishment, and you do not have to explain it forty times.",
 ["What boundary do I need to set?", "How will I enforce it this week?", "What will I do when they push back?"],
 "Set one real-world boundary today. Write the exact sentence you will use.",
 "Lord, give me a firm yes and a firm no, and keep my heart open to those who are safe. Amen.",
 "I am not explaining it forty times. It is a property line."),
68: ("When You Fall", "Addiction · Cycle-Breaking",
 "Having a plan is not permission. Not having one gives the fall a runway. Stop at the first one. The fall is the first act, the ruin is the decision afterward. Tell someone within the hour. Have naloxone in the house if opioids are in your history, and tell a person who can help. Do not throw away ninety days over one day. Then find the link you missed and write it down. Shame says hide; recovery says tell. The identity is in the rising.",
 ["What is my written plan for the day I fall?", "Who will I tell within the hour?", "What will I not do afterward?"],
 "Write the plan and share it with one person. Keep a copy somewhere you can find it.",
 "Lord, when I fall, You are my light. Give me someone to call. Amen.",
 "The identity is in the rising, not in never falling."),
69: ("Where Was He When You Were Six Months Old?", "Childhood · Warfare",
 "Hagar, a mistreated servant who had run away, is the first person in Scripture to give God a name, and it is the God who sees. He was near the brokenhearted, in the room, not outside it, not arriving later. That is harder than absence, because it means He saw. It is also better than absence, because it means you were never alone, even when you felt completely alone. I do not know why He did not stop it. I know He saw, and I know He kept the record of every tear.",
 ["Where do I most need to know He was?", "What do I feel when I imagine Him in that room?", "What do I want to say to Him?"],
 "Say aloud, \"You saw me.\" Sit with whatever comes.",
 "God of seeing, I did not know You were there. Show me, gently, how You were. Amen.",
 "He was in the room. I was never in there by myself."),
70: ("Why Didn't He Stop It?", "Mother Wound · Childhood",
 "God made a world with real agency, because love that cannot be refused is not love. That means people can choose evil, and He does not routinely override the will He gave. He did not cause it, want it, or approve it. He hated it. That is an explanation, not a comfort, and I will not pretend it is the same. But hear how He answers in Isaiah: Can a woman forget her nursing child? Even these may forget, yet I will not forget you. He knows that mothers fail. And He says: I will not.",
 ["What do I most need to ask Him?", "What do I do with the part that has no answer?", "How does it feel to hear Him say, \"I will not forget you\"?"],
 "Write the question you have never asked, and leave it open.",
 "Father, I do not understand. I trust Your character where I cannot trace Your hand. Stay with me. Amen.",
 "I trust His character where I cannot trace His hand."),
71: ("Not Punishment", "Childhood · Warfare",
 "The disciples asked whose sin caused a man's blindness, and Jesus rejected the whole premise. What was done to you as a baby was not the sentence for anything you did or were. Your suffering was not invoiced to you. Jesus paid the bill and God does not double-bill. Grief is not proof of a curse, and hardship is not a verdict. If you have been secretly wondering what was wrong with you that this happened, nothing was.",
 ["What have I secretly believed I was being punished for?", "Where did I learn that suffering means I did something wrong?", "What would it mean to let that go?"],
 "Write the sentence you believe, then cross it out and write, \"This was not punishment.\"",
 "Jesus, You refused the lie that suffering is always a sentence. Take mine out of that frame. Amen.",
 "He is not punishing me. There is no condemnation."),
72: ("Angry at God", "Warfare · Mother Wound",
 "Scripture preserves complaints. Jesus quoted a psalm of abandonment from the cross. Job accused God and God said Job had spoken rightly of Him. Lamentations is grief laid out before God, and God kept it in the canon. He can handle your rage. What He cannot work with is your distance. Say it to Him directly, even the part that says, where were You when I was a baby and no one protected me?",
 ["What have I never said to God directly?", "What am I afraid will happen if I do?", "What would it look like to say it today?"],
 "Write or say it to God, unedited, for two minutes.",
 "God, here it is, all of it. I am bringing it to You instead of holding it against You. Amen.",
 "I bring it to Him instead of holding it against Him."),
73: ("Taking Your Case Out of Court", "Warfare · Mother Wound",
 "As long as you hold a verdict against God, you cannot receive from Him. You do not have to stop having questions. You have to stop having a verdict. And handing over your case against your father and your mother is not letting them off. It is God taking a weight that was killing you. He is the judge, and He sees everything, including what never reached a human court. Some people never face anything on earth. That is not the end of the story.",
 ["What verdict am I carrying against God?", "What case am I carrying against my father and mother?", "What would it feel like to hand each to Him?"],
 "Write \"I withdraw the verdict\" beside the one you are ready to put down.",
 "God, I keep my questions open and I withdraw my verdict. The case is Yours. Amen.",
 "I keep the questions open. I withdraw the verdict."),
74: ("The Quiet Stretch of Faith", "Warfare · Addiction",
 "Elijah was suicidal and looked for God in wind, earthquake, and fire, and God came in a thin silence, after He fed him and let him sleep twice. Food, sleep, then the whisper. Sometimes the silence is not rejection. Sometimes you are exhausted and He is feeding you first. In early recovery you may have no energy for a long quiet time, and that is okay. A few honest sentences are prayer.",
 ["Have I been asking for a whisper when I need food and sleep?", "What would feed me today?", "What is one small way to wait?"],
 "Eat something and rest ten minutes before praying. Then pray one sentence.",
 "Lord, I am tired. Feed me, and then speak. Amen.",
 "Silence is documented. It is not rejection."),
75: ("Rocked Like a Weaned Child", "Childhood · Mother Wound",
 "Noise was safety. If it was quiet, you could hear them coming, and you had to feel it. So silence may feel like danger before it feels like peace. Start with two minutes. Eyes open if closed feels unsafe. When your mind runs, say later and come back. The coming back is the prayer. The psalmist describes a soul quieted like a weaned child with its mother. You may not have had that mother. You can ask for it from the One who comforts like one.",
 ["How long did I sit, and what came up?", "What does silence feel like in my body?", "What would it be like to be quieted like a child with her mother?"],
 "Sit two minutes today. Feet on the floor. Say once, \"Jesus, I am here.\" Then nothing.",
 "Father, I do not have to say anything. I am not leaving. Quiet my soul like a child with her mother. Amen.",
 "I am here. He does not have to say anything. I am not leaving."),
76: ("All Things, Honestly", "Warfare · Cycle-Breaking",
 "It does not say all things are good. It says God works in all things toward good, and the next verse defines that good as being made like Christ. It is not a promise that your story will have a satisfying plot, and it is not meant to be said to someone in fresh grief. It is a promise that nothing in your story, including what happened when you were a baby and the years in your addiction, is unusable in His hands. It was not good. It will not be wasted. Those are different things.",
 ["What do I need Him to use rather than explain?", "What have I been tempted to call good that was not?", "What do I hope He will redeem?"],
 "Write one thing that was not good, and one thing you are asking Him not to waste.",
 "God, I will not call it good, but I ask You not to waste it. Use it. Amen.",
 "It was not good. It will not be wasted. Those are different."),
77: ("You Were Not Their Savior", "Mother Wound · Addiction",
 "If you lost someone to addiction, you may carry the idea that you should have saved them. You may also carry it about your mother. You were not their savior. You were a child, then a sister, then a daughter, then a friend. You lost them because addiction is lethal, because they were sick, and because the world they were in was built to fail people like them. None of those were yours to control. This page is for Brandi, and for the mother you could not save. Grief is allowed here.",
 ["What did I do for them?", "What do I keep telling myself I should have done?", "Was it truly in my power at that age and in that condition?"],
 "Write one thing you did that was love. Let that be enough for today.",
 "God, I loved them and I was never their God. Hold them, and hold me. Amen.",
 "I loved them. I was never their God. That was never my job."),
78: ("Who Was Responsible", "Mother Wound · Addiction",
 "List what actually contributed: their choices, the people who hurt them, the ones who sold to them, the systems that turned them away, the disease itself, the patterns they were born into, and your own choices. Then count how many lines have your name on them, and how many do not. The point is not to avoid responsibility. It is to put it where it belongs, so grief can be grief and not an endless trial.",
 ["Who or what was responsible for each part?", "Which lines have my name, truthfully?", "What age and condition was I in then?"],
 "Fill in a list of responsible parties. Stop when it is done.",
 "Lord, You are a stronghold for the oppressed. Help me put the weight where it belongs. Amen.",
 "I judge my past self with resources she did not have. I stop."),
79: ("Hope Without Certainty", "Warfare · Mother Wound",
 "I am not God, and I will not pretend to know where she is. But addiction is not the unforgivable sin, God judges the heart and not the manner of death (1 Samuel 16:7), and Romans 8:38-39 lists death first among the things that cannot separate us from His love. A cry does not have to be eloquent: the thief on the cross got one sentence (Luke 23:42-43). You can hope, legitimately, without lying to yourself. Hope is not certainty, and you do not need certainty to stop tormenting yourself.",
 ["Can I hope without needing to know?", "What does it feel like to place them in God's hands?", "What would help me leave them there?"],
 "Say aloud, \"I do not know, and I hope.\" Sit with it.",
 "God, You are there, even in Sheol. I put them in Your hands. I do not know everything, and I hope. Amen.",
 "I am putting them in the hands of someone kinder than the people who scared me."),
80: ("Not a Debt", "Addiction · Cycle-Breaking",
 "Their death, or their harm, did not buy your life, and there was no exchange. If you build your recovery or your work as restitution for being the one who lived, you will never be able to stop, and it will never be enough, because guilt does not close accounts. Build it because it is right, and because you love them. Their name goes on it as a dedication, not a debt. A survivor does not owe her life as payment.",
 ["Am I building out of love or out of guilt?", "How can I tell the difference?", "What would change if it were a dedication, not a debt?"],
 "Write the sentence, \"My life is not a payment.\" Say it aloud once.",
 "Father, I did not receive a spirit of slavery. Free me from owing. Let me carry their name in love. Amen.",
 "Their name goes on the work as a dedication, not a debt."),
81: ("The Letter: To Her, To Him, To Brandi", "Mother Wound · Childhood",
 "Jesus wept at a grave He was about to open. Grief is not weak faith. Write a letter to the one you need to write to: your mother, your father, or Brandi. Everything: the love, the rage, the why did you not protect me, the I am sorry, what you never said. You will not send it. Then write the indictment you have been running against yourself, and, if you can do it safely, burn it outside and watch it go.",
 ["What I have never said to her:", "What I have never said to him:", "What case have I been prosecuting against myself?"],
 "Write the letter. Then, if you wish and it is safe, burn the second page.",
 "Jesus, You wept. Weep with me. Let me say it all, and let it go. Amen.",
 "I am not letting them go. I am putting them down in better hands."),
82: ("Grief Is Not a Relapse", "Addiction · Mother Wound",
 "Grief that is not given a place will take one, usually as rage, shutdown, or a craving. Know your dates: birthdays, anniversaries, the day you got the call. Plan for them instead of being ambushed. Have one person to call on those days. And stop calling it a setback when it is love with nowhere to put itself. You may grieve more than a death: the childhood you did not get and the mother you needed.",
 ["What are my hard dates?", "Who will I call?", "What gentle ritual could I make for what I am grieving?"],
 "Put the next hard date on your calendar with a name and a plan.",
 "Lord, comfort me as You promised. Let me grieve without breaking. Amen.",
 "I am allowed to grieve, and I am allowed to have a good day."),
83: ("Letting the Living Go: If Your Mother Is Still Here", "Mother Wound · Warfare",
 "There are four kinds of letting go: release to God with them still in your life, boundary, distance, and no contact. You are not obligated to give unlimited access to someone who is actively harming you, and no Scripture requires it. If your mother is living, decide which kind fits now and what would change it. If she is gone, you may still be letting go of the mother you needed and the apology you may never hear. You can love someone and not be their savior.",
 ["Which of the four fits my relationship with my mother now?", "What would have to change for that to change?", "What am I grieving that has no funeral?"],
 "Write which kind you are choosing, the cost, and the next step.",
 "Father, You see her. Go where I cannot go. Help me love without losing myself. Amen.",
 "Loving someone does not require me to die with them.",
 ("Luke 5:16", "But he would withdraw to desolate places and pray.")),
84: ("The Release", "Warfare · Mother Wound",
 "Say it: I release ___ into the hands of God. I am not their savior, judge, jailer, or payment. What was good, I keep. What was mine, I take back. What was theirs, I return. I forgive them, and I am not available for more harm. Then replace the space on purpose, because holes get filled by whatever is nearest. Put something good in it: a person, a practice, a purpose.",
 ["Who am I releasing?", "What am I keeping, and what am I returning?", "What will I put in the space?"],
 "Write the release by name, and read it aloud. Then do one small good thing in the space.",
 "God, I release them into Your hands. Sustain me. Amen.",
 "Out of my hands, into His. His are better than mine ever were."),
85: ("Known Before You Were Formed", "Childhood · Mother Wound",
 "God knew you before you were formed, and what was done to you never canceled what He had in mind for you. Scripture says He knitted you together in your mother's womb. Your mother's womb was not the whole story, and she was not the one who made you; He was. I cannot tell you the harm was aimed at your calling. I do not know that. But the place that hurt most is often the place you understand best, and that can become a place you help from.",
 ["What was hurt earliest, and what did it try to take?", "What do I see when I picture myself as known and wanted by God?", "What does it change?"],
 "Look at a photo of yourself as a child. Say, \"Known and wanted by God.\"",
 "Father, You knitted me together. Let that be the final word over me. Amen.",
 "God's knowing came first. The harm does not get the final word."),
86: ("The Wound as a Door", "Warfare · Cycle-Breaking",
 "Joseph was starved of family and put in charge of feeding families. Moses was drawn out of the water and sent to draw a nation out. Often, the fruit comes in the shape of the wound. Not always, not automatically, and never as a reason to call the wound good. Look at yours as a map, not a verdict. The so that is the whole point: you were not comforted to feel better only. You were comforted so you would know the road for someone else.",
 ["Where do my wound and my compassion overlap?", "Who might need exactly what I know?", "What is one small way I could offer it?"],
 "Complete the sentence: \"I am the one who ___ for the people who ___.\"",
 "God of all comfort, comfort me, and let me comfort someone else with what You gave me. Amen.",
 "My wound does not have to stay a wound. It can become a door."),
87: ("Sent, Not Special", "Warfare · Cycle-Breaking",
 "Chosen is not a rank. It is an assignment with a destination. Scripture uses the language of being chosen of every believer, not only the dramatic ones. Many people in Scripture were marked early, isolated, delayed, misunderstood, and broken in a specific place before they were used. The cost is real: lost people, delay that looks like denial, being misunderstood by good people. It does not mean God likes you more. Your assignment may start with simply being the one who stays in recovery.",
 ["What has this already cost me?", "What am I still unwilling to pay?", "What is the assignment right in front of me?"],
 "Name the assignment closest to you today. Do one small thing for it.",
 "Jesus, You chose me and sent me. Keep me humble and faithful. Amen.",
 "Chosen does not mean liked more. It means sent."),
88: ("Two Roads: Carrying It On, or Ending It Here", "Cycle-Breaking · Addiction",
 "One possible future is the woman who knew what she was for, told people about it, and never started, while the pattern ran on. Another is the same woman, with the agreements she made in pain released, the pattern interrupted, five people who truly know her, and someone helped because of what she lived. Neither is guaranteed. Choices are what you have, and you get to make a small one today. If this page pulls you down, close it and call someone.",
 ["If this week repeats 260 times, where am I in five years?", "Who else is affected by my choices?", "What is the one small step I can take today?"],
 "Take the small step you wrote. Then tell one person.",
 "God, I choose life, for me and for those who come after me. Start small with me today. Amen.",
 "I am going to do it, scared and imperfect and on a date."),
89: ("Steward, Not Survivor: What You Pass On Without Children", "Cycle-Breaking · Warfare",
 "Victim: this happened to me. Survivor: and I am still here. Steward: and now it belongs to God and it is for somebody else. You do not need children to pass something on. You pass it on to the people who watch how you live: friends, nieces, nephews, coworkers, people in a meeting, people you mentor. Paul remembered a line of faith that passed through women, a grandmother and a mother. You can start a line of faith and honesty, whether or not you ever raise a child. What you pass on is how you live.",
 ["What have I learned that is worth passing on?", "Who is watching how I live?", "What does passing it on look like in an ordinary week?"],
 "Share one honest, hopeful truth with someone who is watching you this week.",
 "Lord, make me a steward of what You have taught me. Let what I pass on be good. Amen.",
 "I know the road because I was on it. That is the qualification."),
90: ("The Commission", "Warfare · Cycle-Breaking · Addiction",
 "Nehemiah rebuilt a wall with one hand on the work and the other on the weapon. That is the picture: build and stand at the same time. Revelation 12:11 says they conquered by the blood of the Lamb and the word of their testimony, and your testimony is whatever is true, told at your own pace to safe people. Read the whole page aloud, standing. Then set the next date and run it again, because you can only see the next layer from ground you already took. You are not finished. You are on your way, and you are not carrying it on.",
 ["What is different about me than on Day 1?", "What is the next layer I can see now?", "Who will walk with me into it?"],
 "Sign it, date it, and tell one person. Then pick your next date.",
 "Father, thank You for ninety days of honesty. Keep me standing, keep me building, and keep me Yours. In Jesus' name. Amen.",
 "I am the woman God chose to stand and to build. Not someday. Today. The line stops here."),
}
