# Ninety Days of Standing — rewrite for a daughter of an addicted mother who was abused as an infant,
# is in recovery from her own addiction, is not a mother, and wants to end the pattern.
# day: (title, lens, teaching, [3 prompts], soft action, prayer, declaration)   [days 1-30]
# Optional 8th element: (scripture reference, ESV quotation) to replace the verse.

R1 = {
1: ("The War Started Before You Had Words", "Mother Wound · Warfare · Addiction",
 "You have told me that your father abused you when you were six months old, and that your mother, who carried her own trauma and addiction, allowed it. You had no words, no memory, and no defense. Scripture says the struggle is real and bigger than flesh and blood, and Jesus names the thief's work: to steal, kill, and destroy. What was done to you was never God's will. You are not crazy for living with effects you cannot explain, and you do not need a single memory to be believed here.",
 ["What do I already know about my beginning, and how do I know it?", "How does it feel to hear that I do not need to remember it?", "What would it mean to stand against it instead of just surviving it?"],
 "Write one sentence that starts, \"What happened to me was wrong because…\" Say it aloud once.",
 "Jesus, I did not choose the war I was born into. Stand with me in it. Name the harm as harm, and be near me while I look. Amen.",
 "What was done to me was wrong, and God was never on its side."),
2: ("Telling the Truth About Both of Them", "Mother Wound · Warfare",
 "Families protect the ones who did the harm. Silence says the father's actions and the mother's failure to protect are not to be named. Light is not exposure for its own sake. It is one safe person who will not panic, gossip, or use it against you. Warfare begins small: saying out loud to one human being that your father hurt you and your mother did not protect you, and watching what the fear does when it is spoken.",
 ["What have I never said out loud about my father or my mother?", "Who has earned the right to hear the unedited version?", "What do I need from them when I say it?"],
 "Name your one person and choose a day this week. Start with one true sentence. You do not have to tell it all.",
 "Father, I have kept this in the dark to survive. Give me one safe person and the courage to say one true thing. Amen.",
 "I do not have to carry this alone, and I do not have to carry it in secret."),
3: ("Both Hands: What Was Done and What You Did", "Mother Wound · Addiction",
 "A baby has zero responsibility for what happens to her. None. And later, in your own addiction, some of what you did was your own doing, and some of it hurt people. Both are true at once. Holding only the first makes you a permanent victim. Holding only the second makes you your own warden. Your mother had both hands too: she was hurt, and she failed you. You can see that without excusing it. You need both hands to carry this, and God carries the rest.",
 ["What was done to me that was never mine to carry?", "What did I do that was mine to own?", "What would it be like to see my mother with both hands without excusing her?"],
 "Make two columns: \"Done to me\" and \"My part.\" Fill one line each. Stop there.",
 "Lord, give me honest hands, one to set down what was never mine, one to own what was. Hold the rest. Amen.",
 "I can tell the truth about what was done to me and what I did, and still be held."),
4: ("The Accuser Says It Was Your Fault", "Warfare · Mother Wound",
 "Children, even tiny ones, take blame. When the people who should protect you do not, a child concludes that she must not be worth protecting. The accuser loves that conclusion and says it in your own voice: you were the problem, you are too much, no one would help. Conviction names one specific thing with a way out. Condemnation names your whole self with no door. A baby cannot be guilty of what was done to her, and God does not condemn the one who was harmed.",
 ["What does the accuser say about why this happened to me?", "Is it specific with a way out, or sweeping with no door?", "What would Jesus say to that sentence?"],
 "When the sentence shows up today, answer it once with Romans 8:1 and move on. Do not debate it.",
 "Jesus, You stand with the harmed. Silence the voice that blames the baby. Amen.",
 "Conviction gives me a door. Condemnation is not from God."),
5: ("A Body That Learned Early", "Childhood · Addiction",
 "Your body learned things before you had words: that the world is not safe, that the people meant to protect you may not, that relief has to be found. Those lessons live in the nervous system, not in stories, which is why you can feel them without remembering anything. Fight, flight, freeze, and fawn were survival strategies, and a body that learned them that early may reach for relief quickly. That is not weak faith. It is a body doing a job it learned young. God keeps count of every tear.",
 ["Which survival response is my default?", "How does it show up in my cravings, my relationships, my sleep?", "What did it save me from?"],
 "Put a hand where your body holds it most. Say, \"You kept me alive. You can rest now.\"",
 "God, You saw every tear. Thank You for the body that kept me alive. Teach it that it does not stand watch alone. Amen.",
 "My body is not broken. It is remembering, and it can learn a new rhythm."),
6: ("Where the Baby Lives", "Childhood · Mother Wound",
 "Trauma has an age, and for you the youngest part may be pre-verbal. You cannot interview a baby; you can only hold her. That is what comfort is: warmth, rocking, a steady voice, a blanket, a hand on the chest. You do not have to dig for anything. You only have to give the youngest part of you what she needed and did not get. God promised to comfort like a mother comforts, and He means the kind of mother who stays.",
 ["Where in my body does the oldest fear live?", "What does she need that is simple: warmth, quiet, being held?", "What would it feel like to give it?"],
 "Wrap yourself in a blanket for three minutes. Say, \"I am here. I will not leave you.\"",
 "Father, You comfort like a mother who stays. Come to the youngest part of me and hold her. Amen.",
 "I can comfort her without going back into what hurt her."),
7: ("Six Resets for an Old Alarm", "Warfare · Addiction",
 "A body that was never taught to calm itself will reach for something that does it. Before you ask whether something is spiritual, calm the alarm. Breathe in four, hold seven, out eight. Name five things you see. Cold water on your wrists. Push the wall for ten seconds. Say, \"This is memory, not danger.\" These do not replace prayer. They are what you learn instead of the thing you used, and they are what make prayer possible when your chest is on fire.",
 ["Which reset helps me most?", "When is my alarm loudest, and what do I usually reach for?", "What small change could make the reset easier to reach?"],
 "Pick one reset and practice it three times today before you need it.",
 "Lord, I do not have to fight with a racing heart. Slow me down and be near. Amen.",
 "I have tools. I am not at the mercy of my own alarm."),
8: ("Inventory: Mother, Father, Me", "Mother Wound · Addiction",
 "Titles only, no stories. Three lists: what happened to me (what my father did, what my mother did or did not do), what I used and what it did, and the patterns I am afraid of repeating. Ten lines at most. Then circle the one you skipped. That is where the work is, and we are coming back to it slowly. You are allowed to leave a list blank today.",
 ["What are the main titles under what happened?", "What are the titles under what I used?", "What pattern am I most afraid of repeating?"],
 "Write your three lists. Circle the skipped one. Do not write about it yet.",
 "God, search me, not to punish me but to lead me. Show me where to start, and not more than I can hold. Amen.",
 "Naming it is the beginning of the end of its power over me."),
9: ("Medical Before Mystical", "Warfare · Addiction",
 "Before you decide something is demonic, ask a doctor. Early trauma changes how the body handles stress, and addiction changes the brain, so sleep, mood, anxiety, and craving can feel like attack. Look for a therapist trained in trauma (approaches like EMDR or trauma-focused therapy are options), a doctor who understands addiction, and a recovery community. If you are physically dependent on alcohol, benzodiazepines, or barbiturates, withdrawal can be deadly; do not stop alone. Prayer and medicine are not enemies.",
 ["What have I been calling spiritual that might also be physical?", "What appointment have I been avoiding?", "Who could go with me?"],
 "Make the call or book the appointment today. If you are in crisis, call or text 988.",
 "Lord, You made healers. Give me the courage to ask for help and the humility to take it. Amen.",
 "Treating my body is stewardship, not a lack of faith."),
10: ("A Date, and a Reason Bigger Than Fear", "Addiction · Cycle-Breaking",
 "Someday is a comfortable word. A date is a decision. If you are ready to stop using, pick the date, clear the first seventy-two hours, remove what needs removing, and tell three people. Add the reason: you do not want to carry on what was handed to you. That reason is bigger than fear, and it can hold you when a craving is loud. If medical detox is needed, do it first; call SAMHSA at 1-800-662-4357.",
 ["What date am I willing to write down?", "Who are my three people?", "What is the reason that is bigger than my fear?"],
 "Write the date, three names, and the reason on one card.",
 "Father, I am tired of someday. Give me a date, a plan, people, and a reason that holds. Amen.",
 "I am not waiting for someday. I am choosing a day."),
11: ("What Your Mother Taught Without Words", "Mother Wound · Childhood",
 "Trauma does not only hurt. It teaches. Without a word, you may have learned that love comes with harm, that people who should protect you will not, that you are not worth protecting, and that relief is something you find on your own. Those lessons were installed when you were too small to argue. You may be living by house rules from a house that burned down. The work is not to hate the lessons but to notice them.",
 ["What did I learn about love and safety before I could speak?", "Which lesson shows up in my relationships or my addiction?", "What would I tell a child who had learned it?"],
 "Underline the lesson that frightens you most. Write beside it, \"I was taught this. I can unlearn it.\"",
 "Jesus, You are the truth. Show me the lessons I took on, and replace them with what is real. Amen.",
 "I learned it under pressure. I am allowed to unlearn it."),
12: ("Lie, Evidence, Truth: \"I Wasn't Worth Protecting\"", "Warfare · Mother Wound",
 "Paul's weapons are truth, arguments answered, thoughts brought to Christ. Take the lie: I was not worth protecting. Ask who taught it. The evidence you have used is that no one stopped it. But a person's failure to protect you says everything about them and nothing about your worth. Now find one piece of evidence against it, and write the truth you choose instead. God is called the defender of the helpless. Do not give the Sunday School answer. Give the real one.",
 ["Lie one, in my own words:", "One piece of evidence against it:", "The truth I choose, and where Scripture says it:"],
 "Say the truth aloud to the mirror once today. It will feel awkward. Do it anyway.",
 "Lord, I bring this thought to You instead of agreeing with it. Teach me what is true. Amen.",
 "I am not arguing with a lie. I am replacing it."),
13: ("The Names You Were Given", "Childhood · Mother Wound",
 "Somebody named you and you answered. Damaged. The addict's daughter. Too much. Not enough. The one who is just like her. A name given in someone's worst moment can follow you for decades, and a family that cannot name its own harm often names the child instead. God gives names in love. Whatever you answer to will run your life, so it is worth asking who gave it to you and whether they had the right.",
 ["Which name have I answered to longest?", "Who gave it to me?", "Does God agree with it?"],
 "Write the old name on a slip of paper. Do not tear it up yet. Just see it from the outside.",
 "Father, You called me by name before anyone else did. Help me hear Yours louder than theirs. Amen.",
 "I belong to God. My name is not the worst thing that was said about me."),
14: ("Trading Names", "Warfare · Childhood",
 "God renames people: Abram to Abraham, Jacob to Israel, Simon to Peter. His names point at who you are becoming. Trading names is not positive thinking. It is putting a new truth where the old one lived. Daughter of an addicted mother becomes daughter of God. Damaged goods becomes new creation. Addict becomes a woman in recovery. Cycle-breaker is a name you get to earn, a day at a time. Say the new one out loud each morning for thirty days.",
 ["The name I am putting down:", "The name I am choosing, and where Scripture says it:", "Who will help me remember it?"],
 "Write the new name where you will see it every morning.",
 "Jesus, I give You the old name. Teach me to answer to the one You give. Amen.",
 "I answer to what God calls me, not what they called me."),
15: ("It Was Not Your Fault. You Were Six Months Old.", "Childhood · Mother Wound",
 "A baby cannot consent, cannot run, cannot tell, cannot choose. A body that responds physically under harm is not agreeing. Shame built a city on that lie. And your mother's failure to stop it was her failure, not yours. Notice how God meets you: not with a lecture but with compassion, the way a father does for his child. Take your name off a crime you did not commit.",
 ["What am I still blaming myself for that was never a choice?", "What do I want to say to a baby who was hurt?", "What would God say to her?"],
 "Say it aloud, as if to a baby you love: \"It was not your fault.\" Then say it to yourself.",
 "Father, You are not angry at the baby I was. Take the blame she picked up and give her compassion. Amen.",
 "I am taking my name off a crime I did not commit."),
16: ("Why You Went Back", "Addiction · Mother Wound",
 "When the first people in your life were unsafe, unsafe can feel like home. Peter failed and went back, and Jesus had already prayed for him and named what came after: when you have turned again. Why you went back to the substance, to people who hurt you, to your mother or your father: it was familiar, it worked, you had no other options, or you hoped it would be different this time. Most people try more than once. The turning again is the story.",
 ["What did I go back to, and what did it give me?", "What was I hoping would be different?", "What do I believe Jesus prayed for me?"],
 "Write, \"I went back because…\" with no excuses and no punishment. Then write, \"And I am turning again.\"",
 "Jesus, You prayed for Peter before he fell. Pray for me. Strengthen me for the turning. Amen.",
 "I was in a trap built to hold. Leaving late is still leaving."),
17: ("Missing the Ones Who Hurt You", "Mother Wound · Addiction",
 "You can miss a mother who did not protect you. You can miss a father who harmed you. You can miss the high. Longing for a parent does not mean the parent was good; it means you were a child who needed one. Cruelty and tenderness on an unpredictable schedule bond people harder than steady kindness. Missing is not evidence you should go back. It is evidence that something in you is still hungry, and God fills the hungry.",
 ["What do I actually miss: them, or what I needed from them?", "What hunger is under it?", "What safe thing could feed that hunger today?"],
 "When the missing hits, say, \"This is hunger, not a sign.\" Then eat, drink water, and call a safe person.",
 "God, I am hungry and tired of feeding it with what hurts. Fill the place only You can fill. Amen.",
 "What I feel is real. It is not a reason to go back."),
18: ("No Memory, No Problem", "Childhood · Warfare",
 "You cannot remember being six months old, and you do not need to. You know what you know from what family told you, from your body, from patterns you live with. You are not lying and you are not making it up. Do not push for memory; do not let anyone lead you to \"recover\" scenes. A trauma-informed counselor can help you work with what the body holds without scripts. God sees the parts you cannot, and the grief of not knowing is real.",
 ["What do I know, and how do I know it?", "What do I wish I could remember, or wish I could un-know?", "What would it mean to let \"enough\" be enough?"],
 "Write one line: \"I know that ___. I do not need to know more to heal.\"",
 "Lord, the dark is not dark to You. Hold what I cannot hold. Give me grace for the gaps. Amen.",
 "I do not need perfect memory to tell the truth or to be loved."),
19: ("What You Did While Surviving", "Addiction · Warfare",
 "Some of you are not haunted only by what was done to you. You are haunted by what you did while surviving: the people you hurt, the things you took, the times you were the dangerous one. That is moral injury, and it is real. It is also not unforgivable. Paul called himself the foremost of sinners and God used him anyway. Forgiveness from God is complete. Repair with people is a separate road, and tomorrow takes it up.",
 ["What did I do that I cannot reconcile with who I wanted to be?", "Who did it touch?", "What part is guilt I can bring to Jesus, and what part is shame that lies?"],
 "Write it in one line. Beneath it write, \"Jesus came for people like me.\"",
 "Jesus, You came for sinners, and I am one. Take what I cannot carry, and lead me to repair what I can. Amen.",
 "I did that. It was mine. Jesus paid for it. I stop punishing someone He pardoned."),
20: ("Living Amends, and Forgiving Yourself", "Addiction · Cycle-Breaking",
 "When you cannot undo the harm, you live differently where the harm lives. Amends are mostly shown: showing up when you said you would, telling the truth, not asking people to take care of your feelings, and not demanding their forgiveness. Where a person is gone or contact is unsafe, serve where that damage lives. And forgive yourself, not because you deserve it but because God decided it. You cannot walk out of the prison while you are still the warden.",
 ["Who needs repair from me, and what would honest repair look like?", "Where is repair unsafe, and what could I do instead?", "What am I still collecting from myself that God already settled?"],
 "Choose one promise you can keep this week, however small, and keep it.",
 "Lord, make me someone who shows up. Where I cannot repair, use me where the damage lives. Amen.",
 "I make amends by becoming someone who does not do that anymore."),
21: ("Two Realms, One Family", "Warfare · Mother Wound",
 "Spiritual warfare is not only for conferences. It meets us in a family where addiction, abuse, and silence ran for years: in what you believe about yourself, in cravings, in who you are drawn to. Scripture treats the unseen opposition as real and limited, and treats ordinary faithfulness as how we stand. You are not imagining what you lived through, and you do not have to make the fight dramatic. You have to show up, tell the truth, and keep Jesus near. People are not demons; the harm done through them was still wrong.",
 ["Where do I see the fight in ordinary moments?", "What have I called \"just my personality\" that might be something else?", "How could I meet it with something simple?"],
 "Pick one ordinary moment today and pray one sentence in it.",
 "Lord, You are in my ordinary day. Teach me to see what is going on beneath the noise, and to stand there with You. Amen.",
 "I am not imagining what I have been through, and I am not fighting it alone."),
22: ("Four Categories at 2 a.m.", "Warfare · Addiction",
 "When something is tormenting you, sort it. What part is body and chemistry (sleep, withdrawal, anxiety)? What part is wound (the old fear)? What part is flesh, your untrained appetite, which needs discipline, not deliverance? What part might be spiritual? Now you have four assignments instead of one impossible one. A craving is usually several at once. Do not label a craving demonic first. Treat the body, tend the wound, build discipline, and bring all of it to God.",
 ["What is tormenting me most right now?", "How would I sort it?", "Who could help me with each part?"],
 "Fill in the four categories for one craving or one fear. Do one small thing under each.",
 "God, give me discernment instead of panic. Teach me to fight the right thing the right way. Amen.",
 "Discernment is not doubt. It is how I stop fighting the wrong thing."),
23: ("What He Cannot Do", "Warfare · Cycle-Breaking",
 "The enemy is a created being, not God's opposite. He is not everywhere, he cannot read your mind, he cannot make you do anything, and he cannot snatch you from God's hand. Your biggest fear may be that you are destined to become your mother. Scripture does not say that. Patterns are strong, and they are not destiny. God keeps those who are His, and He does not promise a trouble-free life; He promises you will not face it alone or unprotected.",
 ["Where has the fear of becoming her been louder than truth?", "What do I believe about what the enemy can do?", "What is God asking me to trust Him with?"],
 "Write: \"I am afraid I will become ___.\" Then write, \"God, this is Yours.\"",
 "Father, You are greater. I give You the fear I have been carrying like a weapon. Keep what I cannot keep. Amen.",
 "He can build a hallway. He cannot move my feet."),
24: ("Standing, Not Cowering", "Warfare",
 "Notice the verb in Ephesians 6: stand. Colossians 2:15 says Christ disarmed the rulers and authorities and put them to open shame. Authority is not volume or a formula. It is standing where Jesus has already won, and it lets you rest. It is also never a reason to skip a doctor, a counselor, a meeting, or a safety plan. Cowering and charging are both ways of forgetting He already won. You were not protected as a child. You can be, now, by Him and by the people He sends.",
 ["Where have I been cowering?", "Where have I been charging in my own strength?", "What would standing look like in one situation this week?"],
 "Stand up, plant your feet, and say aloud, \"I stand in Christ.\" Hold it ten seconds.",
 "Jesus, You disarmed what scared me. Help me stand where You already won. Amen.",
 "I am not negotiating with fear. I am standing on what Christ has already won."),
25: ("Submit, Then Resist", "Warfare · Addiction",
 "The order matters. Submit to God first, then resist. For anyone in addiction, submission begins with an honest admission that you cannot do this on willpower, and that is not defeat; it is where help begins. Resisting without submitting is exhausting. Authority is not volume. Jesus answered temptation with a sentence of Scripture. Loud is for our own fear.",
 ["What am I trying to handle in my own strength?", "What would submitting to God look like there?", "What is one thing I can resist this week once I am under His care?"],
 "Say aloud, \"I cannot do this alone. Jesus, I am Yours.\" Then do one resisting thing.",
 "God, I give You my will, my plan, and my pride. Under Your care, I will stand against what harms me. Amen.",
 "I get under God before I stand against anything."),
26: ("What Keeps Getting Fed: Anger at Both Parents", "Warfare · Mother Wound",
 "Some struggles keep getting fed by the same things: unforgiveness, lies about yourself, anger left to rot, old vows, substances. Paul says anger is not the problem. Holding it past sundown gives the enemy room. Your anger at your father and your mother is not wrong; it is information that you were wronged. The work is to bring it to God and to safe people, so it does not spill on yourself, on your recovery, or on people who did not cause it.",
 ["Where does my anger really belong?", "How have I been feeding it, knowingly or not?", "Where can I safely put it?"],
 "Name your anger in one line. Then do one physical thing with it: walk hard, scrub something, push a wall.",
 "Lord, You are not afraid of my anger. Take it, and keep it from feeding on me. Amen.",
 "Everything I can name, I can bring to God and begin to change."),
27: ("Taken In", "Mother Wound · Warfare",
 "Before anything else, get under cover. David knew what it was to be left: his father and mother had forsaken him, and the Lord took him in. You do not have to pretend your parents were safe in order to receive a safe God. Say who you belong to. Say what you cannot do alone. This is not a spell, and it does not guarantee a trouble-free life. It is a child running to the one who is bigger, and being taken in.",
 ["Who failed to take me in?", "What would it mean to be taken in by God?", "What do I want covered today?"],
 "Pray aloud in your own words: \"I belong to You. Take me in and cover me today.\"",
 "Father, You take me in. I run to You. I do not go in uncovered. Amen.",
 "I do not go in alone and I do not go in uncovered.",
 ("Psalm 27:10", "For my father and my mother have forsaken me, but the LORD will take me in.")),
28: ("Forgiving a Mother Who Did Not Protect You", "Mother Wound · Warfare",
 "Forgiveness is not saying it was okay and not reconciliation. It is releasing the right to collect. A mother who did not protect you, perhaps because of her own trauma and addiction, still did not protect you. Both are true: she may have been hurt and she hurt you. Forgive in pieces if you have to, out loud, one thing at a time, and let God keep the ledger. If she is gone, forgiveness can happen without her. You can forgive fully and keep every boundary.",
 ["What specifically do I need to forgive her for?", "What do I fear forgiveness would mean?", "What would I keep, even after forgiving?"],
 "Choose one specific thing and say, \"I release this to You, God. I am not available for more harm.\"",
 "Lord, I am tired of being her jailer and her prisoner. I release it to You. Keep me safe. Amen.",
 "I refuse to be her jailer and her prisoner at the same time."),
29: ("Forgiven Is Not Back In", "Mother Wound · Warfare",
 "Forgiveness is between you and God. Reconciliation requires two people and real repentance. Where someone has harmed you or could harm you, safety decides access, not guilt or family pressure. Jesus withdrew often, and Paul named people and told others to avoid them. If your mother or father reaches out, you have options: no contact, limited contact, contact with conditions. This is not unforgiveness. It is wisdom, and in recovery it may be survival.",
 ["Who have I let back in because I thought forgiving required it?", "What does safety actually require right now?", "Who can help me hold the line?"],
 "Write one boundary about contact with a parent. Tell one safe person.",
 "God, give me wisdom, not just kindness. Help me guard what You have given me to guard. Amen.",
 "I forgive completely. I am not available for more harm."),
30: ("Armor for the Daughter Who Wasn't Protected", "Warfare · Cycle-Breaking",
 "Thirty seconds, out loud, before the day puts anything on you. Truth: I will not lie to myself today. Righteousness: I am covered by His, not mine. Peace: I bring it into rooms; I do not take chaos from them. Faith, salvation, the Word, prayer. This is the covering you did not get as a baby, given now by Someone who does not fail. Notice there is no armor for the back; you are built to stand, not run.",
 ["Which piece of armor do I forget most?", "What is coming at me today that I need to prepare for?", "Who do I want to be covered by?"],
 "Say it aloud for thirty seconds today, standing.",
 "Lord, I put on what You gave me. Keep me upright today, and keep my eyes on You. Amen.",
 "I put it on before the day puts anything on me."),
}
